### ISSUE TITLE
Code blocks in org-mode not highlighted

### ISSUE THREAD

**Issue by jiri** [gollum/gollum#1192] opened 2017-02-02 01:53 UTC
I've installed pygments, but that doesn't seem to have done anything. As far as I know, I'm using the newest versions of all the gems. I don't really see a lot of documentation on setting up pygments, I assume no extra configuration is required?

**Comment by bartkamphorst** [comment] 2017-02-20 12:20
As I recall, you need to have Python installed with `Pygments` as well as the `pygments.rb` gem. Gollum will try to use pygments.rb automatically, but will fall back on `rouge` for syntax highlighting if pygments cannot be found.

**Comment by jiri** [comment] 2017-02-20 15:32
> I've installed pygments
> As far as I know, I'm using the newest versions of all the gems

I have both installed.

**Comment by bartkamphorst** [comment] 2017-02-20 15:59
And is it just org-mode or other code blocks that fail to be highlighted?

**Comment by jiri** [comment] 2017-02-20 16:03
Markdown works fine, org-mode isn't highlighted at all. The source blocks seem to be untouched, the issue doesn't seem to be a missing CSS file, since the source isn't even tokenized and classified. I haven't tried other modes than markdown and org-mode.

**Comment by bartkamphorst** [comment] 2017-02-20 16:07
Is the `org-ruby` gem installed?

**Comment by jiri** [comment] 2017-02-20 16:15
Yup, the org file is processed correctly as far as headings and such go, the only defective part is the code highlighting.

**Comment by bartkamphorst** [comment] 2017-02-20 21:55
What about backtick-style code blocks (within org-mode page), are they highlighted?

**Comment by jiri** [comment] 2017-02-21 14:08
I haven't tried those, as they aren't part of the org-mode syntax.

**Comment by bartkamphorst** [comment] 2017-03-26 19:04
I'm trying to reproduce your issue. Without Pygments, the following code block from http://orgmode.org/manual/Literal-examples.html renders just fine:
  #+BEGIN_SRC emacs-lisp
      (defun org-xor (a b)
        "Exclusive or."
       (if a (not b) b))
  #+END_SRC`
![screen shot 2017-03-26 at 9 02 28 pm](https://cloud.githubusercontent.com/assets/571173/24334250/931aa270-1267-11e7-86ca-59ad199814d8.png)

Is there any particular reason you need Pygments instead of Rouge highlighting?

**Comment by bartkamphorst** [comment] 2017-03-26 21:11
Cannot reproduce either with Pygments installed; closing the issue until further notice.

**Closed by bartkamphorst** 2017-03-26 21:11 UTC
Labels: Org-Mode
