### ISSUE TITLE
Seems to be very complicated to serve the current directory

### ISSUE THREAD

**Issue by zoechi** [gollum/gollum#1702] opened 2021-03-23 17:46 UTC
**Please read the [CONTRIBUTION GUIDELINES](https://github.com/gollum/gollum/blob/master/CONTRIBUTING.md) before submitting!**

If your have problems using or installing the software which stem from bugs in the software or a lack of documentation, we are always happy to help out! However, **for ordinary usage questions, please consider asking elsewhere**, for instance on [StackOverflow](http://stackoverflow.com/questions/tagged/gollum-wiki).

**Describe the bug**
I can't serve a Git repo with *.md files in the repo root repository

**To Reproduce**
1. Checkout gitlab Wiki repo
2. Rename `home.md` to `Home.md`
3. Run `gollum .` or `gollum --page-file-dir=.` 
4. Open `localhost:4567`
5. Browser redirects to `http://localhost:4567/gollum/create/Home` which does not exist.

It also shows `NOTE: This page will be created within the "/create" directory`
Why would anyone want a `/create` directory?

**Expected behavior**
Serving files from the directory where gollum was started (repo root) should be easier.

Where does this `gollum` directory come from? How can I get rid of it?

**Screenshots**

**Environment Info**

Always include the output of the `gollum --versions` command (NB: `versions` in plural).
```
gollum --versions
Gollum 5.2.1
Running on: x86_64-linux-gnu with Ruby version 2.5.5
Using:
rugged 0.99.0
gollum-rugged_adapter 1.0
gollum-lib 5.1
Markdown rendering gem: kramdown
Other renderering gems:
org-ruby 0.9.12
```

**Comment by dometto** [comment] 2021-03-24 10:42
Hi @zoechi. Can you just confirm that you are committing the file `Home.md` to the repository after having renamed it? `gollum .` or even just `gollum` just works for me, so I think the problem is just that `Home.md` is not being found in the repo.

Feel free to reopen this issue if the file is properly committed to the repo and it nevertheless doesn't work!

**Closed by dometto** 2021-03-24 10:42 UTC

**Comment by bartkamphorst** [comment] 2021-03-24 14:13
> It also shows NOTE: This page will be created within the "/create" directory

This is a peculiar warning though. @dometto Can you reproduce this part?

**Comment by dometto** [comment] 2021-03-24 20:17
I can't reproduce that, neither with the `--page-file-dir .` option nor without it. @zoechi is it possible that you accidentally ended up creating the `create` directory in an attempt to debug this problem? If you need help debugging the issues, please supply the output of `git ls-files`
