### ISSUE TITLE
create a page under another page failed

### ISSUE THREAD

**Issue by xu4wang** [gollum/gollum#962] opened 2015-01-27 16:28 UTC
Create a page named sub_page under page sandbox, caused:

```
Internal Server Error
undefined method `join' for #<String:0x007f9cecd4bee0>
```

my gollum command line:
```
WangXudeMacBook-Pro:~ wangxu$ ps -ef | grep ruby
  501   764   760   0 12:07上午 ttys002    0:05.79 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby /usr/bin/gollum --host 127.0.0.1 --port 9046 --config /Users/wangxu/Documents/gollum_wiki/config.rb --css --live-preview --allow-uploads page --page-file-dir wiki /Users/wangxu/Documents/gollum_wiki
```

The logs are:

```
localhost - - [28/Jan/2015:00:23:21 CST] "GET /create/favicon.ico HTTP/1.1" 200 6733
- -> /create/favicon.ico
Encoding::CompatibilityError - incompatible character encodings: UTF-8 and ASCII-8BIT:
	/Library/Ruby/Gems/2.0.0/gems/gitlab-grit-2.7.3/lib/grit/index.rb:176:in `%'
	/Library/Ruby/Gems/2.0.0/gems/gitlab-grit-2.7.3/lib/grit/index.rb:176:in `block in write_tree'
	/Library/Ruby/Gems/2.0.0/gems/gitlab-grit-2.7.3/lib/grit/index.rb:171:in `each'
	/Library/Ruby/Gems/2.0.0/gems/gitlab-grit-2.7.3/lib/grit/index.rb:171:in `write_tree'
	/Library/Ruby/Gems/2.0.0/gems/gitlab-grit-2.7.3/lib/grit/index.rb:198:in `block in write_tree'
	/Library/Ruby/Gems/2.0.0/gems/gitlab-grit-2.7.3/lib/grit/index.rb:180:in `each'
	/Library/Ruby/Gems/2.0.0/gems/gitlab-grit-2.7.3/lib/grit/index.rb:180:in `write_tree'
	/Library/Ruby/Gems/2.0.0/gems/gitlab-grit-2.7.3/lib/grit/index.rb:198:in `block in write_tree'
	/Library/Ruby/Gems/2.0.0/gems/gitlab-grit-2.7.3/lib/grit/index.rb:180:in `each'
	/Library/Ruby/Gems/2.0.0/gems/gitlab-grit-2.7.3/lib/grit/index.rb:180:in `write_tree'
	/Library/Ruby/Gems/2.0.0/gems/gitlab-grit-2.7.3/lib/grit/index.rb:123:in `commit'
	/Library/Ruby/Gems/2.0.0/gems/gollum-grit_adapter-0.1.2/lib/grit_adapter/git_layer_grit.rb:240:in `commit'
	/Library/Ruby/Gems/2.0.0/gems/gollum-lib-4.0.2/lib/gollum-lib/committer.rb:170:in `commit'
	/Library/Ruby/Gems/2.0.0/gems/gollum-lib-4.0.2/lib/gollum-lib/wiki.rb:353:in `write_page'
	/Library/Ruby/Gems/2.0.0/gems/gollum-3.1.2/lib/gollum/app.rb:318:in `block in <class:App>'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/Library/Ruby/Gems/2.0.0/gems/gollum-3.1.2/lib/gollum/editing_auth.rb:13:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/nulllogger.rb:9:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/nulllogger.rb:9:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
[2015-01-28 00:23:31] ERROR NoMethodError: undefined method `join' for #<String:0x007f9cecd4bee0>
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:37:in `rescue in call'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
localhost - - [28/Jan/2015:00:23:31 CST] "POST /create HTTP/1.1" 500 340
http://127.0.0.1:9046/create/wiki/sandbox/subpage -> /create
localhost - - [28/Jan/2015:00:23:31 CST] "GET /favicon.ico HTTP/1.1" 302 0
- -> /favicon.ico
localhost - - [28/Jan/2015:00:23:31 CST] "GET /create/favicon.ico HTTP/1.1" 200 6733
- -> /create/favicon.ico


```

**Comment by dometto** [comment] 2015-01-27 16:48
The problem is with using unicode. This is a duplicate of #100.

**Comment by dometto** [comment] 2015-01-27 16:48
Sorry, duplicate of https://github.com/gollum/gollum/issues/843 I mean.

**Closed by dometto** 2015-01-27 16:48 UTC
