### ISSUE TITLE
5.x Javascript tags are missing correct mime-type

### ISSUE THREAD

**Issue by petrkalina** [gollum/gollum#1496] opened 2020-03-24 15:42 UTC
When editing page, the served html contains:

```
  <script src="/gollum/assets/app-982c7fca1832732a24e92474ca2729aeb56f2d0c05bb7a8ff913e9f58a6500d5.js"></script>
  <script src="/gollum/assets/editor-da03e90b6d201aca7f6a4d53360d9c31befb005e038abfd152bbf48b316e771e.js"></script>
```

which conflict with https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options in case the data is served via https.  The same snippet should read:

```
  <script src="/gollum/assets/app-982c7fca1832732a24e92474ca2729aeb56f2d0c05bb7a8ff913e9f58a6500d5.js" type="text/javascript"></script>
  <script src="/gollum/assets/editor-da03e90b6d201aca7f6a4d53360d9c31befb005e038abfd152bbf48b316e771e.js" type="text/javascript"></script>
```

**Comment by dometto** [comment] 2020-03-24 16:29
This looks like a bug in `sprockets-helpers`, which is generating the `script` tags without mime-type. How big of a problem is this in Firefox, i.e. what kind of errors/warning are being thrown? https://github.com/petebrowne/sprockets-helpers/ doesn't seem to be very well maintained but perhaps opening an issue/PR there could help?

The relevant code is here: https://github.com/petebrowne/sprockets-helpers/blob/master/lib/sprockets/helpers.rb#L172

(And perhaps correspondingly for CSS?)

If this is a major problem, we can try to modify the tag returned by sprockets in our own view helpers.

**Comment by dometto** [comment] 2020-03-24 20:06
To be clear, this is an issue with all javascript tags generated by `sprockets_helpers`, and is not specific to the edit view.

**Comment by petrkalina** [comment] 2020-03-25 11:31
```
The resource from “https://{domain}:8646/gollum/assets/editor-da03e90b6d201aca7f6a4d53360d9c31befb005e038abfd152bbf48b316e771e.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
```

resulting in:

<img width="853" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77532086-74ae0c00-6e94-11ea-9017-e629d7d40e16.png">

**Comment by dometto** [comment] 2020-03-25 11:34
Is a similar error thrown for the stylesheet tags or not?

**Comment by petrkalina** [comment] 2020-03-25 11:36
<img width="908" alt="Screenshot 2064" src="https://user-images.githubusercontent.com/1150350/77532513-4846bf80-6e95-11ea-970d-bbdabd31df9a.png">

.. no

**Comment by petrkalina** [comment] 2020-03-25 11:37
I think I will be able to disable this header on the secure proxy.. Which is a workaround for now..

**Comment by dometto** [comment] 2020-03-25 11:38
I've opened a PR at `sprockets-helper`. Let's see if they respond. As I said, if not, we can address the issue in our own view helpers.

**Comment by petrkalina** [comment] 2020-03-25 14:33
Tested locally now..

<img width="1336" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77547656-c616c500-6ead-11ea-9c01-cbb0f31b2610.png">

<img width="1473" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77547767-e8104780-6ead-11ea-9351-c9c676113953.png">

**Comment by dometto** [comment] 2020-03-25 14:39
My PR was merged, so updating to `sprockets-helpers v.1.2.2` should solve the issue. (`bundle update`, or manually uninstall and reinstall sprockets-helpers with `gem uninstall`, `gem install -v 1.2.2`, `bundle install`). Let me know if this resolves the issue with https.

**Comment by petrkalina** [comment] 2020-03-26 08:00
Tested.. I'm super sorry to report (as you asked this exact question before) that I have an issue now with the stylesheets for the same reason:

<img width="1339" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77623297-23f3ed00-6f40-11ea-8ea5-35b84d254a17.png">

<img width="1409" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77623269-19395800-6f40-11ea-9923-55c4b4af4141.png">

.. in source there is really the mime type missing..

<img width="868" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77623356-42f27f00-6f40-11ea-84a1-6287240d5bf1.png">

**Comment by dometto** [comment] 2020-03-26 09:15
Also proposed a PR for this at sprockets-helpers. Hopefully it will be merged soon

**Comment by petrkalina** [comment] 2020-03-26 12:56
JFYI:

testing with:

```
[submodule "gollum"]
        path = gollum/gollum
        url = https://github.com/gollum/gollum
        branch = 5.x
```

seeing:

```
bundle install --gemfile gollum/Gemfile
...
Using gollum-lib 5.0.a.4 from https://github.com/gollum/gollum-lib.git (at gollum-lib-5.x@a008b4b)
...
Fetching sprockets 3.7.2
Installing sprockets 3.7.2
Fetching sprockets-helpers 1.2.2
Installing sprockets-helpers 1.2.2
```

but when I view the page, it looks like this:

<img width="321" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77648919-3898ab00-6f69-11ea-8947-62504d116088.png">

due to:

<img width="1407" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77648940-42baa980-6f69-11ea-85bd-5f81726613a3.png">

but also, when I try to edit a page, I see:

<img width="559" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77649000-59610080-6f69-11ea-848f-f810387f1b25.png">

and 

<img width="1431" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77649019-6120a500-6f69-11ea-9129-52db95329e2a.png">

.. so it seems that the mime type is still incorrect in the js reference as well - even if I see:

<img width="857" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77649122-91684380-6f69-11ea-870a-dcf36e8156d6.png">

in the page source..

**Comment by petrkalina** [comment] 2020-03-26 13:03
Following the link from here:

<img width="695" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77649502-43077480-6f6a-11ea-94ac-5342a3f6dfb3.png">

i.e. https://html.spec.whatwg.org/multipage/scripting.html#javascript-mime-type

I see:
<img width="720" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77649464-308d3b00-6f6a-11ea-91b7-50516e88be99.png">

so it seems all should be good - so I'm not sure what's up

**Comment by petrkalina** [comment] 2020-03-26 13:13
I think the priblem is rather the the script link does not exist as well as the css:

```
  <link rel="stylesheet" href="/gollum/assets/app-1f77d3951828aebecd9c3f65f60028b0e70972cceb3badf85bfa9004a92e552c.css" media="all">

  <link rel="stylesheet" href="/gollum/assets/print-c70ea78d9c87a4546733a2f2288fbf1f93fa8510890ac73cac6db8a784e27429.css" media="print">

  <script src="/gollum/assets/app-982c7fca1832732a24e92474ca2729aeb56f2d0c05bb7a8ff913e9f58a6500d5.js" type="text/javascript"></script>

  <script src="/gollum/assets/editor-da03e90b6d201aca7f6a4d53360d9c31befb005e038abfd152bbf48b316e771e.js" type="text/javascript"></script>
```

found:

<img width="1201" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77650426-c5446880-6f6b-11ea-9d26-3cbaf8be8714.png">

<img width="1462" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77650469-d42b1b00-6f6b-11ea-8ea3-6392aadb7033.png">

.. not found:

<img width="1232" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77650384-b8277980-6f6b-11ea-99fb-344d75cd1029.png">

<img width="1230" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77650497-e016dd00-6f6b-11ea-9942-85b921405d37.png">

**Comment by petrkalina** [comment] 2020-03-26 13:16
I see

```
./lib/gollum/public/assets/editor-2ea2ba8b37655af601c89ba4e9680989279ffe12c489c85c8e2858df5e5d1f4a.js
./lib/gollum/public/assets/app-982c7fca1832732a24e92474ca2729aeb56f2d0c05bb7a8ff913e9f58a6500d5.js
root@gollum-v5-1:/gollum# 
```

vs the refs from the html:

```
/gollum/assets/app-982c7fca1832732a24e92474ca2729aeb56f2d0c05bb7a8ff913e9f58a6500d5.js
/gollum/assets/editor-da03e90b6d201aca7f6a4d53360d9c31befb005e038abfd152bbf48b316e771e.js
```

.. i.e. the editor link does not match..

**Comment by dometto** [comment] 2020-03-26 14:34
Oops, that's a bug with the packaged static assets. You can fix this locally by running `bundle exec rake precompile`. I'll open a PR to fix that ASAP.

**Comment by dometto** [comment] 2020-03-26 14:41
Should now be fixed in 5.x too. Thanks for the report!

Does the "no sniff" issue for stylesheets remain?

**Comment by petrkalina** [comment] 2020-03-26 15:38
```

**Comment by dometto** [comment] 2020-03-26 15:45
That is weird, not seeing this locally. Could it be some strange caching issue? What happens when you run `bundle exec rake precompile`? Any difference in behavior? Running `git status` after that should tell you if it generated any new assets.

**Comment by petrkalina** [comment] 2020-03-26 16:06
Maybe it is caching somewhere within the ruby libs' system, otherwise I do not believe so, as I always start from 0 .. using a dockerfile. However, with the `rake precompile` command it works. JFYI this is my dockerfile:

```
FROM ruby

RUN apt-get -y update \
    && apt-get -y install cmake \
    && apt-get -y install nodejs \
    && rm -rf /var/lib/apt/lists/*

RUN gem install github-markdown

COPY gollum /gollum
RUN bundle install --gemfile gollum/Gemfile

COPY config.rb /gollum/config.rb
WORKDIR /gollum
RUN bundle exec rake precompile

ENTRYPOINT ["bundle", "exec", "bin/gollum", "--config", "config.rb", "--port", "80", "/wiki"]
EXPOSE 80
```

**Comment by dometto** [comment] 2020-03-26 16:20
I was wondering whether it could be browser caching?

I'm a little worried as I still can't reproduce this. On a fresh 5.x install, my app requests the `/gollum/assets/editor-2ea2ba8b37655af601c89ba4e9680989279ffe12c489c85c8e2858df5e5d1f4a.js` file (correct).

After running `precompile`, are there any new files generated? You should be able to see this when you run `git status`

**Comment by petrkalina** [comment] 2020-03-26 16:23
Hard for me to test, as I use gollum as submodule of a repository where my docker images are .. and the precompile runs in the container .. in which gollum is only present as a folder, not a git repository..

**Comment by dometto** [comment] 2020-03-26 17:38
Give it a try with a fresh 5.x and a different browser thought, to avoid caching there?

**Comment by bartkamphorst** [comment] 2020-03-26 19:48
I did the following, hoping to replicate the issue:
* git clone https://github.com/gollum/gollum.git
* git fetch origin
* git checkout 5.x
* bundle install
* bundle exec gollum

In this scenario, though, everything seems to be in working order: Pages and the editor are working normally. See here for the Network info:

![Screen Shot 2020-03-26 at 20 47 03](https://user-images.githubusercontent.com/571173/77690081-07d56780-6fa3-11ea-87af-98372c18dc1c.png)

**Comment by dometto** [comment] 2020-03-27 09:33
Could be an old .css file remained in place in the `public/assets` directory on @petrkalina's installation. In that case, sprockets might find that file before the correct one. Should be able to fix by:

1. `rm -rf lib/gollum/public/assets/`
2. `git checkout lib/gollum/public/assets/`

**Comment by petrkalina** [comment] 2020-03-27 15:11
While testing other feature today, I verified All is working also without the `bundle exec rake precompile` Command. However, I still see missing mime for the CSS:

<img width="884" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77770478-98648400-7045-11ea-9ecd-463683a1b369.png">

**Comment by dometto** [comment] 2020-03-27 15:15
👍 thanks for the feedback again. My new PR for the mime type in CSS tests has been merged at sprockets-helpers meanwhile, so updating that should fix the last issue!

**Closed by dometto** 2020-03-27 15:15 UTC
