### ISSUE TITLE
Redirects to incorrect page when being served behind nginx proxy

### ISSUE THREAD

**Issue by chardskarth** [gollum/gollum#2027] opened 2024-01-22 12:05 UTC
**Describe the bug**
Probably related to #1149. I created [this repo](https://github.com/chardskarth/gollum-behind-nginx) to replicate . The 3rd and 4th link unexpectedly redirects to path that omits the ports. 

**To Reproduce**
1. Clone https://github.com/chardskarth/gollum-behind-nginx (include the submodule)
2. Click on the links in the readme page

**Expected behavior**
It should still serve the page correctly since nginx proxy usually works enough to most of my use case.

**Environment Info**

v5.3.2

**Comment by dometto** [comment] 2024-01-23 11:41
Hi @chardskarth, it seems to me the trouble you're running into is due to the docker port mapping in your example. I can reproduce the issue when I run the nginx service with port 80 mapped to port 3002 on the host, but *not* when I map port 80 to port 80 on the host (this requires the `privileged` setting for the nginx container). The reverse proxy is just redirecting the browser to the port that nginx runs on *in the container*, since it doesn't know that it's being mapped to port 3002.

Like I said, one option is to make the nginx service available on port 80 on the host. Alternatively, you can use the nginx SetHost directive to tell the reverse proxy to tell the browser to connect to the right port.

There's an additional issue with the gollum instance with `--base-path` enabled, which I can fix simply by changing the reverse proxy URL. I'll paste my final nginx config below.

In any case, this doesn't seem like a bug in gollun to me, but more of getting gollum, nginx, and Docker to play well together. Let me know if I'm missing anything!

**Comment by dometto** [comment] 2024-01-23 11:45
Working nginx config:

```
server {
  listen 80;
  server_name ${GOLLUM_HOST};

  location / {
    proxy_pass http://${GOLLUM_DOCKER_HOSTNAME}:${GOLLUM_DOCKER_PORT}/;
    proxy_set_header Host $host:3002;
  }
}

server {
  listen 80;
  server_name ${GENERIC_HOSTNAME};

  location /wiki {
    proxy_pass http://${GOLLUM_DOCKER_HOSTNAME_WITHPATH}:${GOLLUM_DOCKER_PORT}/wiki;
    proxy_set_header Host $host:3002;
  }
}
```

**Comment by dometto** [comment] 2024-01-23 11:46
Will close this, but let me know if I've missed anything and this needs to be reopened. :)

**Closed by dometto** 2024-01-23 11:46 UTC

**Comment by chardskarth** [comment] 2024-02-22 12:55
Hi man. Thanks a lot for this. Will try this out.
