### ISSUE TITLE
Allow Gollum to understand Markdown pages in any directory

### ISSUE THREAD

**Issue by marco-brandizi** [gollum/gollum#1145] opened 2016-07-02 11:08 UTC
Hi all, 

not sure wether this is already possibile, or some other issue exists for it (it's discussed in [issue 137](https://github.com/gollum/gollum/issues/137)). I keep some documentation pages (.md files) inside the code repository, they're not just README and I do not wish to move those to a separated wiki repository, because people are just fine with browsing the code repository (from GitHub web) and finding those pages around.

My question is: is there a way to make Gollum understand those .md files and permit editing functionality over them? If not, I'm proposing to support this in future versions. So far, I've tried to run Gollum from the repo clone, to run it with `--bare`, to run it with `--page-file-dir`, nothing worked, it doesn't see existing .md files, when you write them explicitly in the URL, it proposes to create a new page, when you create a 'test' page, apparently it doesn't create anything.

**Comment by dometto** [comment] 2016-07-13 20:53
I'm not sure what the issue is here. Gollum does support markdown format. Are you sure the `.md` files in your repo are committed? Gollum as of yet does not support viewing or editing uncommitted files (see #1031).

**Closed by dometto** 2016-07-13 20:53 UTC

**Comment by marco-brandizi** [comment] 2016-07-13 21:16
Sorry, they were committed, but I'm working on a branch other than master, I've just discovered the -r/--ref option. Stupid me, sorry.
