### ISSUE TITLE
RDoc throwing TypeError when generating documentation

### ISSUE THREAD

**Issue by claman** [gollum/gollum#1961] opened 2023-03-30 13:44 UTC
**Describe the bug**

On running `gem update`:

```
ERROR:  While executing gem ... (RDoc::Error)
    error generating ~/.rvm/gems/ruby-2.7.2/doc/gollum-5.3.1/rdoc/lib/gollum/helpers_rb.html: nil can't be coerced into Integer (TypeError)
```

**Environment Info**

```
Gollum 5.3.1
Running on: x86_64-darwin20 with Ruby version 2.7.2
Using:
rugged 1.6.3
gollum-rugged_adapter 2.1.0
gollum-lib 5.2.4
Markdown rendering gem: commonmarker
Other renderering gems:
none
```

**Comment by benjaminwil** [comment] 2023-04-06 21:13
Hey, thanks for reporting this issue.

I have been unable to reproduce this issue so far. Here's how I tried to reproduce:

1. I installed Ruby 2.7.2.
2. `gem install gollum:5.1.0`
3. `gem update gollum`

I saw Gollum successfully update and did not get an `RDoc::Error`. RDoc succeeded.

Given the copied error message, I'm unsure which helper could have raised this error.

I also attempted to `gem update gollum` on Ruby 3 and did not encounter this error. Given that Ruby 2.7 is now past [its end of life](https://www.ruby-lang.org/en/downloads/branches/), and we don't yet have evidence that this is a persistent issue on newer Rubies, I will close this issue for now.

Please do reopen if you can report additional reproduction instructions or you can't workaround this issue!

**Closed by benjaminwil** 2023-04-06 21:13 UTC
