### ISSUE TITLE
Asciidoc include issues

### ISSUE THREAD

**Issue by craibuc** [gollum/gollum#942] opened 2015-01-16 17:28 UTC
## AsciiDoc include AsciiDoc
I'm attempting to include an `AsciiDoc` file in another `AsciiDoc` file:

/AsciiDoc-Code.asciidoc:

<pre>
=== AsciiDoc Code
AsciiDoc formatted code.

[source,ruby]
----
[1,2,3].each do |x|
  puts x
end
---- 
</pre>

/AD-parent.asciidoc:

<pre>
included content here:

[[include:AsciiDoc-Code]]
</pre>

### Results

The included content is not rendered: [Imgur](http://i.imgur.com/Su1JLpE.png)

## Heterogeneous includes 
Heterogeneous includes don't work in AsciiDoc 'parents', but do in Markdown 'parents'.  Moreover, syntax highlighting isn't preformed in `AsciiDoc`, but is with Markdown:

/AsciiDoc-Code.asciidoc:

<pre>
=== AsciiDoc Code
AsciiDoc formatted code.

[source,ruby]
----
[1,2,3].each do |x|
  puts x
end
---- 
</pre>

/Markdown-Code.md:

<pre>
### Markdown Code
Markdown formatted code.

```ruby
[1,2,3].each do |x|
  puts x
end
```
</pre>

/includes/Code-MD.md:

<pre>
### Code
Attempt to include files from different directories.

[[include:/Markdown-Code]]

[[include:/AsciiDoc-Code]]
</pre>

### Results
Include content (of both types) is rendered, but AsciiDoc syntax is not highlighted: [Imgur](http://i.imgur.com/3ELHPql.png)

/includes/Code-AD.asciidoc:

<pre>
=== Code
Attempt to include files from different directories.

[[include:/Markdown-Code]]

[[include:/AsciiDoc-Code]]
</pre>

Results

Include content is not rendered: [Imgur](http://i.imgur.com/4aPMlI9.png)

**Comment by dometto** [comment] 2015-01-16 20:00
Include issue is a known issue, duplicate of #878 (see also #914). Syntax highlighting in asciidoc is a duplicate of #280, now fixed in gollum-lib `HEAD`. This will be in the next patch-level release of gollum-lib.

**Closed by dometto** 2015-01-16 20:00 UTC
