### ISSUE TITLE
Migration script throws Rugged::OS Error when using wrong argument order

### ISSUE THREAD

**Issue by DanSman** [gollum/gollum#1534] opened 2020-04-01 02:25 UTC
Hi 

I'm trying to update to the new version of Gollum.

Before I start with my issue, I would like to explain how I installed it on my Arch system. 
The installation process is based on version 4.

## Packages
```
sudo pacman -S ruby ruby-rdoc cmake
mkdir -p /home/user/your/wiki/path
git init /home/user/your/wiki/path
gem install gollum
gem install github-markdown
```

&nbsp;

## Copy files

Copy `config.rb`, `public` and the `templates` into your wiki. 
```
cp /home/user/.gem/ruby/2.7.0/gems/gollum-4.1.4/config.rb /home/user/your/wiki/path/config.rb
cp -r /home/user/.gem/ruby/2.7.0/gems/gollum-4.1.4/lib/gollum/public/gollum /home/user/your/wiki/path/public
cp -r /home/user/.gem/ruby/2.7.0/gems/gollum-4.1.4/lib/gollum/templates /home/user/your/wiki/path/public/templates
```

&nbsp;

## gollum.service
```
sudo nano /lib/systemd/system/gollum.service
```
```
[Unit]
Description=Gollum wiki server
After=network.target

[Service]
Type=simple
User=user
Group=user
WorkingDirectory=/home/user/your/wiki/path
ExecStart=/bin/bash -c "PATH=/home/user/.gem/ruby/2.7.0/bin:$PATH exec gollum --config /home/user/your/wiki/path/config.rb --template-dir /home/user/your/wiki/path/public/templates/" 
Restart=on-abort

[Install]
WantedBy=multi-user.target
```

So now I try to run the migration file. I have copied the file to `/usr/bin` and want to run the command `gollum-migrate-tags --write /home/my/software/gollum/` and get the following error message:
```
/home/my/.gem/ruby/2.7.0/gems/gollum-rugged_adapter-0.99.4/lib/rugged_adapter/git_layer_rugged.rb:562: warning: Using the last argument as keyword parameters is deprecated
Traceback (most recent call last):
        7: from /usr/bin/gollum-migrate-tags:234:in `<main>'
        6: from /usr/bin/gollum-migrate-tags:234:in `new'
        5: from /home/my/.gem/ruby/2.7.0/gems/gollum-lib-5.0.2/lib/gollum-lib/wiki.rb:127:in `initialize'
        4: from /home/my/.gem/ruby/2.7.0/gems/gollum-lib-5.0.2/lib/gollum-lib/wiki.rb:127:in `new'
        3: from /home/my/.gem/ruby/2.7.0/gems/gollum-lib-5.0.2/lib/gollum-lib/git_access.rb:16:in `initialize'
        2: from /home/my/.gem/ruby/2.7.0/gems/gollum-lib-5.0.2/lib/gollum-lib/git_access.rb:16:in `new'
        1: from /home/my/.gem/ruby/2.7.0/gems/gollum-rugged_adapter-0.99.4/lib/rugged_adapter/git_layer_rugged.rb:562:in `initialize'
/home/my/.gem/ruby/2.7.0/gems/gollum-rugged_adapter-0.99.4/lib/rugged_adapter/git_layer_rugged.rb:562:in `new': failed to resolve path '--write': No such file or directory (Rugged::OSError)
```

Dry run `gollum-migrate-tags /home/my/software/gollum/` works well and shows me everything that needs to be changed. 

I hope you can help me with this.

Thanks
Dan

**Comment by dometto** [comment] 2020-04-01 08:48
@DanSman thanks for reporting in! I'm afraid the problem is that the mgiration script is just a little dumb, and assumes the first argument to be the path to the repository. `gollum-migrate-tags  /home/my/software/gollum/ --write` will work!

I realize this is not explicitly stated in the script's help documentation, apologies for that.

**Comment by DanSman** [comment] 2020-04-01 19:35
Hi

Thanks for reply.

I tried that already. It takes only the first argument. I also tried:
`gollum-migrate-tags --config /home/my/software/gollum/config.rb --page-file-dir /home/my/software/gollum/ --prefer-relative-links --hyphenate --write`

```
Traceback (most recent call last):
        3: from /usr/bin/gollum-migrate-tags:98:in `<main>'
        2: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/home/my/software/gollum/config.rb:51:in `<top (required)>': uninitialized constant Precious (NameError)
Did you mean?  Process
```

If I go for `gollum-migrate-tags --page-file-dir /home/my/software/gollum/ --prefer-relative-links --hyphenate --write`:
```
/home/my/.gem/ruby/2.7.0/gems/gollum-rugged_adapter-0.99.4/lib/rugged_adapter/git_layer_rugged.rb:562: warning: Using the last argument as keyword parameters is deprecated
Traceback (most recent call last):
        7: from /usr/bin/gollum-migrate-tags:234:in `<main>'
        6: from /usr/bin/gollum-migrate-tags:234:in `new'
        5: from /home/my/.gem/ruby/2.7.0/gems/gollum-lib-5.0.2/lib/gollum-lib/wiki.rb:127:in `initialize'
        4: from /home/my/.gem/ruby/2.7.0/gems/gollum-lib-5.0.2/lib/gollum-lib/wiki.rb:127:in `new'
        3: from /home/my/.gem/ruby/2.7.0/gems/gollum-lib-5.0.2/lib/gollum-lib/git_access.rb:16:in `initialize'
        2: from /home/my/.gem/ruby/2.7.0/gems/gollum-lib-5.0.2/lib/gollum-lib/git_access.rb:16:in `new'
        1: from /home/my/.gem/ruby/2.7.0/gems/gollum-rugged_adapter-0.99.4/lib/rugged_adapter/git_layer_rugged.rb:562:in `initialize'
/home/my/.gem/ruby/2.7.0/gems/gollum-rugged_adapter-0.99.4/lib/rugged_adapter/git_layer_rugged.rb:562:in `new': failed to resolve path '--page-file-dir': No such file or directory (Rugged::OSError)
```

This one `gollum-migrate-tags /home/my/software/gollum/ --prefer-relative-links --hyphenate --write` shows me only the changes what needs to be changed.

**Comment by bartkamphorst** [comment] 2020-04-02 06:46
Not sure if this is a helpful addition here, or should be posted as a new issue, but I'm seeing this:
```bash
$ bundle exec bin/gollum-migrate-tags ../gollum-wiki --page-file-dir foo
[INFO] Page foo/Home.md
====
[INFO] Page foo/bar.md
====
```

So far so good, but:
```bash
NorrinRadd:gollum bart$ bundle exec bin/gollum-migrate-tags ../gollum-wiki --page-file-dir foo --write
[INFO] Page foo/Home.md
bundler: failed to load command: bin/gollum-migrate-tags (bin/gollum-migrate-tags)
Errno::ENOENT: No such file or directory @ rb_sysopen - ../gollum-wiki/foo/foo/Home.md
  bin/gollum-migrate-tags:265:in `initialize'
  bin/gollum-migrate-tags:265:in `new'
  bin/gollum-migrate-tags:265:in `block in <top (required)>'
  bin/gollum-migrate-tags:260:in `each'
  bin/gollum-migrate-tags:260:in `<top (required)>'
```

**Comment by dometto** [comment] 2020-04-02 08:13
@bartkamphorst's case seems different -- on what ruby are you?

but @DanSman: you need to explicitly specify the path to the repository as the first argument. So for instance:

`gollum-migrate-tags /path/to/my/repository --prefer-relative-links --hyphenate --write`

So **don't** put `--page-file-dir` as the first argument. `--page-file-dir` does not specify the path to the repository, but the path *within* the repository where the wiki is served from. If you want to specify a page-file-dir, the command would look, e.g., as follows:

`gollum-migrate-tags /path/to/my/repository --prefer-relative-links --hyphenate --write --page-file-dir docs`

**Comment by dometto** [comment] 2020-04-02 09:15
I fixed the annoying behavior of the migrate script in https://github.com/gollum/gollum/pull/1538, so when that is merged/released you don't have to worry about the argument order anymore.

I'll wait with the bugfix release to see if anything else comes up for a couple of days, if that's ok @DanSman.

**Comment by bartkamphorst** [comment] 2020-04-02 11:40
> on what ruby are you?

This was on ruby 2.6.3p62. Seems like `page-file-dir` `foo` is prepended to a path that already includes it `foo/Home.md`.

**Comment by dometto** [comment] 2020-04-02 12:09
>  Seems like page-file-dir foo is prepended to a path that already includes it foo/Home.md.

Weird, the script just uses `gollum-lib` to set the page file dir. But perhaps it's not being st correctly.

**Comment by DanSman** [comment] 2020-04-02 21:49
> --prefer-relative-links --hyphenate --write

Using your command changes nothing as well. Actually, it doesn't make any difference what I put behind `gollum-migrate-tags /home/my/software/gollum/`

See:
`gollum-migrate-tags /home/my/software/gollum/ --prefer-relative-links --hyphenate --write`
```
/home/my/.gem/ruby/2.7.0/gems/gollum-rugged_adapter-0.99.4/lib/rugged_adapter/git_layer_rugged.rb:562: warning: Using the last argument as keyword parameters is deprecated
[INFO] Page Home.md
[INFO] Found no candidates for broken link: [[Week Plan|wochenplan]]
[INFO] Home.md: Changing [[All pages|all-pages]] -> [[All pages|content/all-pages.md]]
====
[INFO] Page content/all-pages.md
```

> ... .gem/ruby/2.7.0/gems/gollum-rugged_adapter-0.99.4/lib/rugged_adapter/git_layer_rugged.rb:562: warning: Using the last argument as keyword parameters is deprecated

Is there another version of rugged?

**Comment by dometto** [comment] 2020-04-03 07:19
@DanSman you're confusing a deprecation warning with an actual error. If you look at the output of `gollum-migrate-tags /home/my/software/gollum/ --prefer-relative-links --hyphenate --write`, you'll see that the `Ruggged::OSError` is no longer being thrown *and everything works as expected*. Just `cd /home/my/software/gollum` and `git diff` to see the changes made by the script. Then commit them if everything is as you want it.

> What about this code in gollum-rugged_adapter?

We need to change that code so it will be compatible with future versions of ruby -- that is what the deprecation warning indicates. For now, the code is fully functional.

**Comment by dometto** [comment] 2020-04-03 13:57
@bartkamphorst can you open a new issue for the problem you encountered?

**Closed by dometto** 2020-04-03 13:57 UTC

**Comment by DanSman** [comment] 2020-04-04 03:28
I was such an idiot. I completely forgot to commit it. Thank you for the advice and sorry for your time :/

**Comment by dometto** [comment] 2020-04-04 09:30
No worries!
