### ISSUE TITLE
Wont host from submodules

### ISSUE THREAD

**Issue by mccullerlp** [gollum/gollum#1253] opened 2017-08-01 16:38 UTC
Git loads submodules with absorbgitdirs, where the wiki repo has no real .git directory. Instead there is a .git stub file indicating that it is in a parent's .git/submodules dir. I was trying to use gollum from a submodule like this and all page references would go to the create page and then fail with an exception.

I don't really need this, but an error message indicating the impending failure would prevent time wasted to debugging.

The issue being up now will help as well.

**Comment by dometto** [comment] 2017-08-07 15:42
Duplicate of #1082. This is an issue with the underlying git providers (currently `grit` by default, but also `rugged` and `rjgit`). If you think it is necessary, you can add a warning to this to gollum's [wiki](https://github.com/gollum/gollum/wiki), which is publically editable.

**Closed by dometto** 2017-08-07 15:42 UTC
