### ISSUE TITLE
Docker image does not execute command line arguments

### ISSUE THREAD

**Issue by ConorHK** [gollum/gollum#1869] opened 2022-11-06 22:02 UTC
**Please read the [CONTRIBUTION GUIDELINES](https://github.com/gollum/gollum/blob/master/CONTRIBUTING.md) before submitting!**

If your have problems using or installing the software which stem from bugs in the software or a lack of documentation, we are always happy to help out! However, **for ordinary usage questions, please consider asking elsewhere**, for instance on [StackOverflow](http://stackoverflow.com/questions/tagged/gollum-wiki).

**Describe the bug**
Running via docker as described in the documentation with any CLI arguments doesn't execute as expected. The `--bare` flag does not seem to be respected. `--ref main` is not respected.

**To Reproduce**
1. Execute `docker run --rm -p 4567:4567 -v /home/mustang/repositories/gollum:/wiki -v /home/mustang/containers/gollum/config.rb:/etc/gollum/config.rb gollumwiki/gollum:master --ref main --bare` substituting in the relevant directory paths.
2. See in output that the resulting git repository is neither bare nor using the `main` branch.

**Expected behavior**
A bare git branch created in the supplied directory with the supplied branch name as default.

**Paste**
```
[venus] ~ ──── ─ docker run --rm -p 4567:4567 -v /home/mustang/repositories/gollum:/wiki -v /home/mustang/containers/gollum/config.rb:/etc/gollum/config.rb gollumwiki/gollum:master --config=/etc/gollum/config.rb --ref main --bare
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint:   git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint:   git branch -m <name>
Initialized empty Git repository in /wiki/.git/
WARNING: Mathjax will soon be disabled by default. To explicitly enable it, use --mathjax
[2022-11-06 22:00:58] INFO  WEBrick 1.7.0
[2022-11-06 22:00:58] INFO  ruby 2.7.6 (2022-04-12) [x86_64-linux-musl]
== Sinatra (v3.0.1) has taken the stage on 4567 for production with backup from WEBrick
[2022-11-06 22:00:58] INFO  WEBrick::HTTPServer#start: pid=1 port=4567
```

**Comment by dometto** [comment] 2022-11-07 09:24
This looks like a duplicate of #1814, unless other command line options also aren't working? In the later case, please feel free to reopen!

**Closed by dometto** 2022-11-07 09:24 UTC
