### ISSUE TITLE
Pipe tables do not render on 5.1.2 when using redcarpet

### ISSUE THREAD

**Issue by thorlucas** [gollum/gollum#1675] opened 2021-02-20 22:15 UTC
**Describe the bug**
Ordinary markdown pipe tables do not render. Instead we just get: `| foo | bar | | --- | --- | | baz | quz |`

**To Reproduce**
1. Fresh install of gollum `sudo gem install gollum`
2. Fresh git directory
3. Create a Home.md with the following contents:
```
| foo | bar |
| --- | --- |
| baz | quz |
```
4. Add and commit file.
5. Start gollum with `gollum`

**Expected behavior**
That table should render as so:

| foo | bar |
| --- | --- |
| baz | quz |

**Screenshots**
<img width="1045" alt="Screen Shot 2021-02-20 at 2 13 07 PM" src="https://user-images.githubusercontent.com/25698466/108609866-c2bddf00-7385-11eb-8916-2013a89ef8ab.png">

**Environment Info**
```
Gollum 5.1.2
Running on: universal.x86_64-darwin20 with Ruby version 2.6.3
Using:
rugged 0.99.0
gollum-rugged_adapter 1.0
gollum-lib 5.0.6
Markdown rendering gem: redcarpet
Other renderering gems:
RedCloth 4.2.9
```

**Comment by thorlucas** [comment] 2021-02-20 22:25
Running `gem install kramdown` followed by `gem uninstall redcarpet` seems to have fixed this. However, there is still an issue: the wiki says that `kramdown` is used by default when in actuality `redcarpet` seems to be used by default instead.

**Comment by benjaminwil** [comment] 2021-02-21 03:21
Hello, thanks for the detailed report. I did some investigation based on it, and here's what I found.

I was not able to reproduce using the steps above.

Before cleanly installing Gollumn, I made sure that neither `redcarpet` nor `kramdown` were installed:

```
gem list | grep redcarpet
# no output

gem list | grep kramdown
# no output
```

After installing Gollumn, `kramdown` was installed but `redcarpet` was still not installed. This makes sense to me, as the `gollum.gemspec` file only specifies `kramdown` as a dependency, not `redcarpet`.

The Markdown (piped) table rendered on first load with no issues using `kramdown`.

Next, I manually installed `redcarpet`:

```
gem install redcarpet
```

After restarting Gollum, the table was no longer rendering properly. So I think I was able to verify your conclusion, though I got there a slightly different way:

- If `redcarpet` is installed at all, Gollum will default to using it instead of `kramdown`.
- Gollum's render settings for `redcarpet` are not set up to render Markdown tables.

I will see if there are `redcarpet` settings available that allow `redcarpet` to render Markdown tables in Gollum.

**Comment by thorlucas** [comment] 2021-02-22 03:57
Thanks @benjaminwil ! I think you're right, `redcarpet` may have been installed when I installed all gems required by the gollum repo. Although it would be good to get tables working with all renderers.

**Comment by dometto** [comment] 2021-02-22 11:28
Gollum loads `redcarpet` via the `github-markup` gem and its default rendering options for the former. We can't really provide custom rendering settings for all available rendering gems, so I'm not sure we should consider this a bug. If it's really important to you to use `redcarpet` rather than another markdown rendering gem (`kramdown`, `commonmarker` etc. all work with gollum), you could try enabling support for `redcarpet` tables in your `config.rb`. See here for the general method:

https://github.com/gollum/gollum/wiki/Customizing-rendering-settings

@thorlucas do you think you could give that a try? It would be nice to have  working snippet as an example on that wiki page!

**Comment by benjaminwil** [comment] 2021-02-22 18:14
As an aside, it seems to me that most people do not care which gem is used for rendering.

Rather than "fall back" to Kramdown, I wonder if we should "default" to Kramdown and force users to otherwise explicitly specify what rendering gem they would rather use.

That may be a breaking change, and only worth considering for a 6.0 release – I'm not entirely sure.

**Comment by dometto** [comment] 2021-02-23 11:46
> That may be a breaking change, and only worth considering for a 6.0 release – I'm not entirely sure.

Yeah that would be a breaking change as it would mean abandoning `github-markup` as our rendering-gem handler (`github-markup` just tries to load markdown gems in a certain order, so no 'explicit' enabling is possible). There may be grounds for that anyway, as github-markup has been more or less abandoned by github. It wouldn't be crazy to attempt to build our own solution for that, but also definitely not trivial.

**Comment by dometto** [comment] 2021-03-06 11:34
Closing this for now. We can review the desirability of using github-markup in the future!

**Closed by dometto** 2021-03-06 11:34 UTC
