### ISSUE TITLE
Official docker image for 6.0+ not working due to /wiki directory access error

### ISSUE THREAD

**Issue by Hooverdan96** [gollum/gollum#2084] opened 2024-12-17 22:14 UTC
**Describe the bug**
Attempting to run official docker image with tags >=6.0 as well as `latest` or `master` results in "fatal" error during startup.

**To Reproduce**
Steps to reproduce the behavior, tested with `latest` (currently 6.0.1), `master` and `6.0`
1. start docker container within empty directory (no `.git` file present) using:
```
docker run --rm -p 4568:4567 -v $(pwd):/wiki gollumwiki/gollum:6.0
```
2. See error during execution of docker command
```
Unable to find image 'gollumwiki/gollum:6.0' locally
6.0: Pulling from gollumwiki/gollum
Digest: sha256:dc7bd2a46c83a189fb4bc3c1ab1fbc1ba28254ed4f019935c26527ea574668c8
Status: Downloaded newer image for gollumwiki/gollum:6.0
fatal: Cannot access work tree '/wiki': Permission denied
[2024-12-17 22:13:04] INFO  WEBrick 1.8.1
[2024-12-17 22:13:04] INFO  ruby 3.1.6 (2024-05-29) [x86_64-linux-musl]
== Sinatra (v4.0.0) has taken the stage on 4567 for production with backup from WEBrick
[2024-12-17 22:13:04] INFO  WEBrick::HTTPServer#start: pid=1 port=4567
```

3. navigate to `host-ip address`:4568 and observe web page error:
<img width="787" alt="image" src="https://github.com/user-attachments/assets/b88e7cdb-1615-46ba-9c76-4b1e2f111da7" />

**Expected behavior**
When using e.g. version `5.3.3`  in the same above command, the gollum page comes up, no errors. The message log in that version indicates that the git initialization is successful:
```
Initialized empty Git repository in /wiki/.git/
```
while with 6.0+ it seems to run into the authorization problem.

**Environment Info**
see above
Always include the output of the `gollum --versions` command (NB: `versions` in plural).

**Comment by dometto** [comment] 2024-12-18 20:30
Thanks for the bug report. Unfortunately I can't reproduce this. Might the issue be related to your Docker setup locally? I'm thinking the volume mount of the directory might not be working correctly for some reason. What happens if you try the following:

1. Run gollum while giving the docker container a specific name: `docker run --name gollum-test --rm -p 4568:4567 -v $(pwd):/wiki gollumwiki/gollum:6.0`
2. While the container is running, from a different terminal, run `docker exec gollum-test touch /wiki/test`

I'm suspecting that step 2. will trigger a permissions error of some kind. Please let us know if that's correct.

**Comment by Hooverdan96** [comment] 2024-12-18 22:18
Ah, yes. First of all, @dometto thanks for your quick response. I guess, the change has been in the way authorization needs to be aligned. I finally found that the www-data user has the `1000:1000` UID:GID. So, before executing the docker command, I changed the wiki directory ownership to `UID=1000`and `GID=1000`.
Running the `touch` from inside the container did not create a permission error.

Furthermore, I was also able to bring up the gollum web page.

May be this piece of information can be eventually added to the Docker/Docker-compose wiki page, since that looks like a change from 5.x to 6.x?

Since you're probably rather busy, If it helps, I can submit a PR with a proposal?

Thanks again!

**Comment by dometto** [comment] 2024-12-19 08:38
It would be great to have some more context on this in the wiki. I'm thinking it might also be useful if the Docker entrypoint script did some sort of simple permissions check to see if the `/wiki` directory in the container is writable, and output a useful message if it isn't.

By the way, instead of changing permissions on your directory, does adding explicit `rw` to the volume mount also solve the issue? So `-v $(pwd):/wiki,rw`? (Not sure about this)

**Comment by Hooverdan96** [comment] 2024-12-19 16:02
Ok, I did a quick check.
for testing: set designated `wiki` directory's UID:GID to 1001:1001
```
docker run --name gollum-test --rm -p 4568:4567 -v $(pwd):/wiki,rw gollumwiki/gollum:6.0
```
results in `/wiki/.git: Permission denied`
To be sure, also executed:
`docker exec gollum-test touch /wiki/test`
same permission error:
`touch: /wiki/test: Permission denied`

Alternativeyl, using the `-u` option, running with the above example:
```
docker run --name gollum-test --rm -u=1001 -p 4568:4567 -v $(pwd):/wiki gollumwiki/gollum:6.0
```
So, I think there are two options for versions 6.0 onwards to ensure the mapped directory can be written to by the gollum docker:
- set the directory ownership to UID/GID 1000/1000 to match the docker user information
- use the `-u` option to override the docker default user and match it with the UID/GID the host directory has

I will attempt to submit an update to the wiki in the next few days.

As for a PR for the simple permission check, I'll see whether I feel adventurous enough to attempt that :smile:

**Comment by Hooverdan96** [comment] 2024-12-19 16:50
Added 6.0+ context to the wiki page:
https://github.com/gollum/gollum/wiki/Gollum-via-Docker

See if you think that works.

**Comment by dometto** [comment] 2024-12-21 10:54
Great! I've moved the note to the "Running" section  in the wiki page and added the warning message from the just merged changes to the entrypoint script, so that users who search for the warning will hopefully find the relevant fix in the wiki. :)

**Closed by dometto** 2024-12-21 10:54 UTC
