### ISSUE TITLE
NoMethodError at /gollum/search

### ISSUE THREAD

**Issue by sbeaumont** [gollum/gollum#1853] opened 2022-08-25 10:14 UTC
There seems to be an issue when gollum looks up its i18n information: I've poked around but am not a Ruby expert. 

The error happens here: https://github.com/gollum/gollum/blob/ce85301e7089df802a3e6c5892afb99104af4c65/lib/gollum/views/helpers/locale_helpers.rb#L40

and could be because the "yaml" argument is something it's not expecting. Why that happens I haven't figured out.

You can see it here: http://agilelibrary.io/gollum/search?q=test

I won't copy in the resulting page because it pastes in horribly.

**Comment by dometto** [comment] 2022-08-25 10:37
This seems to happen on other routes on your wiki as well, e.g.: http://agilelibrary.io/gollum/latest_changes

However, it doesn't occur on ordinary pages.

Could you supply us with the output of `gollum --versions` (mind the `s`) and perhaps give us some more info about with what configuration you're running gollum?

**Comment by sbeaumont** [comment] 2022-08-25 14:11
The online instance runs on GCP, need to ask a colleague who helped me out there if he can do it for me. What I can say is that I then tried running gollum locally, and it does not have that issue. So there's something up with the GCP install...

**Comment by sbeaumont** [comment] 2022-08-25 14:12
This is my local output of `gollum --versions`

Gollum 5.3.0
Running on: aarch64-linux-musl with Ruby version 2.7.6
Using:
rugged 1.1.1
gollum-rugged_adapter 1.1.2
gollum-lib 5.1.3
Markdown rendering gem: kramdown
Other renderering gems:
RedCloth 4.3.2
org-ruby 0.9.12
creole 0.5.0
asciidoctor 2.0.17
wikicloth 0.8.3

**Comment by benjaminwil** [comment] 2022-08-25 16:48
I haven't been able to reproduce the issues in tests yet.

- I made a new branch off of the `v5.3.0` tag.
- I added all of the recent Capybara test runner-related code we've merged.
- I added acceptance specs for the two offending views.

I wonder if it's possible that Gollum is trying to render the wrong locale? Right now Gollum only includes translations for `en` and it's possible we're not "falling back" to the `en` locale gracefully.

**Comment by sbeaumont** [comment] 2022-08-26 08:38
We've been able to fix the problem at our end by setting all references to the gollumwiki/gollum:v5.3.0 docker image instead of master (which we should have done in the first place).

The containers would regularly pull the master version, and one of those versions will have had the issue just as the version was pulled. This means that the problem occurs on master (and maybe an older commit?), not on v5.3.0.

**Comment by sbeaumont** [comment] 2022-08-26 08:41
As asked for this was the output of gollum --versions on the container after the version fix:

```
bash-5.1# gollum --versions
Gollum 5.3.0
Running on: x86_64-linux-musl with Ruby version 2.7.6
Using:
rugged 1.1.1
gollum-rugged_adapter 1.1.2
gollum-lib 5.2
Markdown rendering gem: kramdown
Other renderering gems:
RedCloth 4.3.2
org-ruby 0.9.12
creole 0.5.0
asciidoctor 2.0.17
wikicloth 0.8.3
```

**Comment by dometto** [comment] 2022-08-30 07:54
> The containers would regularly pull the master version, and one of those versions will have had the issue just as the version was pulled. This means that the problem occurs on master (and maybe an older commit?), not on v5.3.0.

This makes sense. Since I also can't reproduce, I suspect the issue was on a previous commit on `master`. Sorry about the confusion about the Docker image. If you have any ideas on how to make clearer what image to use please let us know!

On a sidenote: perhaps it would be helpful if `--versions` also somehow outputted the latest commit?

**Comment by weaversam8** [comment] 2022-09-02 18:43
I'm also encountering this issue, but not in the Docker image, just while building and running locally.

Reverting to `ee512bd` fixed the issue, which leads me to think that something in #1797 broke this behavior. Would suggest to reopen.

**Comment by dometto** [comment] 2022-09-03 09:45
Thanks for letting us know @weaversam8! Could you also supply us with the output of `gollum --versions`?

**Comment by benjaminwil** [comment] 2022-09-04 21:39
I made a PR, #1855, that tests the the reported views for errors. But it hasn't caught any errors–even when I dropped the commit that fixes one of the translations strings that wasn't rendering properly.

And I haven't been able to manually reproduce this issue, either.

I'm looking forward to getting to the bottom of this.

**Comment by dometto** [comment] 2022-09-07 09:47
@weaversam8 would be great to get some more information on your environment if you could give us the output of `gollum --versions`

**Comment by weaversam8** [comment] 2022-09-14 15:50
Sorry for the delay, this went to my incorrect email.

I don't encounter this error when `gollum` is built from `ee512bdad5e0c783f5af75b1e90b4935db0c62f8`, but I do encounter this error when `gollum` is built from `738d6f6ec47f1300d8c792f84db5b2ceea065fcd`.

`gollum --versions` is identical between both commits:
```
Gollum 5.3.0
Running on: x86_64-linux-gnu with Ruby version 2.7.0
Using:
rugged 1.1.1
gollum-rugged_adapter 1.1.2
gollum-lib 5.2
Markdown rendering gem: kramdown
Other renderering gems:
wikicloth 0.8.3
```

Not sure if this is fixed in `master` or not as `gollum` built from `master` is now silently crashing with an error code of 1.

If it makes any difference, I'm running this from `bin/gollum` in the repo, not from a system installed version.

**Comment by dometto** [comment] 2022-09-22 09:40
The issue was simply that we were requiring `uglifier`, which relies on the presence of a suitable `ExecJS` runtime (e.g. `node` or `therubyrhino`). This is available in many environments but of course not in all. Significantly, it wasn't available on the Docker image, so that's why the newer Docker builds were failing. This should be fixed in #1860 (which only requires `uglifier` when we actually precompile), but, @weaversam8, let me know if you still encounter any issues and we'll reopen this.

**Closed by dometto** 2022-09-22 09:40 UTC

**Comment by dometto** [comment] 2022-10-11 07:28
Actually this seems to occur on other routes on your wiki as well, e.g.
http://agilelibrary.io/gollum/latest_changes

Could you give us the output of `gollum --versions` and perhaps some more
info on how you're running gollum?

**Comment by sbeaumont** [comment] 2022-10-11 09:33
We haven't changed anything (still on 5.3.0) since 26th of august, so my comment there has the current output

We're running on GCP, one app container, and one that does git pull on our internal repo to pull in changes we've made to the data.
