### ISSUE TITLE
Searching multiple keywords

### ISSUE THREAD

**Issue by shanzhong** [gollum/gollum#615] opened 2012-12-27 14:30 UTC
It seems the current version of Gollum (2.4.10) does not support searching multiple keywords simultaneously across the wiki site. For example, if a page contains the following content:

> Problems with the software includes...

Searching `problems software` will not return this page; although using a regular expression like `problems.*software` works - but that will require the order between "problems" and "software" to be the same as it appears in the page. 

It would be great if Gollum could support searching multiple keywords as this is an important feature for a wiki system.

**Comment by rudazhan** [comment] 2016-06-17 00:01
Actually, the `git.grep()` method called by gollum-lib's `search()` accepts RegExp, which I guess defaults to POSIX BRE. So the implementation by @shanzhong can be achieved by searching for `(query_word1| query_word2)`.

**Comment by dometto** [comment] 2018-10-01 16:45
Ideally multiple keyword search would be the default, and so wouldn't require using `query_word1|query_word2`. It should be simple to change the user's query into a disjunctive regex though. PRs very welcome.

**Comment by m3nd3s** [comment] 2018-10-03 14:09
Hi @shanzhong and @dometto, can I take this issue to solve it? 

Let me see if I understood, the problem is on search mechanism, the users should be able to search using multiple terms, but nowadays it only works using regex. Is that right?

If it possible, could you assign this issue to me?

**Comment by dometto** [comment] 2018-10-03 14:21
You're most welcome, @m3nd3s ! And yes, that's exactly the issue. The place to start would probably be to add some tests which specify the desired behavior. Feel free to open a PR and we can discuss further there

**Comment by dometto** [comment] 2018-10-03 14:29
Looks like I can only assign repo owners to an issue, but nobody else is working on it.

**Comment by m3nd3s** [comment] 2018-10-03 14:30
No problem @dometto, asap I give you news ;-)

**Comment by dometto** [comment] 2018-10-03 15:17
@m3nd3s I should have said immediately, but please use the `5.x` branch as your starting point and the target of your PR!

**Comment by m3nd3s** [comment] 2018-10-03 16:09
@dometto OK, thanks

**Comment by m3nd3s** [comment] 2018-10-10 17:49
Hi @dometto , I notice that the [search](https://github.com/gollum/gollum-lib/blob/e811f79cb569f1bf0711947d49105db60421e2c1/lib/gollum-lib/wiki.rb#L642) is implemented on `gollum-lib`, right?

So, the pull request should be open to there, right?

**Comment by bartkamphorst** [comment] 2018-10-10 20:11
@m3nd3s Correct!

**Comment by dometto** [comment] 2019-09-18 16:23
Work on this underway in https://github.com/gollum/gollum-lib/pull/343 and https://github.com/gollum/rugged_adapter/pull/37. Feedback welcome

**Comment by dometto** [comment] 2019-09-30 13:31
This, and contextful search results, have been implemented in 5.x through #1427

**Closed by dometto** 2019-09-30 13:31 UTC
Labels: feature, help wanted
