### ISSUE TITLE
Compare Revisions redirect to error message when Edit option is disabled

### ISSUE THREAD

**Issue by DanSman** [gollum/gollum#1546] opened 2020-04-06 11:48 UTC
**Describe the bug**

#1545

> I have also another question about the editing mode. I disabled it and I can't compare versions without having the edit mode set on true. Is it possible to compare different versions without having the edit mode activated? Should I do another issue about it? I don't wanna bother you so much :)

**To Reproduce**
1. Add `  :allow_editing => false,` to your config.rb
2. Click on 'Page History'
3. Compare Revisions

**Expected behavior**
To see the different versions in comparison.

**Version**
Gollum 5.0.1
Running on: x86_64-linux with Ruby version 2.7.1
Using:
rugged 0.99.0
gollum-rugged_adapter 0.99.4
gollum-lib 5.0.3
Markdown rendering gem: github/markdown
Other renderering gems:
none

**Comment by dometto** [comment] 2020-04-06 12:52
The problem is [here](https://github.com/gollum/gollum/blob/master/lib/gollum/app.rb#L108), coupled with the fact that the History view is `POST`ing the revision data to the compare view. Not sure what the best way to fix is. Would be a bit ugly to hardcode an exception for the `compare` view on L108. Also I don't see a super easy way to make the compare view use GET instead (although this is certainly possible).

**Comment by dometto** [comment] 2020-06-15 10:14
Fixed in #1578 thanks to @tpoliaw! Many thanks

**Closed by dometto** 2020-06-15 10:14 UTC
Labels: bug, help wanted
