### ISSUE TITLE
Empty emails don't work

### ISSUE THREAD

**Issue by simonzack** [gollum/gollum#954] opened 2015-01-26 12:42 UTC
I'm not sure if this is a gollum or gollum-lib bug, but empty emails show up as `<<>` in the git log instead of `<>`. Strangely though, setting `session['gollum.author'][:email]` to `>` fixes the issue.

**Comment by dometto** [comment] 2015-01-26 13:10
Can't reproduce this with this `config.ru`:

```ruby
require 'rubygems'
require 'gollum/app'

use Rack::Session::Cookie

class SetGollumAuthor

  def initialize(app)
    @app = app
  end

  def call(env)
    request = Rack::Request.new(env)
    session = env['rack.session']
    session['gollum.author'] = {
        :name => "gollum",
        :email => ""
      }
    @app.call(env)
  end
end

use SetGollumAuthor

Precious::App.set(:gollum_path, '/tmp/git-test/')
Precious::App.set(:default_markup, :markdown)
Precious::App.set(:wiki_options, {:universal_toc => true, :allow_uploads => true, :mathjax => true, :show_all => true, :live_preview => false})
run Precious::App
```
Also can't reproduce this when using `gollum-lib` from irb, or when running `bin/gollum`. Sure this not related to your setup somehow?

**Comment by simonzack** [comment] 2015-01-26 13:29
Strange this re-produces the error on my machine.

**Comment by simonzack** [comment] 2015-01-26 14:09
Think this is a grit issue, it's `actor.rb` file doesn't parse or stringify `<>` emails.

**Comment by dometto** [comment] 2015-01-26 14:30
Still doesn't explain the difference between our machines though. What version of gitlab-git are you using? 2.7.3 here.

**Comment by simonzack** [comment] 2015-01-26 14:37
Same here. Btw, if my first post wasn't clear enough, by empty email I mean `<>` emails, not the emails which are later filled in. Can you reproduce it after changing `:email => ""` to `:email => "<>"` ?

**Comment by dometto** [comment] 2015-01-26 14:42
Yes that reproduces it. But if you do `:email => ""`, that will show up as `<>` in the git log. :) So that's what you want I think.

**Comment by simonzack** [comment] 2015-01-26 14:49
> So that's what you want I think.
Yeah that's what I want, but it has the same problem. I think what happens there is it expands to my default email (in `~/.gitconfig`), but when that's empty (`<>`) the same problem occurs

**Comment by dometto** [comment] 2015-01-26 14:58
Ah yes, it does override it. I can do `git config user.email ""` though, and then I'll get the result you want. But that shouldn't be necessary.

**Comment by dometto** [comment] 2015-01-26 15:02
The override is being done here:
https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/committer.rb#L56-L57
`@wiki.default_committer_email` will use the email from `git config` if it's there.

It could probably just be changed to ` @options[:email] = @wiki.default_committer_email if @options[:name].nil?`
If you have a second to try that out and do a PR, that would be much appreciated. :)

**Comment by dometto** [comment] 2015-01-27 10:38
Fixed by https://github.com/gollum/gollum-lib/pull/137

**Closed by dometto** 2015-01-27 10:38 UTC
