### ISSUE TITLE
Editing the same page at the same time causes overwrite, not merge

### ISSUE THREAD

**Issue by hozumi** [gollum/gollum#1095] opened 2015-12-02 11:36 UTC
I found editing the same page at the same time causes overwrite, so the contents of earlier update was lost.
This problem can often happen if the page or team is large.
I hope gollum try to merge the commits if possible or at least gollum should warn the user who saved later.

**Comment by dometto** [comment] 2015-12-03 20:39
Duplicate of #279. PRs for this are very welcome.

**Closed by dometto** 2015-12-03 20:39 UTC

**Comment by hozumi** [comment] 2015-12-04 10:00
Thanks for navigating.
