### ISSUE TITLE
wiki not supported git submodule

### ISSUE THREAD

**Issue by shiningwang** [gollum/gollum#1082] opened 2015-10-22 19:33 UTC
i have a git repo. then add a wiki submodule to this git repo.
``` git submodule add https://github.com/shiningwang/wiki.git wiki ```
then enter the wiki folder and run ```gollum```. the web editor do not work for me. Did not display the content for my Home.markdown file, but "Create New Page".

**Comment by bartkamphorst** [comment] 2015-10-23 18:30
Please elaborate by providing either a bug description or a feature request.

**Comment by bartkamphorst** [comment] 2015-10-27 09:42
Closing until a better description is provided.

**Comment by shiningwang** [comment] 2015-10-28 14:47
description updated

**Comment by SkyCrawl** [comment] 2015-10-29 10:34
Clarification after a little manual hunting:
```
$ gollum --irb
$ access = Gollum::GitAccess.new(wiki.path, nil, false)
$ access.repo.commit('master')
=> nil (as opposed to a regular git repository where a commit is returned)
```

Relevant code:
* [Git Access](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/git_access.rb#L150)

But the actual error is down the rabbit (git) hole. I did not venture there.

**Comment by shiningwang** [comment] 2015-10-30 02:13
thanks

**Comment by dometto** [comment] 2015-11-08 23:14
We won't be adding this feature to the grit adapter unless anyone implements it themselves. However, the most recent release of rugged supports submodules, so we could look into that. PRs welcome.

**Comment by dometto** [comment] 2015-12-03 20:43
Just noticed this is a duplicate of #438.

**Closed by dometto** 2015-12-03 20:43 UTC
Labels: improvement
