### ISSUE TITLE
NoMethodError at /home undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by Xunnamius** [gollum/gollum#1057] opened 2015-08-18 03:58 UTC
Similar to previous problems detailed in the issues, but different/recent enough to warrant its own thread, I think. Good thing normal push still works, at least!

Trace:

```
xunnamius@babylon /media/sf_github/wiki/z.xunn.io.wiki  master u=
$  gollum
/var/lib/gems/2.1.0/gems/rouge-1.9.1/lib/rouge/lexers/shell.rb:20: warning: already initialized constant Rouge::Lexers::Shell::KEYWORDS
/var/lib/gems/2.1.0/gems/rouge-1.9.1/lib/rouge/lexers/shell.rb:20: warning: previous definition of KEYWORDS was here
/var/lib/gems/2.1.0/gems/rouge-1.9.1/lib/rouge/lexers/shell.rb:25: warning: already initialized constant Rouge::Lexers::Shell::BUILTINS
/var/lib/gems/2.1.0/gems/rouge-1.9.1/lib/rouge/lexers/shell.rb:25: warning: previous definition of BUILTINS was here
[2015-08-17 22:55:03] INFO  WEBrick 1.3.1
[2015-08-17 22:55:03] INFO  ruby 2.1.5 (2014-11-13) [x86_64-linux-gnu]
== Sinatra (v1.4.6) has taken the stage on 4567 for development with backup from WEBrick
[2015-08-17 22:55:03] INFO  WEBrick::HTTPServer#start: pid=6056 port=4567
2015-08-17 22:55:13 - NoMethodError - undefined method `split' for nil:NilClass:
	/var/lib/gems/2.1.0/gems/gitlab-grit-2.7.3/lib/grit/commit.rb:152:in `list_from_string'
	/var/lib/gems/2.1.0/gems/gitlab-grit-2.7.3/lib/grit/repo.rb:560:in `log'
	/var/lib/gems/2.1.0/gems/gollum-grit_adapter-1.0.0/lib/grit_adapter/git_layer_grit.rb:203:in `versions_for_path'
	/var/lib/gems/2.1.0/gems/gollum-lib-4.1.0/lib/gollum-lib/page.rb:281:in `versions'
	/var/lib/gems/2.1.0/gems/gollum-4.0.0/lib/gollum/app.rb:497:in `show_page_or_file'
	/var/lib/gems/2.1.0/gems/gollum-4.0.0/lib/gollum/app.rb:480:in `block in <class:App>'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
	/usr/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
	/usr/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
	/usr/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
gateway - - [17/Aug/2015:22:55:13 CDT] "GET /home HTTP/1.1" 500 138504
- -> /home
gateway - - [17/Aug/2015:22:55:13 CDT] "GET /__sinatra__/500.png HTTP/1.1" 302 0
http://127.0.0.1:4567/home -> /__sinatra__/500.png
gateway - - [17/Aug/2015:22:55:13 CDT] "GET /create/__sinatra__/500.png HTTP/1.1" 200 6643
http://127.0.0.1:4567/home -> /create/__sinatra__/500.png
gateway - - [17/Aug/2015:22:55:13 CDT] "GET /favicon.ico HTTP/1.1" 302 0
http://127.0.0.1:4567/home -> /favicon.ico
gateway - - [17/Aug/2015:22:55:14 CDT] "GET /create/favicon.ico HTTP/1.1" 200 6633
http://127.0.0.1:4567/home -> /create/favicon.ico
```

Repo is not bare, only has one commit (home.md) from GitLab. On Debian 8 Linux, running ruby 2.1.5p273 (2014-11-13).

**Comment by SkyCrawl** [comment] 2015-08-18 10:24
@dometto 
Looks to me we should redirect this issue to `gitlab_grit`? Specifically, something about @Xunnamius 's commit doesn't seem to work with [their notion of a commit](https://github.com/gitlabhq/grit/blob/v2.7.3/lib/grit/commit.rb#L145), since the [next shift](https://github.com/gitlabhq/grit/blob/v2.7.3/lib/grit/commit.rb#L152) clearly produces nil.

@Xunnamius 
As a quick remedy, you could try [switching to another git adapter](https://github.com/gollum/gollum/wiki/Git-adapters).

**Comment by dometto** [comment] 2015-08-18 15:30
@Xunnamius, you could try to confirm that this is an issue with grit from `irb`, for example:
```
require 'grit'
Grit::Repo.new('myrepo').log
```
If trying to access the repo in this way also fails, it's likely to be a `gitlab-grit` error.

**Comment by damianesteban** [comment] 2015-08-22 03:13
I'm having the same issue.  I've installed and used Gollum many times with no problems at all, however I just recently did a clean install of OS X and not it is giving me the same error.

Are there any specific logs that I can give you that would be of assistance?

**Comment by bartkamphorst** [comment] 2015-08-22 14:28
@damianesteban First off, great avatar. :smile: Secondly, could you try @dometto's suggestion and let us know if this is indeed an issue related to grit?

**Comment by damianesteban** [comment] 2015-08-23 03:23
Thank you.  Let me give it a try right now and I'll get back to you shortly.

**Comment by dometto** [comment] 2015-08-23 09:55
Can't reproduce this with a random new repo on OS X. Is it possible this has to do [with the specific commit messages](https://github.com/gitlabhq/grit/blob/v2.7.3/lib/grit/commit.rb#L136-L137)? @Xunnamius, do you get this error when using a different commit message, too?

**Comment by damianesteban** [comment] 2015-08-25 01:11
I'm going to try and completely re-install Ruby now, I'll check back in shortly.

**Comment by Xunnamius** [comment] 2015-08-31 23:12
Sorry @dometto, I've been busier recently than I expected. ~~I don't quite remember what I was doing when I encountered—~~ah, right! After I wake up in a few, I'll plug in your suggestions and reproduce the error. Just wanted to let you know that I didn't vanish forever :)

**Comment by PaulMakepeace** [comment] 2015-09-11 02:43
I'm seeing a similar problem serving `/custom.css`,

```
2015-09-11 02:10:39 - NoMethodError - undefined method `commit' for nil:NilClass:
	/app/vendor/bundle/ruby/2.2.0/gems/gollum-grit_adapter-1.0.0/lib/grit_adapter/git_layer_grit.rb:277:in `commit'
	/app/vendor/bundle/ruby/2.2.0/gems/gollum-lib-4.1.0/lib/gollum-lib/file.rb:114:in `get_disk_reference'
```

Trying to use `rugged` causes a massive and fatal downgrade,

```
$ bundle update
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies.................
Using posix-spawn 0.3.11
Installing albino 1.3.3
Using asciidoctor 1.5.2
Using creole 0.5.0
Using diff-lcs 1.2.5
Using github-markdown 0.6.9
Installing github-markup 0.7.5 (was 1.3.3)
Installing mime-types 2.6.1 (was 1.25.1)
Installing grit 2.0.0
Using mustache 0.99.8
Installing nokogiri 1.4.7 (was 1.6.6.2) with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
```

The last commit in the series was a repeatedly `--amend`'ed commit where I was adding files, FWIW.

**Comment by Xunnamius** [comment] 2015-09-11 11:08
> @Xunnamius, you could try to confirm that this is an issue with grit from irb, for example:
> 
> require 'grit'
> Grit::Repo.new('myrepo').log
> If trying to access the repo in this way also fails, it's likely to be a gitlab-grit error.

```
xunnamius@babylon ~/repos/wiki/z.xunn.io.wiki  master u=
$  irb
irb(main):001:0> require 'grit'
=> true
irb(main):002:0> Grit::Repo.new('.')
=> #<Grit::Repo "/media/sf_github/wiki/z.xunn.io.wiki/.git">
irb(main):003:0> Grit::Repo.new('.').log
NoMethodError: undefined method `split' for nil:NilClass
    from /var/lib/gems/2.1.0/gems/gitlab-grit-2.7.3/lib/grit/commit.rb:152:in `list_from_string'
    from /var/lib/gems/2.1.0/gems/gitlab-grit-2.7.3/lib/grit/repo.rb:560:in `log'
    from (irb):3
    from /usr/bin/irb:11:in `<main>'
```

@dometto So this is all gitlab's fault, then? If so, I'll go nag them instead :)

I literally pulled the wiki repo from my GitLab instance and tried to load it up with gollum. I can try on a fresh repository with a clean wiki and see what happens if that'll help. I haven't committed any changes clientside I don't believe.

Our commit messages look like the following:

```
...
* cb71bcc - [2 weeks ago]  jameshermes created page: mechanics - James Hermes
|  
* 086aac0 - [2 weeks ago]  we do want njs to use /api :P - Xunnamius (gitlab)
|  
* f98ad9d - [2 weeks ago]  edited api title - Xunnamius (gitlab)
|  
* 68edaae - [2 weeks ago]  edited generalschema title - Xunnamius (gitlab)
...
```

**Comment by dometto** [comment] 2015-09-11 12:17
On 11-09-15 13:08, Tre Giles wrote:
||
>
> @dometto <https://github.com/dometto> So this is all gitlab's fault, 
> then? If so, I'll go nag them instead :)
>

Yes, looks like it. You could try importing the data in a new repository 
(with just one commit) to see if the problem is indeed with the commit 
messages. If you could open an issue with gitlab-grit, that would be great.

 From our end, we'll work on fixing the problem with the rugged adapter 
and mime-types, since we want to encourage people to move to rugged 
anyway. I'll ping you guys on this thread when that's done, and then 
close this issue.

@PaulMakepeace: I think your issue is not related to this. Would you 
mind opening a new issue here or at https://github.com/gollum/grit_adapter?

**Comment by PaulMakepeace** [comment] 2015-09-11 23:27
@dometto sure thing: https://github.com/gollum/grit_adapter/issues/11

**Comment by dometto** [comment] 2015-09-23 19:38
The mime-types issue has been fixed in the `gollum-rugged_adapter` release `v0.4.1`. Until gitlab solves the problem with `gitlab-grit`, I recommend switching to rugged.

**Closed by dometto** 2015-09-23 19:38 UTC

**Comment by Xunnamius** [comment] 2015-09-25 16:45
Just to round this out: I can confirm that everything works on my system with gollum-rugged_adapter v0.4.1. Nice!

**Comment by bartkamphorst** [comment] 2015-09-25 22:40
Thanks for the feedback @Xunnamius !
