### ISSUE TITLE
install from source - cannot load such file -- rdoc/markup/to_html

### ISSUE THREAD

**Issue by deadc0de6** [gollum/gollum#1342] opened 2018-10-28 17:16 UTC
I'm not much into ruby but I tried installing gollum from source and ended up with following error:
```bash
$ bundle exec bin/gollum
bundler: failed to load command: bin/gollum (bin/gollum)
LoadError: cannot load such file -- rdoc/markup/to_html
  /home/user/.gem/ruby/2.5.0/gems/github-markup-1.7.0/lib/github/markup/rdoc.rb:3:in `require'
  /home/user/.gem/ruby/2.5.0/gems/github-markup-1.7.0/lib/github/markup/rdoc.rb:3:in `<top (required)>'
  /home/user/.gem/ruby/2.5.0/gems/github-markup-1.7.0/lib/github/markups.rb:2:in `require'
  /home/user/.gem/ruby/2.5.0/gems/github-markup-1.7.0/lib/github/markups.rb:2:in `<module:Markup>'
  /home/user/.gem/ruby/2.5.0/gems/github-markup-1.7.0/lib/github/markup.rb:103:in `instance_eval'
  /home/user/.gem/ruby/2.5.0/gems/github-markup-1.7.0/lib/github/markup.rb:103:in `<module:Markup>'
  /home/user/.gem/ruby/2.5.0/gems/github-markup-1.7.0/lib/github/markup.rb:24:in `<module:GitHub>'
  /home/user/.gem/ruby/2.5.0/gems/github-markup-1.7.0/lib/github/markup.rb:10:in `<top (required)>'
  /tmp/gollum/lib/gollum.rb:8:in `require'
  /tmp/gollum/lib/gollum.rb:8:in `<top (required)>'
  bin/gollum:7:in `require'
  bin/gollum:7:in `<top (required)>'
```

Here's what I did
```bash
$ ruby --version             
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
$ rdoc --version
6.0.4
$ export PATH="`ruby -e 'puts Gem.user_dir'`/bin:$PATH"
$ export GEM_HOME=$(ruby -e 'print Gem.user_dir')
$ git clone https://github.com/gollum/gollum.git
$ cd gollum
$ bundle install
...
Bundle complete! 9 Gemfile dependencies, 53 gems now installed.
...
$ bundle exec bin/gollum
```

I'm on arch linux and installed the following packages: `ruby` and `ruby-rdoc`.

What am I missing ?

**Comment by dometto** [comment] 2018-10-28 17:39
Try bundle exec gollum

**Comment by deadc0de6** [comment] 2018-10-29 09:15
thanks :+1:

**Comment by deadc0de6** [comment] 2018-11-03 06:57
Today I tried to re-install gollum from source as shown above and both commands `bundle exec gollum` and `bundle exec bin/gollum` failed. It does so on the *master* and on the *5.x* branch. Anything I'm doing wrong ?

```bash
$ bundle exec bin/gollum 
bundler: failed to load command: bin/gollum (bin/gollum)
LoadError: cannot load such file -- rdoc/markup/to_html
  /home/user/.gem/ruby/2.5.0/gems/github-markup-1.7.0/lib/github/markup/rdoc.rb:3:in `require'
  /home/user/.gem/ruby/2.5.0/gems/github-markup-1.7.0/lib/github/markup/rdoc.rb:3:in `<top (required)>'
  /home/user/.gem/ruby/2.5.0/gems/github-markup-1.7.0/lib/github/markups.rb:2:in `require'
  /home/user/.gem/ruby/2.5.0/gems/github-markup-1.7.0/lib/github/markups.rb:2:in `<module:Markup>'
  /home/user/.gem/ruby/2.5.0/gems/github-markup-1.7.0/lib/github/markup.rb:103:in `instance_eval'
  /home/user/.gem/ruby/2.5.0/gems/github-markup-1.7.0/lib/github/markup.rb:103:in `<module:Markup>'
  /home/user/.gem/ruby/2.5.0/gems/github-markup-1.7.0/lib/github/markup.rb:24:in `<module:GitHub>'
  /home/user/.gem/ruby/2.5.0/gems/github-markup-1.7.0/lib/github/markup.rb:10:in `<top (required)>'
  /home/user/tools/gollum/lib/gollum.rb:8:in `require'
  /home/user/tools/gollum/lib/gollum.rb:8:in `<top (required)>'                                                                     
  bin/gollum:7:in `require'
  bin/gollum:7:in `<top (required)>'
```

```bash
bundle exec gollum
bundler: failed to load command: gollum (/home/user/.gem/ruby/2.5.0/bin/gollum)
LoadError: cannot load such file -- rdoc/markup/to_html
  /home/user/.gem/ruby/2.5.0/gems/github-markup-1.7.0/lib/github/markup/rdoc.rb:3:in `require'
  /home/user/.gem/ruby/2.5.0/gems/github-markup-1.7.0/lib/github/markup/rdoc.rb:3:in `<top (required)>'
  /home/user/.gem/ruby/2.5.0/gems/github-markup-1.7.0/lib/github/markups.rb:2:in `require'
  /home/user/.gem/ruby/2.5.0/gems/github-markup-1.7.0/lib/github/markups.rb:2:in `<module:Markup>'
  /home/user/.gem/ruby/2.5.0/gems/github-markup-1.7.0/lib/github/markup.rb:103:in `instance_eval'
  /home/user/.gem/ruby/2.5.0/gems/github-markup-1.7.0/lib/github/markup.rb:103:in `<module:Markup>'
  /home/user/.gem/ruby/2.5.0/gems/github-markup-1.7.0/lib/github/markup.rb:24:in `<module:GitHub>'
  /home/user/.gem/ruby/2.5.0/gems/github-markup-1.7.0/lib/github/markup.rb:10:in `<top (required)>'
  /home/user/tools/gollum/lib/gollum.rb:8:in `require'
  /home/user/tools/gollum/lib/gollum.rb:8:in `<top (required)>'
  /home/user/tools/gollum/bin/gollum:7:in `require'
  /home/user/tools/gollum/bin/gollum:7:in `<top (required)>'
  /home/user/.gem/ruby/2.5.0/bin/gollum:23:in `load'
  /home/user/.gem/ruby/2.5.0/bin/gollum:23:in `<top (required)>'  
```

Here are some info:
```bash
$ ruby --version                     
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
$ rdoc --version
6.0.4
```

**Comment by dummys** [comment] 2018-11-06 16:02
Just to add my 2cents to this issue:
Inside the file: `.gem/ruby/2.5.0/gems/github-markup-1.7.0/lib/github/markup/rdoc.rb`
If I remove the `require "rdoc/markup/to_html"` then gollum start correctly.
Is it an issue with rDoc or with gollum-lib ?

**Comment by dometto** [comment] 2018-11-06 16:43
Looks like a bug in the github-markup gem in ruby 2.5.

**Comment by dometto** [comment] 2018-11-06 17:31
Could someone just try requiring github-markup (latest version) and see if that breaks? If so, please file a bug at github/markup and use gollum with ruby 2.4.x for the time being.

**Comment by dummys** [comment] 2018-11-07 10:47
Ok I tested what you just asked and yes it works !

ruby version: `2.5.0`
gollum-lib version: ` 4.2.10`
github-markup version: `3.0.1`

**Comment by dometto** [comment] 2018-11-10 23:58
I cannot reproduce this on `5.x`, neither on OS X nor on Ubuntu:
```
$ bundle exec gollum --versions
Gollum 5.0.1b
Running on: x86_64-darwin17 with Ruby version 2.5.3
Using:
gollum-grit_adapter 1.0.1
gollum-lib 5.0.a.4
rugged 0.27.5
gollum-rugged_adapter 0.4.4
With the following renderers:
kramdown 1.17.0
```

@dummys on what platform are you? And am I right to conclude from what your saying that upgrading `github-markup` fixed this?

@deadc0de6 if this persists for you, it may be a problem with `rdoc` on arch.

**Comment by dummys** [comment] 2018-11-11 10:06
@dometto yes you are right.

**Comment by dometto** [comment] 2018-11-11 11:38
Going to close this then since we won't be working on gollum 4.x anymore!

**Closed by dometto** 2018-11-11 11:38 UTC

**Comment by jpittis** [comment] 2019-07-02 21:24
I'm also on Arch and am experiencing the same issue using ruby 2.6.3. Don't have time to debug but wanted to mention that I suspect this is still a problem.
