### ISSUE TITLE
Plantuml won't work under HTTPS

### ISSUE THREAD

**Issue by j4hangir** [gollum/gollum#1117] opened 2016-03-18 03:10 UTC
Evidently the plugin fails for plantuml servers set up at **HTTPS**

**Comment by bartkamphorst** [comment] 2016-03-18 14:33
Please provide more details than this. How are you running gollum? How can the issue be reproduced? What's the error you are seeing?

**Comment by j4hangir** [comment] 2016-03-18 22:43
Hi. 
It concerns `Gollum 4.0.1`.

If the URL below gets changed to **https** the UML generation fails:
```ruby
Gollum::Filter::PlantUML.configure do |config|
    config.url = "http://example.com/plantuml/svg"
end
```

But browsing the same URL in browser (https or not) doesn't produce any errors.

The failure error is `Sorry, unable to render PlantUML diagram at this time`

Originated from [plantuml.rb#105](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/filter/plantuml.rb#), directly caused by function [check_server](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/filter/plantuml.rb#L159). 

However, as aforementioned, the `check_url` defined in the `check_server` works without a glitch in browser.

**Comment by j4hangir** [comment] 2016-03-18 22:44
Hi. 
It concerns `Gollum 4.0.1`.

If the URL below gets changed to **https** the UML generation fails:
```ruby
Gollum::Filter::PlantUML.configure do |config|
    config.url = "http://example.com/plantuml/svg"
end
```

But browsing the same URL in browser (https or not) doesn't produce any errors.

The failure error is `Sorry, unable to render PlantUML diagram at this time`

Originated from [plantuml.rb#105](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/filter/plantuml.rb#), directly caused by function [check_server](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/filter/plantuml.rb#L159). 

However, as aforementioned, the `check_url` defined in the `check_server` works without a glitch in browser.

**Comment by SkyCrawl** [comment] 2016-03-21 08:10
Gollum was not developed with HTTPS in mind and here we see only one of the issues. In this particular case, [it should be easy to resolve](http://stackoverflow.com/questions/5786779/using-nethttp-get-for-an-https-url), however.

**Comment by dometto** [comment] 2016-03-21 22:15
To say that gollum is not intended/designed/able to deal with https seems rather unfair, given the nature of the present issue. As it is built on rack, gollum attempts to be agnostic about https. The plantuml macro is a very recent addition, and the lack of https here is a simple oversight. This oversight occurs more often when using `net/http`, since it's not very intuitive that `:use_ssl` has to be set explicitly even when parsing in an `https://` URI. We consider this a bug and welcome a PR.

**Comment by SkyCrawl** [comment] 2016-03-21 23:03
Indeed. Poor choice of words from my side, I'm sorry. I simply remembered seeing multiple instances of HTTPS incompatibility (or general absence, including the readme and wiki) somewhere in Gollum, so I blurted out that comment...

**Comment by dometto** [comment] 2017-03-28 17:07
I've added an option to use SSL, but this may continue to fail due to certificate checking problems. This is not something we can easily fix inside gollum, but you may be able to configure ruby's `net/http` library in such a way that it recognizes the certificate (by setting a custom CA file). Otherwise, I've added an option to skip certificate checking for PlantUML settings. [See the wiki](https://github.com/gollum/gollum/wiki/Custom-PlantUML-Server#ssl) for a howto.

This will be fixed in the next minor release of `gollum-lib`.

**Closed by dometto** 2017-03-28 17:07 UTC
Labels: bug
