### ISSUE TITLE
Home button is broken

### ISSUE THREAD

**Issue by plujon** [gollum/gollum#1590] opened 2020-07-08 20:09 UTC
The home button in a vanilla instance of gollum now merely loads the same url.  It does not go "home".

I suspect https://github.com/gollum/gollum/pull/1580 .

Perhaps gollum should have a test that the home button works.

**Comment by bartkamphorst** [comment] 2020-07-10 06:59
@heavywatal Could you have a look too see if this issue with the home button is indeed related to #1580?

**Comment by heavywatal** [comment] 2020-07-12 04:49
Thank you for the report, and sorry for the inconvenience. I have just submitted a quick fix.

> Perhaps gollum should have a test that the home button works.

Agreed. Many parts in gollum seems untested.

**Comment by dometto** [comment] 2020-07-15 10:45
Just merged @heavywatal's fix. It'll be contained in the next release of gollum (or you can pull in the changes if you're running from source).

> Agreed. Many parts in gollum seems untested.

Yes, the problem is we currently don't have tests for the UI elements and Javascript. We can test basic route functionality, but to test what happens when you press a button, we would need to add tests using a framework like https://github.com/teamcapybara/capybara

**Closed by dometto** 2020-07-15 10:45 UTC

**Comment by dometto** [comment] 2020-08-03 17:09
Fix released in 5.1
