### ISSUE TITLE
Tables are broken in gollum-lib 4.0.3?

### ISSUE THREAD

**Issue by penguinpowernz** [gollum/gollum#1037] opened 2015-07-27 00:39 UTC
Hey guys, can;t see anyone else having this issue so it must just be something wrong with my setup.  I have recently started using a [docker instance](http://registry.hub.docker.com/genebarker/gollum) to run Gollum and it doesn't seem to be rendering the tables.

I can't see anything about a syntax change and I have tried both the Kramdown and GHFM syntax and neither are working - it just prints everything on the same line:

```
First Header  | Second Header
------------- | -------------
Content Cell  | Content Cell
Content Cell  | Content Cell
```

```
| First cell|Second cell|Third cell
| First | Second | Third |
```

Most of the tables in my existing documentation are formatted as such:

```
| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |
```

This is the list of the gems installed on the docker:

```sh
bigdecimal (1.2.4)
charlock_holmes (0.7.3)
diff-lcs (1.2.5)
github-markup (1.3.3)
gitlab-grit (2.7.3)
gollum (4.0.0)
gollum-grit_adapter (1.0.0)
gollum-lib (4.0.3)
io-console (0.4.2)
json (1.8.1)
kramdown (1.6.0)
mime-types (1.25.1)
mini_portile (0.6.2)
minitest (4.7.5)
mustache (0.99.8)
nokogiri (1.6.6.2)
posix-spawn (0.3.11)
psych (2.0.5)
rack (1.6.4)
rack-protection (1.5.3)
rake (10.1.0)
rdoc (4.1.0)
rouge (1.7.7)
sanitize (2.1.0)
sinatra (1.4.6)
stringex (2.5.2)
test-unit (2.1.5.0)
tilt (2.0.1)
useragent (0.10.0)
```

And this is the command used to run Gollum itself:

```
/usr/bin/ruby2.1 /usr/local/bin/gollum --bare --allow-uploads --h1-title --css --js --no-live-preview /root/wiki.git
```

What am I doing wrong?

**Comment by SkyCrawl** [comment] 2015-07-27 11:31
Hello @penguinpowernz ,

I'm afraid we'll need more information, namely:
* the exact source - ideally a small example page or the table, with a bit of a context,
* the exact output - ideally the appropriate HTML bit :).

I've never seen an issue like this, so we'll probably need to reproduce it at first to learn more about it :).

**Comment by penguinpowernz** [comment] 2015-08-03 03:20
OK, sorry for the late reply...

Here's is the source:

```markdown
[[/uploads/settings-climate-comp-general-setpoints.png|align=center]]

|Field | Description |
|---|---|
| **Start** | The time period start time |
| **Cooling** | Start cooling the compartment if the temperature goes above this |
| **Heating** | Start heating the compartment if the temperature goes below this |
| **RH** | Humidify if the RH goes below this, dehumidify if the RH goes above this |
| **T Ramp &deg;C / hr** | To avoid shocking the plants, transition the **Working Targets** to the **Calc Targets** by this rate |
| **RH Ramp % / hr** | To avoid shocking the plants, transition the **Working Targets** to the **Calc Targets** by this rate |

### Targets
```

Here is the HTML that is generated:

```html
p><span class="align-center"><span><img src="/uploads/settings-climate-comp-general-setpoints.png" /></span></span></p>

<p>|Field | Description |
|---|---|
| <strong>Start</strong> | The time period start time |
| <strong>Cooling</strong> | Start cooling the compartment if the temperature goes above this |
| <strong>Heating</strong> | Start heating the compartment if the temperature goes below this |
| <strong>RH</strong> | Humidify if the RH goes below this, dehumidify if the RH goes above this |
| <strong>T Ramp °C / hr</strong> | To avoid shocking the plants, transition the <strong>Working Targets</strong> to the <strong>Calc Targets</strong> by this rate |
| <strong>RH Ramp % / hr</strong> | To avoid shocking the plants, transition the <strong>Working Targets</strong> to the <strong>Calc Targets</strong> by this rate |</p>

<h3><a class="anchor" id="targets" href="#targets"><i class="fa fa-link"></i></a>Targets</h3>
```

As you can see they are not preceded by white space.

This is the file encoding:

```sh
$ file -bi setting-up-a-new-compartment.md 
text/plain; charset=us-ascii
```

Note that none of the tables in this repo are working, and that gollum is running from a bare repo (I had to clone the repo to check the file encoding).

Thanks for you help!

**Comment by SkyCrawl** [comment] 2015-08-03 11:46
> text/plain; charset=us-ascii

Thank you :). Just a note - this is probably only a guess and the actual encoding is probably different (a superset of `us-ascii` or `ascii` in general).

> Here's the source

I tested it and it worked for me. Despite whitespaces/encoding seem by far the best candidates here, looks like we'll have to get more experimental :(. Let's focus on the environment now... could you, please, try:

1. Running Gollum on a clone, not the bare repo?
2. Running Gollum normally (as shown on Gollum's home page), not via docker?

and see if anything changes? If there are no changes, would it be possible to have you upload a sample file that doesn't work?

**Comment by dometto** [comment] 2015-08-03 11:58
Disparities are probably due to different markdown gems. Gollum now uses kramdown by default, but will switch to github-markdown if it is present (the fallback logic is in the github-markup gem). @penguinpowernz, we haven't yet implemented a debugging option to show which markup gems are being used, but you can `gem list` and see which gems are available.

**Comment by SkyCrawl** [comment] 2015-08-03 20:11
@penguinpowernz 
Idd, I just confirmed it :). I made a clean install, matched your set of gems and kramdown obviously failed to render the table. Once I executed `sudo gem install github-markdown` and restarted Gollum, everything was alright again.

@dometto 
Looks to me that Gollum really begins to have obsolete documentation. I believe the issue of multiple rendering gems should be tracked more closely and publicly, say on Gollum's Home page? E.g. explain the advantage of one gem over the other? Why did Gollum switch to kramdown by the way?

If you give me the necessary and relevant information, I could even make the PR :). Despite I shouldn't allow myself to start dealing with Gollum's code again for other engagements, I could at least deal with the docs a little when I have spare time :). Any other docs related tips?

**Comment by dometto** [comment] 2015-08-03 20:41
Sorry for the confusion!

Looks to me that Gollum really begins to have obsolete documentation. I believe the issue of multiple rendering gems should be tracked more closely and publicly, say on Gollum's Home page?

:+1: it would be good to link to github-markup's fallback logic to explain what's going on, for instance. See https://github.com/github/markup/blob/master/lib/github/markup/markdown.rb#L6

E.g. explain the advantage of one gem over the other?

Well, linking to the gem's website should maybe be enough?

Why did Gollum switch to kramdown by the way?

JRuby support (github-markdown has C-extensions). :) Also, it looks like github-markdown isnt being actively developed, whereas kramdown is now the default for large projects like jekyll.

**Comment by SkyCrawl** [comment] 2015-08-07 18:12
@dometto 
Okay, docs update is on the way. I think we can close this? :)

**Comment by dometto** [comment] 2015-08-07 20:13
Yay!

**Closed by dometto** 2015-08-07 20:13 UTC
