### ISSUE TITLE
Delete file doesn't work

### ISSUE THREAD

**Issue by CrustyAuklet** [gollum/gollum#1620] opened 2020-10-02 04:12 UTC
**Describe the bug**
Using the "overview" mode to view files, if I click the trash can icon to delete a file it initially appears to be removed but persists on page reload.

**To Reproduce**
I want to delete a file that has been uploaded. In our case the file is `uploads/sheet1.png`. Using the "overview" mode to see all the files, the I then navigate to the `uploads` folder. If I then press the "trash can" button next to the file to delete it, gollum asks if I am sure with a popup prompt. After clicking "yes" the file appears to be deleted. But if I then refresh the page, the file is still there.

If I ssh into the server and run `git log` in the gollum directory I see no activity related to the delete attempt.

**Expected behavior**
If I press the trash can icon next to the file it should be removed

**Screenshots**
![image](https://user-images.githubusercontent.com/9755578/94887253-b5ca3e80-042a-11eb-9418-00a5c0f5c36e.png)

**Environment Info**
```
gollum@red-markdown2:~$ gollum --versions
Gollum 5.0.1
Running on: x86_64-linux-gnu with Ruby version 2.7.0
Using:
rugged 0.99.0
gollum-rugged_adapter 1.0
gollum-lib 5.0.4
Markdown rendering gem: kramdown
Other renderering gems:
org-ruby 0.9.12
```

**Comment by dometto** [comment] 2020-12-11 17:29
Hi @CrustyAuklet! I've tried but can't reproduce this. There's been a couple of patch-level updates to gollum-lib, and one patch-level update to gollum. Could you update and let us know if you still encounter this bug? If so, could you let us know:

1. with what arguments you're running gollum
1. whether this occurs with all files or only some
2. if the latter, which files?
  * either point us to an example repository
  * or tell us about the directory structure/filename of the files which display the problem

Thanks!

**Comment by CrustyAuklet** [comment] 2020-12-11 19:50
@dometto the bug still persists, we are running 5.1.2 now. 

It happens with any type of file, specifically for us PDFs and PNG files.

we have files in a single "uploads" folder, with all the markdown pages in the root wiki directory  
example:
```
~/wiki
├── uploads
│  ├── picture.png
│  └── document.pdf
├── WikiPage1.md
└── WikiPage2.md
```
  


we are running gollum using systemd, here is the systemd file and gollum settings file:
```
gollum@wiki-server:~$ cat /etc/systemd/system/gollum.service
[Unit]
Description=Gollum wiki server
After=network.target
After=syslog.target

[Service]
Type=simple
User=gollum
Group=gollum
WorkingDirectory=/home/gollum/wiki/
ExecStart=/usr/local/bin/gollum --config "/etc/gollum/config.rb" --css --js
Restart=on-abort

[Install]
WantedBy=multi-user.target
```

```
gollum@wiki-server:~$ cat /etc/gollum/config.rb
=begin
This file can be used to (e.g.):
- alter certain inner parts of Gollum,
- extend it with your stuff.

It is especially useful for customizing supported formats/markups. For more information and examples:
- https://github.com/gollum/gollum#config-file

=end

# enter your Ruby code here ...

Gollum::Page.send :remove_const, :FORMAT_NAMES if defined? Gollum::Page::FORMAT_NAMES

## Omni Auth
require 'rubygems'
require 'gollum/app'
require 'omnigollum'
require 'omniauth-ldap'

#OmniAuth::Strategies::LDAP

wiki_options = {
  :live_preview => true,
  :allow_uploads => 'page',
  :per_page_uploads => false,
  :allow_editing => true,
  :css => true,
  :js => true,
  :mathjax => true,
  :h1_title => true
}
Precious::App.set(:wiki_options, wiki_options)

options = {
  :providers => Proc.new do
    provider :ldap,
        :title => "Gollum Authentication USE YOUR WINDOWS CREDENTIALS",
        :host => 'red-dc1',
        :port => 389,
        :method => :plain,
        :base => 'ou=Employees,dc=internal,dc=MyCompany,dc=com',
        :uid => 'sAMAccountName',
        :name_proc => Proc.new {|name| name.gsub(/@.*$/,'')},
        :bind_dn => '##################',
        :password => '##########################'
  end,
  :dummy_auth => false,
  #:protected_routes => ['/*'],
  :author_format => Proc.new { |user| user.name },
  :author_email => Proc.new { |user| user.email },

  :authorized_users => nil,
}


## :omnigollum options *must* be set before the Omnigollum extension is registered
Precious::App.set(:omnigollum, options)
Precious::App.register Omnigollum::Sinatra
```

**Comment by dometto** [comment] 2020-12-12 13:07
Thanks for the info! It's interesting that you're using omniauth. My first thought is that something may be going wrong with authentication for the delete route that's being called via Ajax when you click the trashcan.

**Comment by dometto** [comment] 2020-12-12 13:10
Actually, if that's the case you should be seeing a 401 Unauthorized or similar in the network activity pane of your browser's developer tools, when clicking the button. It would be useful to know what happens there anyway -- e.g. is the `/gollum/delete` route being hit at all?

**Comment by dometto** [comment] 2020-12-13 18:59
A fix for this is in https://github.com/gollum/gollum/issues/1620 . It will be in the next bugfix release, but you can also grab the patch (or pull the changes from `master` as soon as it is merged).

**Comment by CrustyAuklet** [comment] 2020-12-14 17:29
Thanks! I will try to bring in those latest changes, and see if it fixes the problem. You linked to this issue but I presume you mean #1639 ?

**Comment by dometto** [comment] 2020-12-15 08:39
> You linked to this issue but I presume you mean #1639 ?

Yeah indeed!

**Comment by CrustyAuklet** [comment] 2020-12-15 19:11
@dometto I went into our server and manual did the edits from #1639 to :  
  - /var/lib/gems/2.7.0/gems/gollum-5.1.2/lib/gollum/templates/overview.mustache
    - I added an additional winky face `;)` to the popup message so i know my changes are running for my own sanity
  - /var/lib/gems/2.7.0/gems/gollum-5.1.2/lib/gollum/views/overview.rb
 
Restarted the server and the problem seems to persist even though I see my winky face in the message ☹️

**Closed** 2021-01-04 10:29 UTC
Labels: bug, hacktoberfest, help wanted
