### ISSUE TITLE
Locally Cloned Gollum Demo Does Not Render Images

### ISSUE THREAD

**Issue by nkabir** [gollum/gollum#1807] opened 2022-02-25 16:16 UTC
Local images using `[[image]]` notation generate 404 errors.

1. Clone [https://github.com/mojombo/gollum-demo](https://github.com/mojombo/gollum-demo)
2. cd into `gollum-demo`
3. In browser, go to `http://localhost:4567/Mordor/Eye-Of-Sauron.md`

```
gollum --versions
Gollum 5.2.3
Running on: x86_64-linux-gnu with Ruby version 2.7.0
Using:
rugged 1.1.1
gollum-rugged_adapter 1.1.2
gollum-lib 5.1.3
Markdown rendering gem: kramdown
Other renderering gems:
none
```

**Comment by benjaminwil** [comment] 2022-03-02 23:00
No problem! I am still curious about the issue and intend to try to reproduce in an environment more like the reported one.

**Comment by dometto** [comment] 2022-05-26 08:55
I can't reproduce this on ruby-2.7.0 with either the latest gollum, or `v5.2.3` (which @nkabir used). This leaves only the difference between OS X and Linux, but I wonder if something else might not have been up: a corrupt test repo, say. I'm also curious but think we can close this -- unless @benjaminwil still wants to investigate further :)

**Comment by benjaminwil** [comment] 2022-05-26 15:57
I'll close for now!

**Closed by benjaminwil** 2022-05-26 15:57 UTC
