### ISSUE TITLE
<H1> display and button conflict when I initialize a wiki project

### ISSUE THREAD

**Issue by fangjishuai** [gollum/gollum#1537] opened 2020-04-02 08:52 UTC
Environment：

- gollum-version：5.0.0
- ruby-version:       2.4.4
- rugged-version:   0.99.0

Steps ：

- `mkdir wiki`
- `cd wiki`
- `git init`
- `gollum --host "0.0.0.0" --port "4567" --base-path "wiki" --h1-title --user-icons "identicon" --emoji --mathjax --allow-uploads "dir" --css /home/wiki/wiki 1>golluom.log 2>&1 &`

**Comment by fangjishuai** [comment] 2020-04-02 08:53
![1](https://user-images.githubusercontent.com/26083850/78229334-7023cc00-7502-11ea-9b6b-a20cecfa2246.png)
![2](https://user-images.githubusercontent.com/26083850/78229353-76b24380-7502-11ea-9790-b098917bd338.png)

**Comment by dometto** [comment] 2020-04-02 09:01
I'm not sure what the problem is here, as it seems you're using a custom CSS, which probably accounts for the distorted layout (there were many layout changes in 5.x). The JS error you're seeing is because you haven't committed a `mathjax.config`, but that shouldn't impact anything (you can still use mathjax, with the default config). If I'm missing something, please reopen with more info.

**Closed by dometto** 2020-04-02 09:01 UTC
