### ISSUE TITLE
Problems caused by language

### ISSUE THREAD

**Issue by zhangjiahaoGitHub** [gollum/gollum#2020] opened 2023-12-07 10:12 UTC
![1701943875131](https://github.com/gollum/gollum/assets/50603506/a1eb872a-8961-47d0-b6fe-fa1d7e1f0cf7)
![image](https://github.com/gollum/gollum/assets/50603506/eb4b7efb-378b-433d-9e78-35c0f4867d7d)
The rendered dom is different.
As a result, the following one cannot adapt to the height.

**Comment by benjaminwil** [comment] 2024-04-21 18:42
This seems to be an issue with Mermaid upstream, but I'm unsure exactly how to even report the issue to Mermaid.

I was able to reproduce using an emoji, as well. To quickly reproduce you can save a Gollum page with this content:

<pre>
 Correct height Mermaid diagrams:

```mermaid
sequenceDiagram
    participant a as a
    participant b as b
    participant c as c
    participant d as d
```

```mermaid
pie title NETFLIX
    "Time spent looking for movie" : 90
    "Time spent watching it" : 10
```

Mermaid diagram frame is too small:

```mermaid
sequenceDiagram
    participant a as 😪
    participant b as b
    participant c as c
    participant d as d
```
</pre>

Where the first two diagrams appear correctly and the last one appears the same way that the original issue message describes.

**Comment by dometto** [comment] 2024-04-21 18:59
The unicode text seems to work ok in the Mermaid live editor though: https://mermaid.live/edit#pako:eNpljjEOwyAQBL-CrvYLqPODtDTnu0uCYjCBo4gs_yOd-7wuTwgUrthqNbvS7ga0soCFIq8qkeTi8Z4xuGiaEmb15BNGNWiwmN_x-Y7R3KN55NQ5jZw7Z5ggSA7ouc1vveVAHxLEgW2WMT8duLi3HlZdr-9IYDVXmaAmRj2vgr3hUmT_A_ESRak

Could it be that gollum (gollum-lib in this case) is not properly setting the encoding of the text in the mermaid block?

**Comment by benjaminwil** [comment] 2024-04-21 19:02
I was able to make a much more exaggerated reproduction:

<img width="762" alt="Screenshot 2024-04-21 at 12 01 26 PM" src="https://github.com/gollum/gollum/assets/883581/b0233633-5162-4475-9e08-5076b4538cc8">

<pre>
Correct:

```mermaid
pie title NETFLIX
    "one" : 90
    "two" : 10
```

Incorrect:

```mermaid
pie title NETFLIX
    "😪" : 90
    "😠" : 10
```
</pre>

**Comment by dometto** [comment] 2024-04-21 19:07
Looks like it is indeed an issue with sandbox mode, see [here](https://jsfiddle.net/pret25d8/). If you remove the `securityLevel: 'sandbox'` from the configuration, both diagrams render as expected.

**Comment by dometto** [comment] 2024-12-29 13:24
Fixed in the latest version of Gollum, which uses an updated version of Mermaid.

**Closed by dometto** 2024-12-29 13:24 UTC
