### ISSUE TITLE
5.x: modal dialog styling issue

### ISSUE THREAD

**Issue by scolytus** [gollum/gollum#1366] opened 2019-01-04 18:24 UTC
There is a styling issue with the modal dialogs (New, Upload)
Screenshot taken on Windows & FF 64. Chrome looks the same.

![2019-01-04_18h29_43](https://user-images.githubusercontent.com/1374754/50704006-37bee500-1056-11e9-9b4b-3d0078c78a72.png)

**Comment by bartkamphorst** [comment] 2019-01-04 21:08
Duplicate of https://github.com/gollum/gollum/issues/978.

**Closed by bartkamphorst** 2019-01-04 21:08 UTC
