### ISSUE TITLE
Submodule support

### ISSUE THREAD

**Issue by bootstraponline** [gollum/gollum#438] opened 2012-07-17 01:50 UTC
At least two issues (#151, #369) have mentioned problems using submodules with Gollum. Gollum should either support submodules or document why it's not currently possible.

**Comment by dometto** [comment] 2017-04-05 20:57
Closing this as the issue is with the underlying git implementations. If gitlab does not want to support submodules in `gitlab-grit` (as it appears from https://github.com/gitlabhq/grit/pull/29), then that's it; we will not maintain our own fork.

At the moment, it looks like `rugged` also does not support submodules. If people want to use submodules with the `rugged-adapter`, please file on issue or work on a solution there. Unfortunately, submodules currently also do not work in the `rjgit` adapter.

**Closed by dometto** 2017-04-05 20:57 UTC
Labels: feature

**Comment by dometto** [comment] 2017-08-31 08:24
@milesrichardson I just read that JGit contains rudimentary submodule support, so you might try the following:
1. Install the rjgit adapter
2. Run gollum with the following flags:
--adapter rjgit
--page-file-dir path/to/submodule/in/your/repo
/path/to/your/repo

**Comment by dometto** [comment] 2017-08-31 08:26
I forgot to say: this may well work for reading pages in the submodule, but might fail for editing/creating new pages. I'd be interested to hear what happens.

**Comment by melMass** [comment] 2018-09-24 16:00
@milesrichardson Technique should be documented. it feels hacky but with a few scripts allow to fake the feeling of wiki as submodule.

**Comment by petrkalina** [comment] 2020-02-28 16:43
+1

**Comment by remyd1** [comment] 2022-02-08 08:04
+1

I would also need this submodule feature.
