### ISSUE TITLE
ArgumentError - invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by ldeluigi** [gollum/gollum#1718] opened 2021-05-13 13:21 UTC
**Describe the bug**
When requesting for a file, like /Home, this happens:
2021-05-13 13:08:01 - ArgumentError - invalid byte sequence in US-ASCII:
/var/lib/gems/2.5.0/gems/mustache-0.99.8/lib/mustache/context.rb:31:in `gsub'

**To Reproduce**
RUN gem install gollum
RUN gollum --port 8081 --config=/etc/gollum/config.rb

config.rb:
```
wiki_options = {
  :live_preview => false,
  :allow_editing => false,
  :allow_uploads => false,
  :h1_title => true,
  :universal_toc => true,
  :mathjax => true,
  :js => true
}

Gollum::Filter::PlantUML.configure do |config|
  config.url = "http://localhost/plantuml/svg"
  config.verify_ssl = false
end

Precious::App.set(:wiki_options, wiki_options)
Precious::App.set(:environment, :production)
```

**Expected behavior**
It should render the page correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/44567586/118142178-6d382200-b40a-11eb-9dfc-b865334167ac.png)
![image](https://user-images.githubusercontent.com/44567586/118142203-72956c80-b40a-11eb-989a-6c01167e74fd.png)
![image](https://user-images.githubusercontent.com/44567586/118142252-7d500180-b40a-11eb-9b33-371724565540.png)

**Environment Info**
Gollum:  [2021-05-13 13:07:46] INFO  WEBrick 1.7.0
Gollum:  [2021-05-13 13:07:46] INFO  ruby 2.5.5 (2019-03-15) [x86_64-linux-gnu]
Gollum:  == Sinatra (v2.1.0) has taken the stage on 8081 for production with backup from WEBrick
Gollum:  [2021-05-13 13:07:46] INFO  WEBrick::HTTPServer#start: pid=13 port=8081

Run inside debian:buster-slim image

**Comment by ldeluigi** [comment] 2021-05-13 14:18
It seems that this doesn't happens with Ruby 2.7, but I don't know why, and I'm not even sure

**Comment by dometto** [comment] 2021-05-14 07:08
Duplicate of #1699. Thanks for the tip about ruby 2.7 though!

**Closed by dometto** 2021-05-14 07:08 UTC
