### ISSUE TITLE
Gollum with pandoc-ruby renders math weirdly

### ISSUE THREAD

**Issue by ashwinreddy** [gollum/gollum#1589] opened 2020-07-01 17:49 UTC
**Describe the bug**

Installing `pandoc-ruby` correctly renders the bibliography, but at the cost of not rendering math with backslashes properly.

**To Reproduce**
1. Install the gems needed for bibliography rendering.
2. Make a Test.bib file (e.g. `@misc{name, title = {Title}, howpublished = {\url{https://google.com}}, year = {2020}}`) and a Home file in the wiki:

```
---
bibliography: Test.bib
---

See [@name]. 

\begin{gather}
\mathbf{A}\vec{v} = \lambda \mathbf{I}\vec{v} \\\\\
\left(\mathbf{A} - \lambda \mathbf{I} \right)\vec{v} = 0
\end{gather}

Here is some inline math also: $\det(A - \lambda \mathbf{I})=0$.
```

**Expected behavior**
I'm expecting my math to look exactly the same and the `[@name]` turns into a sensible citation.

**Screenshots**

Here is the rendering without `pandoc-ruby`.
<img width="1280" alt="Screenshot 2020-07-01 10 41 47" src="https://user-images.githubusercontent.com/2141637/86275072-8dab1500-bb87-11ea-9956-58833fcf0ec4.png">

Then I install `pandoc-ruby` and get this. The citation is correct, but my multiline math doesn't get rendered and the inline math is now differently rendered.

<img width="1280" alt="Screenshot 2020-07-01 10 42 06" src="https://user-images.githubusercontent.com/2141637/86275083-91d73280-bb87-11ea-9ff5-98604ed877b8.png">

The solution would be to escape every backslash, but I'd prefer to find a solution that doesn't require a drastic change like that, if possible, seeing as everything was working fine with kramdown. It also doesn't fix the inline math being rendered differently. I've tried changing the code to use `pandoc-ruby` with certain pandoc extensions, but then the bibliography doesn't work.

**Environment Info**

```
Gollum 5.0.1
Running on: x86_64-darwin19 with Ruby version 2.6.3
Using:
rugged 0.99.0
gollum-rugged_adapter 1.0
gollum-lib 5.0.4
Markdown rendering gem: pandoc-ruby
Other renderering gems:
none
```

**Comment by heavywatal** [comment] 2020-07-02 14:45
Sorry I didn't get what exactly the problem is. Could you clarify it? The previous threads #1559 and #1588 will help you break down problems. If it is an expected behavior of `pandoc-ruby`, gollum can do almost nothing. If not, you should consult `pandoc-ruby` community first.

**Comment by ashwinreddy** [comment] 2020-07-02 17:48
The problem is basically that pandoc processes the math on the backend rather than letting MathJax do its job in the browser, if that makes sense. I've found a fix in case anyone else runs into this:

```rb
GitHub::Markup::Markdown::MARKDOWN_GEMS['pandoc-ruby'] = proc { |content|
          PandocRuby.convert(content, :from => 'markdown-tex_math_dollars-raw_tex', :to => :html, :filter => 'pandoc-citeproc')
      }
```

Feel free to close this issue if there's nothing more to add, and thanks for the help!

**Comment by dometto** [comment] 2020-07-03 08:38
Happy you found a fix that works for you, @ashwinreddy. Does your fix work well when MathJax is simultaneously enabled in gollum? I guess we could opt to enable pandoc's own math processing by default, in that case.

**Comment by ashwinreddy** [comment] 2020-07-04 05:42
Yup, my fix lets me use MathJax the same as before installing pandoc-ruby. I'd be happy to see pandoc enabled by default so that citations work out of the box.

**Comment by dometto** [comment] 2020-07-05 11:25
@heavywatal @bartkamphorst can you see any objections to letting pandoc handle math by itself? I'm assuming most users who use pandoc for citations will either want, or not mind, having math enabled.

**Comment by heavywatal** [comment] 2020-07-05 12:20
If I understand it correctly, pandoc math is enabled by default, and @ashwinreddy 's solution is to disable/bypass pandoc math to get unprocessed text and let MathJax handle it. It will be nice to have this setting in gollum and make it follow gollum's `--mathjax` option.

**Comment by bartkamphorst** [comment] 2020-07-06 11:05
>  @ashwinreddy 's solution is to disable/bypass pandoc math to get unprocessed text and let MathJax handle it

This was my understanding as well.

> It will be nice to have this setting in gollum and make it follow gollum's --mathjax option.

Agreed. 👍

**Comment by dometto** [comment] 2020-07-07 11:54
> @ashwinreddy 's solution is to disable/bypass pandoc math to get unprocessed text and let MathJax handle it

Even better! @ashwinreddy, are you interested in submitting your fix as a PR to gollum-lib?

**Comment by ashwinreddy** [comment] 2020-07-08 01:50
Done! PR is over at https://github.com/gollum/gollum-lib/pull/383.

**Comment by dometto** [comment] 2020-07-15 10:41
Fixed when https://github.com/gollum/gollum-lib/pull/383 will be released

**Closed by dometto** 2020-07-15 10:41 UTC
