### ISSUE TITLE
Encoding::CompatibilityError at /create incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by NabiKAZ** [gollum/gollum#1114] opened 2016-03-03 02:46 UTC
Can not create page with unicode filename and also don't show file with unicode filename that commited.
![screenshot-127 0 0 1 4567 2016-03-03 06-11-56](https://cloud.githubusercontent.com/assets/246721/13483129/2585ec2a-e107-11e5-9e93-27991ee0a466.png)

**Comment by SkyCrawl** [comment] 2016-03-04 18:39
Hello @NabiKAZ 

could you please post the respective console output? It may contain more detailed information.

**Comment by hs3180** [comment] 2016-04-28 07:23
@SkyCrawl 
I may get the same problem, logs are here:

    2016-04-28 07:19:43 - Encoding::CompatibilityError - incompatible character encodings: UTF-8 and ASCII-8BIT:
        /var/lib/gems/1.9.1/gems/gitlab-grit-2.7.3/lib/grit/index.rb:176:in `%'
        /var/lib/gems/1.9.1/gems/gitlab-grit-2.7.3/lib/grit/index.rb:176:in `block in write_tree'
        /var/lib/gems/1.9.1/gems/gitlab-grit-2.7.3/lib/grit/index.rb:171:in `each'
        /var/lib/gems/1.9.1/gems/gitlab-grit-2.7.3/lib/grit/index.rb:171:in `write_tree'
        /var/lib/gems/1.9.1/gems/gitlab-grit-2.7.3/lib/grit/index.rb:198:in `block in write_tree'
        /var/lib/gems/1.9.1/gems/gitlab-grit-2.7.3/lib/grit/index.rb:180:in `each'
        /var/lib/gems/1.9.1/gems/gitlab-grit-2.7.3/lib/grit/index.rb:180:in `write_tree'
        /var/lib/gems/1.9.1/gems/gitlab-grit-2.7.3/lib/grit/index.rb:123:in `commit'
        /var/lib/gems/1.9.1/gems/gollum-grit_adapter-1.0.0/lib/grit_adapter/git_layer_grit.rb:249:in `commit'
        /var/lib/gems/1.9.1/gems/gollum-lib-4.1.0/lib/gollum-lib/committer.rb:170:in `commit'
        /var/lib/gems/1.9.1/gems/gollum-4.0.1/lib/gollum/app.rb:207:in `block in <class:App>'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
        /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
        /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
        /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
        /usr/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
        /usr/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
        /usr/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
    172.17.0.2 - - [28/Apr/2016:07:19:42 UTC] "POST /uploadFile HTTP/1.1" 500 153879

I am using the latest official gollum docker container.

**Comment by SkyCrawl** [comment] 2016-04-28 09:33
@hs3180 
I'm sorry but I couldn't reproduce your issue. Would it possible for me to download the file causing the issue? Anyway, [this](https://gitlab.com/gitlab-org/gitlab-grit/blob/v2.7.3/lib/grit/index.rb#L176) is the relevant code.

@NabiKAZ @hs3180 
I am unable to reproduce both of your issues, either using Ruby 1.9.3 or 2.3.0. Even trying to create a page with arabian content didn't yield the expected encoding mismatch. I don't want to believe the issue is caused by the environment, and if so, there should be a way to fix it. At the moment, I'm more inclined to believe that the fault lies in different Ruby development environments of all the gems. For instance, `gitlab-grit` (see the link above) doesn't seem to include the `# encoding: UTF-8` initial comment, which could be causing your issue @hs3180 . Worse even, the declared comment encoding could be different from the actual file encoding in some cases but luckily, that shouldn't really be related to the error in question.

Possible fixes include:
* Upgrading to Ruby 2.0 or newer as it is the first version that parses Ruby scripts using UTF-8 encoding by default. If nothing else, that makes for some interoperability issues...
* Inspecting and perhaps modifying the `Encoding::default_external` and `Encoding::default_internal` values. More information [here](http://ruby-doc.org/core-2.0.0/Encoding.html) (Ruby 2.0).

**Comment by bigyuki** [comment] 2016-06-29 08:06
+1

I got the same error, and when i change to `ragged` adapter , the error was gone. 

so i think is the `gitlab-grit` unicode problem

beside, if i search with unicode characters in gollum with `ragged` adapter , unicode problem happen again.

why there are so much ruby unicode problem = =

**Comment by tnt** [comment] 2017-06-03 10:35
I 'fixed' the issue temporarily by hacking the following (which is line 176 in `gitlab-grit-2.8.1/lib/grit/index.rb`) from:

    tree_contents[k] = "%s %s\0%s" % [tmode, obj.name, sha]

to:

    tree_contents[k] = "%s %s\0%s" % [tmode, obj.name.force_encoding('ASCII-8BIT'), sha]

I reproduced it with Ruby 2.2.5 and 2.3.3 with the following Gemfile:

```ruby
gem 'gollum'
gem 'github-markup'
gem 'github-markdown'
gem 'creole'
gem 'org-ruby'
gem 'rack'
```
Will we ever get rid of encoding errors?

**Comment by tnt** [comment] 2017-06-03 13:24
The error occurs independently of what string is actually submitted:

**Post**

| Variable | Value |
|------------|--------------|
| content	|"test"|
| format	| "markdown" |
|message	 |"Created test (markdown)"|
|page	|"test"|
|path	|"/"|

It seems funny to me that it works anywhere at all. What could be the difference in the setup?

My `Encoding.default_internal` is `nil`, `Encoding.default_external` is `'UTF-8'`.

**Comment by chris2fr** [comment] 2018-01-02 11:22
I have the same problem on my Mac after updating ACE to 1.2.9 from 1.2.5 and updating to branch 5.x on Chrome. I do not have the problem on Safari, but Safari doesn't charge the new editing pane from ACE (yet). Strange, but a real problem. 

(By the way, I do not have the dead-keys problem with the ACE-1.2.9 #1275 )

**Comment by chris2fr** [comment] 2018-01-02 11:28
I applied the above-mentioned patch \

> tree_contents[k] = "%s %s\0%s" % [tmode, obj.name.force_encoding('ASCII-8BIT'), sha]

to

> /usr/local/lib/ruby/gems/2.4.0/gems/gitlab-grit-2.8.2/lib/grit/index.rb

and it works.

**Comment by bartkamphorst** [comment] 2018-09-17 18:04
This will be fixed in `5.x` with either the rugged adapter or RJGit adapter.

**Closed by bartkamphorst** 2018-09-17 18:04 UTC
Labels: unicode
