### ISSUE TITLE
5.x: github wiki compatbility

### ISSUE THREAD

**Issue by petrkalina** [gollum/gollum#1494] opened 2020-03-24 10:26 UTC
While fixing incompatibility of anchors handling between github and gollum (see: https://github.com/dcm4che/dcm4chee-arc-light/wiki/Anchor-Test), v5 introduces some new compatibility problems.

Based on https://github.com/gollum/gollum/wiki/5.0-release-notes#filename-handling, the markdown imported from github will no longer be interpreted correctly, because links to pages will not work, if interpreted literally i.e.

`[[Page Name]]` pointing to i.e. `/wiki/folder/Page-Name.md` that will work in github wiki (following github default filename conventions) will no longer work in gollum 5

I'm aware of the `--global-tag-lookup` which resolves the `/folder/` problem. However, it would be great to have also `--github-page-names` or similar to be able to accomodate github style links..

The overall use-case is when trying to run gollum on wiki repos cloned from github - which I believe is one of the core use-cases. In my case, the github wiki is cloned to a sub-folder of the gollum wiki (as it is not possible to use git submodules due to another issue..)

I can imaging having a global tag i.e. `--github-compatible` which would configure gollum to be as compatible as it can be with github wikis.

I can also imagine publishing a `gollum MD compatibility wiki page` on project wiki, which would highlight non-compatible syntax from github to help people interested in the mentioned use-case.

I'm aware that this is not really an issue, more like a question towards what are the main use-cases driving v5 effort. I'm more than willing to contribute, but I have to first learn how it all works, so for the moment, I'm just posting this. Thanks for a great effort nonetheless!

**Comment by dometto** [comment] 2020-03-24 12:02
@petrkalina jsut to make sure: the issue is that github links with spaces (`[[Page Name]]`) will match pages with dashes (`Page-Name`)? If that's right, we'll consider whether to add a compatibility option. We will definitely make sure the `gollum-migrate-tags` script is able to update the filenames to the new 5.x convention.

To explain the new behavior: originally, the substitution of dashes for whitespace was a necessity in the original version of gollum which ran on github, because the git backend (grit) couldn't handle spaces in filenames. We thus considered this a limitation that we could get rid of after ditching grit in favor of rugged (and rjgit on JRuby) as backends.

**Comment by dometto** [comment] 2020-03-24 12:05
>  We will definitely make sure the gollum-migrate-tags script is able to update the filenames to the new 5.x convention.

On second thought, in this case the best way to migrate might not be to update the tags (so change all `[[Page Name]]` to `[[Page-Name]]`, but change the filenames, which users could do themselves. Thoughts?

**Comment by petrkalina** [comment] 2020-03-24 13:10
Hello, thanks for fast reaction!

One thing I would like to point out is, that my use-case is not "migration" of github wiki, but rather "inclusion". As mentioned, favoured solution would be i.e.:

```
/wiki $ git submodule add {os-project}.wiki.git
```

so that you are still able to get latest changes from github via

```
/wiki $ git submodule update --remote [{os-project}]
```

apart from gollum not being able to work with submodules.. Just to illustrate exactly where I come from. For the moment, I use `git clone {os-project}` instead, and then commit the changes to `/wiki`..

I still think that github compatibility can be one of the major USPs of gollum. 

I think there are two options in general  how to provide this:

- support maximum out-of-the-box compatiblity with github i.e. via a dedicated switch
- provide migration script for github wikis

I guess the second is a bit more flexible and possibly simpler and sufficient, the first is simpler for the user to integrate in a use-case similar to mine..

JFYI was just going to test the migration script `gollum-migrate-tags`, but I'm struggling to run it from the source for the moment, so I do not have practical experience with it yet..

**Comment by dometto** [comment] 2020-03-24 13:26
Thanks for the explanation!

>    provide migration script for github wikis

Right. This could not mean changing page names on github wikis to use spaces instead of dashes, since github does not support it. So it would have to mean changing links in github wikis to explicitly use the dashes, rather than the spaces. The `gollum-migrate-tags` script could definitely support that (it doesn't, yet).

Would it be helpful to just include both options, and let the user decide what they want to do? Thoughts, @bartkamphorst?

**Comment by dometto** [comment] 2020-03-24 20:06
See https://github.com/gollum/gollum-lib/pull/365

**Comment by dometto** [comment] 2020-03-25 11:29
@petrkalina I've merged fixes to gollum and gollum-lib to try and resolve this issue. Could you checkout a fresh version of gollum `5.x`, and try with the `--hyphenated-tag-lookup` option? Please let us know how it works and if this resolves the issue.

**Comment by dometto** [comment] 2020-03-26 09:16
Ping @petrkalina

**Comment by petrkalina** [comment] 2020-03-26 12:22
<img width="393" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77646401-c1611800-6f64-11ea-8bcb-b6f67928319e.png">

**Comment by dometto** [comment] 2020-03-26 12:34
> Precious::App.settings.wiki_options[:global-tag-lookup] = true

Typo, should be `:global_tag_lookup`.

Notice that instead of configuring this in `config.rb` you can now also run `bundle exec gollum --hyphened-tag-lookup --global-tag-lookup /path/to/repo` (the command line options use `-`, the ruby symbols use `_`).

**Comment by petrkalina** [comment] 2020-03-26 12:38
otherwise running as:

```
petrs-MacBook-Pro:gollum-local petr$ docker exec gollum-v5-1 ps ax
  PID TTY      STAT   TIME COMMAND
    1 ?        Ssl    0:01 bin/gollum --global-tag-lookup --config config.rb --port 80 --allow-uploads page /wiki
 ```

with

```
Precious::App.settings.wiki_options[:hyphened_tag_lookup] = true
```

in `config.rb`

I get the following results:

```
page files

/test/Page-Name-1.md
/test/Page Name 2.md
/test/page-name-3.md
```
- `[[/test/Page-Name-1]]`: ok
- `[[Page-Name-1]]`: ok
- `[[/test/Page Name 1]]`: ok
- `[[Page Name 1]]`: ok


- `[[/test/Page-Name-2]]`: no
- `[[Page-Name-2]]`: no
- `[[/test/Page Name 2]]`: ok
- `[[Page Name 2]]`: no (this is surprising)


- `[[/test/Page-Name-3]]`: no
- `[[Page-Name-3]]`: no
- `[[/test/Page Name 3]]`: no
- `[[Page Name 3]]`: no

(sorry, a page screenshot would be nicer, but I do not have any styles at the moent..)

vs. on github:

<img width="574" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77647619-06864980-6f67-11ea-9d1a-754c4f4c338e.png">

**Comment by petrkalina** [comment] 2020-03-26 12:39
> > Precious::App.settings.wiki_options[:global-tag-lookup] = true
> 
> Typo, should be `:global_tag_lookup`.
> 
> Notice that instead of configuring this in `config.rb` you can now also run `bundle exec gollum --hyphened-tag-lookup --global-tag-lookup /path/to/repo` (the command line options use `-`, the ruby symbols use `_`).

ok, I see

**Comment by petrkalina** [comment] 2020-03-26 12:46
gollum 4:

<img width="684" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77648300-341fc280-6f68-11ea-86a9-29b9609a2b17.png">

**Comment by dometto** [comment] 2020-03-26 14:54
Thanks! So it seems to me that

* Everything is fine for `Page-Name-1` (it supports absolute links which github doesn't, but that's fine -- we can support *more* than github, as long as we don't support less).
* It's true that case insensitivity is gone in 5.x. However, I'm reluctant to change this. Consider:
  * You might have two files in the same directory, `bilbo` and `Bilbo`.
  * Case insensitivity would mean that it's unclear what resource is meant by `Bilbo` and `bilbo`, and that one of the files is inaccessible.
  * Even if you force lowercase or uppercase when creating new pages via the web interface, so that you can e.g. only create `Bilbo.md`, someone could still add `bilbo.md` on the command line, thus creating the above situation.

So I'm inclined to say that the case-insensitivity on github.com is problematic. Also see the extended discussion about case-sensitivity in https://github.com/gollum/gollum/issues/824. You can already use the `gollum-migrate-tags` script to migrate your case-insensitive tags. Does that sound fair?

That leaves the differences on Page 2 to be investigated. Get back to you about that in a second.

**Comment by dometto** [comment] 2020-03-26 15:17
On Page 2:

* `[[/test/Page-Name-2]]` works on 4.x, but NOT on github and 5.x
  * it doesn't work on github because of the absolute path. This is fine: gollum allows abs paths in addition to relative paths.
  * it doesn't work on 5.x for a different reason: there is no file `Page-Name-2` (with dashes)
* `[[/test/Page Name 2]]` works on 4.x AND github, but NOT on 5.x
  * it doesn't work because the `--hyphened-tag-lookup` option makes 5.x look for a file with dashes, which doesn't exist.
* `[[/test/Page Name 2]]` works on 4.x AND 5.x, NOT github.
  * This is because it's an absolute path. Again, Gollum allows more than Github, which is fine. 5.x correctly mimics 4.x's behavior.
*  `[[Page Name 2]]` works on 4.x, AND on github, NOT on 5.x
  *  Again, it doesn't work because 5.x with the compatibility option is expecting a file with dashes, which doesn't exist.

Conclusion: 4.x and github.com are more lenient than I thought. They will:
  1. resolve `[[Bilbo-Baggins]]` to `[[Bilbo Baggins]]`
  2. resolve `[[Bilbo Baggins]]` to `[[Bilbo-Baggins]]`

...whereas 5.x only does the second.

**Comment by petrkalina** [comment] 2020-03-26 15:58
thanks for the answer!! 

- `Case sensitivity`: yes, I agree that it is ok to consider case mismatch an error. On the other hand, in case all pages are created via UI (github or later gollum), the situation with ambiguous references should not occur because of this. Also note, that supporting i.e. `global-tag-lookup` while in the same time supporting paths (which is awesome and a key feature imo) makes it possible to create ambiguous references anyways (`[[Global Name]]` -> `/Global Name.md`, `/subfolder/Global Name.md`). 
- `[[Bilbo-Baggins]] -> /Bilbo Baggins.md` link: I guess no problem consider this an error.. 

So it seems it all works ok and should be able to accommodate github wiki. 

As I mentioned earlier, as an option, you could also introduce i.e. `strict-lookup-mode` and `github-lookup-mode` and group all the behaviour under these options, maybe replicating the leniency of github in github mode. You could also support `strict-github-lookup-mode` where paths would not resolve .. i.e. it would strictly replicate github behaviour .. but that is probably too much effort for non-critical feature..

I can also imagine, that some features may only be available in the `strict-lookup-mode` in case they depend on attributes of the refs / file tree that `github-lookup-mode` does not guarantee, for example - i.e. if ambiguous references render some feature inconsistent, for example..

**Comment by dometto** [comment] 2020-03-26 16:13
@petrkalina In https://github.com/gollum/gollum-lib/pull/366 I added support for case-insensitivity, and for resolving `[Bilbo-Baggins]`] to `[[Bilbo Baggins]]` when using `--hyphened-tag-lookup`. 👍  Thanks for all the testing and reports!

@bartkamphorst what do you think about grouping some or all of these options together?

**Comment by dometto** [comment] 2020-03-27 11:19
@petrkalina we have added the `--leniet-tag-lookup` combined option as you suggested (and removed the individual options, although you can still set those in a `config.rb`). This now includes case-insensitive lookup, and a fix for the remaining incompatibilities on your Page Name 2. If you want, give the new option a spin and let us know if you're satisfied!

**Comment by petrkalina** [comment] 2020-03-27 14:31
I'm not sure what is the relation between `config.rb` and command-line options i.e.:

- are ALL commandline options configurable also via `config.rb`?
- are some options ONLY available in `config.rb` or ONLY available as command-line options?

I guess this should be well documented. Sorry if I'm nissing something that is in the wiki..

I will test with:

```
# Precious::App.settings.wiki_options[:hyphened_tag_lookup] = true
# Precious::App.settings.wiki_options[:global_tag_lookup] = true
Precious::App.settings.wiki_options[:lenient_tag_lookup] = true
Precious::App.settings.wiki_options[:css] = true
Precious::App.settings.wiki_options[:allow_uploads] = "page"
```

first

**Comment by bartkamphorst** [comment] 2020-03-27 14:36
To my knowledge:

> are ALL commandline options configurable also via config.rb?

Yes.

> are some options ONLY available in config.rb 

Yes. Example: `Precious::App.settings.wiki_options[:sidebar] = :left` does not have a corresponding flag.

> or ONLY available as command-line options?

No.

**Comment by dometto** [comment] 2020-03-27 14:37
> Precious::App.settings.wiki_options[:lenient_tag_lookup] = true

This will not work. :) See here: https://github.com/gollum/gollum/wiki/5.0-release-notes#compatibility-option

**Comment by petrkalina** [comment] 2020-03-27 14:40
> > Precious::App.settings.wiki_options[:lenient_tag_lookup] = true
> 
> This will not work. :) See here: https://github.com/gollum/gollum/wiki/5.0-release-notes#compatibility-option

ok, I understand it, but you are then not 100% correct when you say

>or ONLY available as command-line options?
No.

as this seems to be command-line-only option :-)!

**Comment by bartkamphorst** [comment] 2020-03-27 14:43
Fair enough! 😅

**Comment by petrkalina** [comment] 2020-03-27 14:50
Verified .. works:

<img width="543" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/77768329-9fd65e00-7042-11ea-9740-3f4e2e3e9ee5.png">

**Comment by dometto** [comment] 2020-03-27 14:55
Thanks for the reporting!

**Closed by dometto** 2020-03-27 14:55 UTC
