### ISSUE TITLE
Can't use gollum with bare repo that's been pushed-to

### ISSUE THREAD

**Issue by mozai** [gollum/gollum#1020] opened 2015-06-08 20:04 UTC
Steps to reproduce:

    $ mkdir /var/www/html/gollum
    $ cd /var/www/html/gollum
    $ git init --bare # "Initialized empty Git repository in /var/www/html/gollum/"
    $ cd /tmp/
    $ git clone /var/www/html/gollum # "Cloning into 'gollum'. warning: you appear to have cloned an empty repository."
    $ cd gollum
    $ echo "# Test" > Home.md
    $ echo add Home.md
    $ git commit -m "first test" Home.md
    $ git push
    $ cd /var/www/html/gollum
    $ gollum --bare

Expected outcome:
- pointing a browser at http://localhost:4567 will show the "Test" document

Seen outcome:
- Grit::InvalidGitRepositoryError at /Home /var/www/html/gollum file: repo.rb location: initialize line: 52

I'm able to run gollum with a checked-out repo, but I'd rather be running gollum with something I can push to instead of having a cronjob pull every N seconds to get updates.

**Comment by mozai** [comment] 2015-06-08 20:23
Update:

    $ gem install --pre gollum-rugged_adapter
    $ gollum --adapter rugged  # no need for --base

I was able to see the "Test" document.  Maybe something to do with the (default) grit adapter, even when I'm using the "--bare" switch?

**Comment by bartkamphorst** [comment] 2015-06-09 12:39
Strange behavior. Thanks for reporting this @mozai . I don't have time to investigate this at the moment, are you okay working with the rugged_adapter for now? Ultimately we are moving towards using the rugged adapter as the default.

**Comment by SkyCrawl** [comment] 2015-06-09 21:57
@mozai 
> Expected outcome:
>      pointing a browser at http://localhost:4567 will show the "Test" document
> Seen outcome:
>      Grit::InvalidGitRepositoryError at /Home /var/www/html/gollum file: repo.rb location: initialize line: 52

I think the problem is the last `cd /var/www/html/gollum`, just before `gollum --bare`. Like this, you're telling Gollum to use a "server-side" git repository which is quite different from the "client-side" repository where all the files nicely reside in the filesystem for everyone to see.

If you removed the `cd /var/www/html/gollum` call, it should work alright. Also, in case you didn't know - you don't have to push for Gollum to render your pages. Commit alone is fine :).

> I'm able to run gollum with a checked-out repo, but I'd rather be running gollum with something I can push to instead of having a cronjob pull every N seconds to get updates.

I'm sorry but I don't really understand what you're trying to say... Did you mean that you need Gollum to work with a repository with more contributors or local copies (each being used locally and to push changes)?

**Comment by mozai** [comment] 2015-06-10 05:43
> remove cd /path/to/repo before starting gollum
No. If I make a repo in directory A, and tell gollum to read from directory B, of course gollum will fail.

> you don't have to push for gollum to render your pages. Commit alone is fine.
No.  Gollum, using repository A, won't know about commits made to repository B unless I push from B to A.

> Did you mean that you would like for gollum to be able to work with [a bare repository]
That really should've been obvious with my use of the '--bare' command-line switch, and the 'git push' step in my problem description, and how I say "with bare repo" in the issue's subject line.

**Comment by SkyCrawl** [comment] 2015-06-10 09:47
Ah, didn't know that "bare" repositories are actually the ones I was talking about (server-side) and that Gollum can handle them. You learn something new every day :). Now everything makes sense, except for the error... Sorry for the confusion.

**Comment by bartkamphorst** [comment] 2015-06-11 14:40
@mozai Quick update: I was able to reproduce the error (ruby 2.1.1, gollum 4.0.0, gollum-lib 4.0.3, gollum-grit_adapter 1.0.0). I can also access the bare repo just fine using grit in irb:
```ruby 
require 'grit'
include Grit
r = Repo.new('/tmp/baretmp', :is_bare => true)
r.commits.first.tree.blobs.first.data
 => "# Test\n" 
```
So it would seem as though gollum's `--bare` flag isn't doing its job. To be continued.

**Comment by bartkamphorst** [comment] 2015-06-12 09:48
@mozai As a workaround, you could rename your bare repository to `/var/www/html/gollum.git`. This naming format is a git convention, and it seems that grit honours the convention (with this change the test page should render normally, with or without the `--bare` flag). So basically the real issue seems to come down to the `--bare` flag not being passed properly.

**Comment by dometto** [comment] 2015-12-30 22:22
If grit is ignoring the `is_bare` option anyway, should we just remove the `--bare` flag from gollum completely? (The other adapters should more or less intelligently test whether the repo is bare based on the presence of a `.git` directory.)

Anyway it seems this can be closed, if @mozai is ok with using @bartkamphorst's workaround? Sorry for the confusing `--bare` flag, but `grit` is sometimes... unpredictable. :)

**Comment by dometto** [comment] 2015-12-30 22:50
Ah, gotcha. The problem is in the grit adapter, which at one point intializes a new `Repo`, and does so without respecting the `--bare` setting. See [here](https://github.com/gollum/grit_adapter/blob/master/lib/grit_adapter/git_layer_grit.rb#L226).

**Closed** 2016-03-13 16:58 UTC
Labels: bug
