### ISSUE TITLE
ReST anonymous hyperlinks don't work.

### ISSUE THREAD

**Issue by davedash** [gollum/gollum#642] opened 2013-02-26 23:21 UTC
```ReST
See `the web site`__.

__ http://www.python.org

See `the web site`__.

.. __: http://www.python.org

```

See
http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#anonymous-hyperlinks

Tested on GHE11.10.300

**Comment by dometto** [comment] 2015-01-04 14:42
Can't reproduce on the latest version gollum/gollum-lib (probably fixed in a newer version of github-markup).

**Closed by dometto** 2015-01-04 14:42 UTC
Labels: bug
