### ISSUE TITLE
If i call a page Terms.md and use an nginx reverse proxy then navigating to this page thinks i'm trying to edit/create a new page

### ISSUE THREAD

**Issue by jb2cool** [gollum/gollum#1371] opened 2019-02-25 12:14 UTC
I have a handful of pages in my Wiki, currently only about 6 or so and am using the GlobalTOC in the sidebar (Thanks to Bart helping me out with that) but i have now found a very weird bug.

I need to use nginx in front of Gollum in order to serve pages on port 80 and when i do this my Terms.md page stops working, everything else is fine it's just Terms.md. It i call my pae anything other than Terms it works again and then if i call a different page Terms that other page stops working. It thinks you are trying to edit the page when you click on it.

Have you ever seen anything like this before?

**Comment by bartkamphorst** [comment] 2019-02-25 14:44
For clarification: you're not seeing this behavior without nginx reverse proxy, correct?

**Comment by jb2cool** [comment] 2019-02-25 15:54
Correct, if I use hostname:4567 and no nginx it was all working just fine. If I put nginx in front of it (so that I can use a standard port 80) then hostname:80 does this weird thing but ip_address:80 or even a separate hostname wiki:80 in the same scenario works just fine.

ip_address:80 (with nginx) - fine
ip_address:4567 - fine
hostname:80 (with nginx) - weird
hostname:4567 - fine
alternate_dns:80 (with nginx) - fine
alternate_dns_4567 - fine

For my particular use-case this is not actually an issue as I was going to put a separate DNS alias in front of it anyway e.g. wiki.company.com and I only just realised this was working ok.

**Comment by bartkamphorst** [comment] 2019-02-26 06:33
Thanks for clarifying. I haven't seen anyone else mention this, but then again the issue seems to originate with nginx. I would recommend going through the logs to see what is actually happening when the Terms.md page is requested. I'd be interested to hear your findings if you do figure it out, but since it doesn't seem to be an issue with gollum itself, I'm closing the issue.

**Closed by bartkamphorst** 2019-02-26 06:33 UTC

**Comment by zeue** [comment] 2019-11-20 17:02
@jb2cool did you ever find a fix for this? I am having the same problem and there's nothing in the logs indicating what the problem is.

**Comment by jb2cool** [comment] 2019-12-02 13:15
I think got around this by using an alternate DNS alias but I have just tried it using the server hostname and can't replicate the issue any more.
