### ISSUE TITLE
Asciidoc: Failed to render page

### ISSUE THREAD

**Issue by d-nnis** [gollum/gollum#1199] opened 2017-03-07 16:01 UTC
After installation of gollum and optional markup-renderer
> apt-get install build-essential make ruby rubygems ruby-dev libicu-dev zlib1g-dev libicu-dev
> gem install gollum wikicloth asciidoctor

(On Debian Jessie: ruby 2.1.5p273 gollum-4.0.1 asciidoctor-1.5.5)
I encounter the following error on the local running server:
> Failed to render page: undefined method `unique_id_start_index=' for Asciidoctor::Compliance:Module

The server-console doesn't show any related error.
Running with the suggested configuration (config.rb) https://github.com/gollum/gollum/wiki/Formats-and-extensions did not change the error.
Rendering of mediawiki and markdown works flawlessly.

Is this a bug?

**Comment by dometto** [comment] 2017-03-09 14:31
It may be an `asciidoctor` compatbility issue, or even a bug in `asciidoctor` itself, since `unique_id_start_index` does not seem to be called from either `gollum` or `gollum-lib`. Have you tried with a different (lower) version of `asciidoctor`?

**Comment by d-nnis** [comment] 2017-03-10 12:49
Hi @dometto 
I just re-installed gollum with Asciidoctor 1.5.0
> gem install asciidoctor -v 1.5.0

And it works! :+1: 

I will issue this problem with the asciidoctor-team @asciidoctor

---
However, I have tried to internally link the wiki-pages with asciidoc. This does not work. I guess this is because the asciidoc-parser checks for different markup elements.
What _does_ work is the relative linking to internal pages like so:
> * Sample1 /Home[Link with relative URL]
> * Sample2 link:Home[]

Applying macros does work in asciidoc-context, too:
> <<AllPages()>>
> <<GlobalTOC()>>

Is there a macro that can link to an internal page - as an alternative to default internal links?
Thx so far!  :airplane:

**Comment by dometto** [comment] 2017-03-10 13:38
Can you give me an example of the kind of links you want to make that's *not* working? I believe gollum-style tags should also function in asciidoc mode. See https://github.com/gollum/gollum/wiki#tags for the syntax.

**Comment by d-nnis** [comment] 2017-03-10 17:59
Okay, of course.
Here is the asciidoc-syntax

> == Fun with AsciiDoc
> === Link Arsenal
> . Links with adoc-format
> .. Link link:/Home[Link with relative URL]
> .. Link2 link:Home[]
> . Links with Gollum-format
> .. Sample1 [[_TOC_]]
> .. Sample2 \[[_TOC_]]\
> .. Sample3 \ [[_TOC_]]
> .. Sample4 +[[_TOC_]]+
> .. Sample5 '[[_TOC_]]
> .. Sample6 +[[Home]]+
> .. Sample7 '[[Home]]
> . Macros
> .. Allpages <<AllPages()>>
> .. GlobalTOC <<GlobalTOC()>>
> 
> == Chapter2
> === Further Further

And see attached the rendered outcome as PDF
[secondAsciidocPage.pdf](https://github.com/gollum/gollum/files/834725/secondAsciidocPage.pdf)

**Comment by d-nnis** [comment] 2017-03-10 18:03
The weird thing about Sample4 is that it somehow works, with some funny chars though.
The same format does not work with an internal link to an existing page (Sample7).

**Comment by mojavelinux** [comment] 2017-03-10 21:47
Asciidoctor is called via github-markup. See: https://github.com/github/markup/blob/5ded14c01037b09dadb8940da4224930c78cde7c/lib/github/markups.rb#L30-L33

**Comment by mojavelinux** [comment] 2017-03-10 21:52
The flag was introduced in Asciidoctor 1.5.2, so it definitely shouldn't work with Asciidoctor 1.5.0. Chances are, you had an old version of Asciidoctor laying around and somehow you managed to upgrade it even though you thought you were installing 1.5.0. Anyway, the minimum requirement to use github-markup should be 1.5.2, but you should be using 1.5.5 anyway.

**Comment by d-nnis** [comment] 2017-03-10 22:27
@dometto: @mojavelinux is right, I somehow have Version 1.5.5 of asciidoctor running after all. The bug I encountered must have happened because I had an older version previously.

**Comment by bartkamphorst** [comment] 2017-03-13 17:02
@d-nnis Thanks for letting us know; I'm glad the issue is resolved (closing the issue).

**Closed by bartkamphorst** 2017-03-13 17:02 UTC
