### ISSUE TITLE
Searching should be done case-insensitive

### ISSUE THREAD

**Issue by techwiz24** [gollum/gollum#934] opened 2015-01-09 20:28 UTC
Currently, when you search for a page using the search bar, only matches between the exact case are returned. For example, searching for `load balancer` won't return any results, but `Load Balancer` will.

**Comment by dometto** [comment] 2015-01-10 16:21
Strange, I can't reproduce this. And the `grit_adapter` should be passing the `-i` flag to `git grep`: https://github.com/gollum/grit_adapter/blob/master/lib/grit_adapter/git_layer_grit.rb#L142
```
$ gem list gollum

*** LOCAL GEMS ***

gollum (3.1.1)
gollum-grit_adapter (0.1.1)
gollum-lib (4.0.1)
```

**Comment by dometto** [comment] 2015-01-11 18:58
@techwiz24 any idea what could be the discrepancy between our setups?

**Comment by techwiz24** [comment] 2015-01-11 21:02
@dometto I have no idea. Unfortunately I can't publish the repository I noticed this in, so i'm going to try and get a repository/environment created in which I can reproduce the issue so you can take a look at it. I did poke around in the grit adapter file you mentioned and saw the case insensitive flag like you said, which is why I thought it was strange that we were having this problem.

On a side note: is the `grit` adapter still the default? I thought I heard mention of gollum moving away from that.

**Comment by dometto** [comment] 2015-01-11 22:34
Thanks, that would be helpful! 

grit is still the default adapter, but it's true we want to move to the [rugged_adapter] (https://github.com/gollum/rugged_adapter) in the future (it should solve a lot of issues, and comes with great performance gains) . It still needs more extensive testing and refactoring, but development is going quite fast. However, the intention is for it to be a drop-in replacement, updating the gollum-lib gem should be all that's necessary to get it to work when the time comes. Any feedback on the rugged_adapter is very welcome!

**Comment by dometto** [comment] 2015-01-16 20:01
@techwiz24, any luck coming up with a reproduceable case? If this needs any fixing, I'd like to get the fix in for the next patch-level release of gollum-lib (so all search-related bugs are solved there).

**Comment by techwiz24** [comment] 2015-01-16 20:18
Sorry, classes just started so I haven't had much time to work on this, I
should be able to get something together this weekend though!

Nathan Lowe

**Comment by techwiz24** [comment] 2015-01-18 20:38
Well...It appears something is broken with the search, sometimes. Chrome returns 

```
Internal Server Error

undefined method `join' for #<String:0x007fc0c0686400>
WEBrick/1.3.1 (Ruby/1.9.3/2013-11-22) at ***.***.***.*** (IP Address removed)
```

and this is the snippit from the log:
```
NoMethodError - undefined method `nonzero?' for nil:NilClass:
	/var/lib/gems/1.9.1/gems/gollum-3.1.1/lib/gollum/app.rb:430:in `block (2 levels) in <class:App>'
	/var/lib/gems/1.9.1/gems/gollum-3.1.1/lib/gollum/app.rb:430:in `sort'
	/var/lib/gems/1.9.1/gems/gollum-3.1.1/lib/gollum/app.rb:430:in `block in <class:App>'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/var/lib/gems/1.9.1/gems/gollum-3.1.1/lib/gollum/editing_auth.rb:13:in `call'
	/var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/nulllogger.rb:9:in `call'
	/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/nulllogger.rb:9:in `call'
	/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
	/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
	/usr/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
	/usr/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
	/usr/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
[2015-01-18 15:33:48] ERROR NoMethodError: undefined method `join' for #<String:0x007fc0c0686400>
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:37:in `rescue in call'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
	/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
	/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
	/usr/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
	/usr/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
	/usr/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
****.neo.res.rr.com - - [18/Jan/2015:15:33:48 EST] "GET /search?q=Cake HTTP/1.1" 500 345
```

I've tested this on a fresh install of gollum on a VM just to make sure it's not my environment. So far, I haven't been able to replicate the original reported issue. The only other thing I can think of is that when we experienced this we were using IE (Which I don't have available with me at home), but I highly doubt that is the problem. I'm going to close this issue because I can't reproduce it. If I stumble upon this again and figure out what is causing it, i'll re-open the issue. Sorry for the delay!

**Comment by techwiz24** [comment] 2015-01-19 18:08
**Breakthrough**! This appears to be caused by the presence of custom macros. If a page is initially committed with a custom macro in it, it will not be returned in the search results unless the page title exactly matches. If the custom macro directive is removed, the page committed, added again and the page committed a second time, the page becomes searchable no matter the case of the search terms.

I have no idea why this is occurring, this is what one of the macros looks like:

```ruby
#	under_construction.rb - Conversion of the Admon-Caution snippit from screwturn
#	Creator: Nathan Lowe	Last Edit: 2014-12-05
#
#	Signature: <<UnderConstruction()>>
#
#	Renders a notification that the page is under construction and may change frequently

class Gollum::Macro::UnderConstruction < Gollum::Macro
	def render(*args)
		"<table 
		 style='margin: 0px 10%;   /* 10% = Will not overlap with other elements */
			 border: 1px solid #aaa; 
			 border-left: 10px solid #1e90ff;    /* Blue */
			 padding: 5px;
			 border-collapse: initial;'
			 >
		 <tr>
		 <td style='border: none; 
			 padding: 2px 0 2px 0.9em;    /* 0.9em left, 0px right */
			 text-align: center;'>
		 <img src='/uploads/hgm_images/under_construction.png' />
		 </td>
		 <td style='border: none; 
			 padding: 0.25em 0.9em;       /* 0.9em left/right */ '>
		 This article or section <b>is in the middle of an expansion or major revamping</b>. You are welcome to assist in its construction by editing it as well. 

		 <small>If this article has not been edited in several days, please remove this snippet.</small>
		 </td>
		 </tr>
		 </table>"
	end
end
```

I'm going to do some more testing and should hopefully have a test repository uploaded on GitHub sometime later today or tomorrow.

**Comment by dometto** [comment] 2015-01-19 18:50
Nice catch @techwiz24! Really weird bug, no idea what could be causing this. I'll take a look if you post a testrepo somewhere.

**Comment by dometto** [comment] 2015-01-19 18:54
Oh, btw, is the query your searching part of the macro's output? Then it really shouldn't find anything, since the search only greps through a page's raw content.

**Comment by techwiz24** [comment] 2015-01-19 18:59
No, it shouldn't be. Off the top of my head we only noticed his when
searching for content that should be in the page already

Nathan Lowe

**Comment by techwiz24** [comment] 2015-01-19 21:06
Then again, maybe it's not the macros. I haven't been able to reproduce this in a new repository. I'm leaning towards the issue being the files initially created and committed inside of windows, because as soon as I introduce a change (any change via the web interface, be it a newline or html comment), the page and **all pages that should be returned for that search term** become searchable without having to match the exact case.

I'm not really sure where to go from here...I'm going to try and rig my conversion script that generated the initial commit for our new wiki to setup a test environment, but I'm guessing this is going to be a one-off issue in the environment that I'm using.

If there's anything specific you'd like me to look at, lt me know.

**Comment by dometto** [comment] 2015-01-19 21:15
Then maybe it's some kind of weird encoding issue (although I've never seen that become an issue with case sensitivity)? If you think it's somehow specific to your setup I'll close this, but feel free to reopen if you want us to take a look at anything. Good luck!

**Comment by techwiz24** [comment] 2015-01-19 21:16
**Bingo**. It's windows' fault. Creating a file with powershell and then committing and pushing it to an ubuntu box causes no results to be returned when searching for `koala test`:

```powershell
@"
<<Foobar()>>

![](/uploads/koala.jpg)

Koala koala Koala koala
"@ | Out-File 'Koala-Test.md'

git init
git add --all .
git commit -m "Initial Commit"
git push testing master
```

Introducing an HTML comment via the web interface fixes this issue. I have no idea how you'd go about fixing this in gollum. I should have a test repo created shortly.

**Comment by dometto** [comment] 2015-01-19 21:18
Ah, so it's not even a case-issue at all? Then it's bound to be an encoding thing. Perhaps this will be resolved when using the rugged adapter?

**Comment by techwiz24** [comment] 2015-01-19 21:39
I don't think so. Looking at the diff, it looks like the line ending style is different, Maybe that's throwing off `grep` (or whatever you guys use for searching)? It could also be an encoding thing (Looks like `UCS-2 LE` in the broken commit and `Windows-1252` in the fixed one). I guess I'll revisit this when the adapter changes. Thanks for the help!

**Comment by techwiz24** [comment] 2015-04-06 18:59
@dometto I tried it with the rugged adapter in 3.1.3 and it's **worse**. Still only returning case-sensitive results, but the rugged adapter includes pages that don't have any matches at all (They show a `0` in parenthesis next to the result)!

**Comment by dometto** [comment] 2015-04-06 19:21
> (They show a 0 in parenthesis next to the result)!
Aren't those pages who's *title* matches the query?

**Comment by techwiz24** [comment] 2015-04-06 19:58
@dometto Not that I can see, unless gollum speaks a different dialect:

![image](https://cloud.githubusercontent.com/assets/794251/7011248/8ba0ead8-dc75-11e4-9886-9923a9d76bc4.png)

The first few results (all uploaded screenshots) are expected. Gollum decides to include ~30 other pages, none of which have the search term (***In this case, `citrix`***) in the body or title.

**Comment by dometto** [comment] 2015-04-06 20:04
That does seem like a bit of a problem with the [grep implementation](https://github.com/gollum/rugged_adapter/blob/master/lib/rugged_adapter/git_layer_rugged.rb#L161-L178) :)
(Sorry about this, as you've probably seen the rugged adapter is still in beta, so thanks for reporting!)

**Comment by bartkamphorst** [comment] 2015-04-06 20:08
Maybe open an issue there too?

**Comment by techwiz24** [comment] 2015-04-06 20:09
That's what I was just going to ask. The original issue was caused by the file encoding between windows and linux in my environment as far as I can tell. @dometto  and @bartkamphorst, would you prefer I open an issue with the adapter project itself instead?

**Comment by techwiz24** [comment] 2015-04-06 20:12
Speaking of original issue, I think it's only matching the file names themselves (case **sensitively**) in my repository and skipping the majority of the files because `git` (and `grep`) thinks they're binary files and thus skips them unless the file name matches (as far as I can tell, there's no way to issue a `git ls-files` case-insensitively). At this point, I'm starting to doubt whether or not this is technically an issue with gollum and more of an issue with supported environments.

**Comment by dometto** [comment] 2015-04-06 20:20
Yes, git [marks files containing a certain amount of unicode characters as binary](https://github.com/gollum/rugged_adapter/issues/3), and then the search ignores them. That could be what caused the original issue. We will probably remove the ignoring of binary files off when we move to the rugged adapter (because performance should be better). So I guess I'll close this again, and yes, please open the new issue under the rugged_adapter project.

**Closed by dometto** 2015-04-06 20:20 UTC
