### ISSUE TITLE
Upgrade from 5.1.1 to 5.2.3: custom css broken and over zealous tables

### ISSUE THREAD

**Issue by Se6** [gollum/gollum#1740] opened 2021-07-12 20:33 UTC
Just upgraded today from 5.1.1 to 5.2.3.

Unfortunately custom css does not work nicely with it.
The example in the wiki for example with a custom css which reads:
```
.container-lg {
  max-width: 90%;
}

#sidebar-content {
  width: 17%;
}
```
does not behave properly, it results in the content of the sidebar displayed on a single column!

Also, with the newer markdown lib, each line which contains a  vertical bar character is now treated as a table!

Seb

**Comment by benjaminwil** [comment] 2021-07-12 20:56
Thanks. We likely need to change that custom CSS example. I can figure out what the equivalent should be. 

Could you provide an example of the issue you are seeing with tables?

**Comment by Se6** [comment] 2021-07-12 21:02
That would be great if you could figure out an updated CSS example!
As for the tables, if you have any line which as a vertical bar, then it formats the line as a table now!
For examples, I have some lines like:
```
 - Music: [[guitar]] | [[harmonica]] | [[piano]]
 ```
 And now they are formatted as a table. Before you got a table if you had at least two lines with the same number of vertical lines.
 Thanks so much for your very prompt replying!

**Comment by benjaminwil** [comment] 2021-07-13 04:41
I updated the example in the wiki. Thanks for pointing out the error. If you use the `--css` feature and have any other simple examples to add, please do add one or two to the wiki.

**Comment by benjaminwil** [comment] 2021-07-13 04:48
```
 - Music: [[guitar]] | [[harmonica]] | [[piano]]
 ```
 
I was able to reproduce this issue. I am a little bit surprised that this is a _new_ issue, and am not exactly sure what the source of the issue is. I don't think Kramdown (the default Markdown rendering engine) has changed table rendering.
 
I do not think this is a bug in Gollum, but I am not 100% sure yet.

In the meantime, you can definitely escape pipe characters to de-tableize your text:

```
 - Music: [[guitar]] \| [[harmonica]] \| [[piano]]
 ```
 
 I realize that suggestion may not be satisfying if you use this pattern a lot. My apologies.
 
 You may also want to try installing another Markdown rendering engine that Gollum supports.

**Comment by Se6** [comment] 2021-07-13 05:54
Thank you so much !
For css, that solves it indeed. 
For the tables, I will do some global search and replace, thanks for suggesting a solution.
Very happy long time Gollum user!

**Comment by benjaminwil** [comment] 2021-07-15 02:55
Here is what I see when I use the custom CSS from the example:

```
.container-lg {
  max-width: 90%;
}

#wiki-sidebar {
  width: 17%;
}
```

<img width="1070" alt="Screen Shot 2021-07-14 at 7 53 20 PM" src="https://user-images.githubusercontent.com/883581/125720540-625cbc23-708a-44fb-9d98-2a33476f31ef.png">

Is this not what you expect to see? Or are you seeing something else?

**Comment by benjaminwil** [comment] 2021-07-15 02:58
```
pp Kramdown::Document.new("guitar | bass | drums").to_html
"<table>\n" +
"  <tbody>\n" +
"    <tr>\n" +
"      <td>guitar</td>\n" +
"      <td>bass</td>\n" +
"      <td>drums</td>\n" +
"    </tr>\n" +
"  </tbody>\n" +
"</table>\n"
```

I did a test outside of Gollum to see if Kramdown would render an HTML table with `a | single | line | with | pipes`. It does!

So this is technically an issue with Kramdown not Gollum. But it's not clear to me whether this is the expected behaviour or not. I would agree with you that this text should not render a table. But this is out of our hands, unless we file a bug with Kramdown.

**Comment by Se6** [comment] 2021-07-15 07:22
My fault, the CSS works indeed. I was confused because it works differently from before.  Even putting a tiny percentage for the side bar does not make it very narrow and 97% for the content does not use all the width available. Could you give me a pointer to where to find the different CSS names and meaning that I can adjust?
I agree, it is a Krandown issue.
Thanks a lot Benjamin for your superb user support!

**Comment by dometto** [comment] 2021-07-15 08:40
@Se6 there's always the possibility of installing a different supported markdown renderer (e.g. `CommonMark`) if you don't like `kramdown`'s behavior!

**Comment by bartkamphorst** [comment] 2021-07-15 09:15
>  Thanks a lot Benjamin for your superb user support!

I can only second that, @benjaminwil !

**Comment by Se6** [comment] 2021-07-15 13:28
I don't know what is happening but I still have an issue with the sidebar. 
Even with the following custom CSS:
```
.container-lg {
  max-width: 90%;
}
```
The sidebar is very narrow and there is only one column of letters!

**Comment by Se6** [comment] 2021-07-15 16:59
There is something really strange happening... made many trials, sometimes the very narrow side bar appears... stop and start again, and it is fine. Odd. As if there were some caching somewhere.

**Comment by benjaminwil** [comment] 2021-07-15 17:07
I am not exactly sure what you wish to accomplish. I'm sorry if my changes broke your custom CSS.

Unfortunately, custom CSS features will always be finnicky as HTML changes over time in a code base.

> Could you give me a pointer to where to find the different CSS names and meaning that I can adjust?

I would recommend getting comfortable with your browser's developer tools if you aren't already.

<img width="1005" alt="Screen Shot 2021-07-15 at 10 02 53 AM" src="https://user-images.githubusercontent.com/883581/125828159-611df61e-5488-4712-9d05-3cea0cdfaced.png">

See in my screenshot:
- The HTML as rendered by Gollum on the left.
- A list of CSS styles on the right.
- CSS rules I've added in-browser as a test (inside of the circle).

> There is something really strange happening... made many trials, sometimes the very narrow side bar appears... stop and start again, and it is fine. Odd. As if there were some caching somewhere.

I don't have enough information about how you're running the Gollum process to help. But it may just be a matter of needing to restart the Gollum process. Note also that `custom.css` changes need to be committed before they take affect, and it's possible what you're seeing is a result of your git history being changed or something like that.

**Comment by benjaminwil** [comment] 2021-07-15 17:08
I will close this since no changes to the Gollum codebase will be made for these issues.

Feel free to keep posting in this thread though.

**Closed by benjaminwil** 2021-07-15 17:08 UTC

**Comment by Se6** [comment] 2021-07-15 18:13
Thanks a lot for everything Benjamin.
Sure, I always commit the changes to _Sidebar.md in order to be taken into account.
