### ISSUE TITLE
unable to link files in gollum

### ISSUE THREAD

**Issue by trenkert** [gollum/gollum#1270] opened 2017-12-06 09:26 UTC
every file link, either absolute or relative becomes an empty link. clicking on it prompts gollum to create a new page.

File links have the format of

[[test_a/test_b/test_c.pdf]]

what is causing this?

**Comment by bartkamphorst** [comment] 2017-12-13 16:26
What's your setup in terms of operating system, gem versions, etc.?

**Comment by trenkert** [comment] 2017-12-13 16:31
Debian testing (SolydX 10)

ruby 2.3.5p376 

gems 2.5.2.1

**Comment by dometto** [comment] 2018-01-17 17:07
I'm guessing you're using gollum from debian's repository. That is most likely a more than outdated version. Try to install the latest version (using `gem install`, see the wiki) and reopen this issue if the problem persists.

**Comment by trenkert** [comment] 2018-01-17 17:24
I am using the current gem version of gollum and never had the gollum debian package installed

**Comment by dometto** [comment] 2018-01-17 18:16
I can reproduce this when one important constraint is present: the directory containing the file does not contain a wiki page (or presumably, another directory containing a wiki page). As soon as I commit a valid page (e.g. a `.md` file) to the directory, the link works. @trenkert can you confirm that this is also the case in your repository?

There is an additional issue (arguably): PDF files are apparently considered to be images, and they display as a broken image in at least some browsers. To work around this just use a named link: [[Link|bla.pdf]].

**Comment by dometto** [comment] 2018-01-17 18:16
@bartkamphorst I believe we have something similar before (files not being detected in directories that contain no pages), but I'm not sure?

**Comment by dometto** [comment] 2018-01-17 18:33
@trenkert sorry, I can't reproduce this issue. Please note: files have to be committed to the repository in order to show up in gollum! That's often overlooked. Might it be that you forgot to commit them? If not, please point us to an example repository where this issue occurs.

**Closed** 2018-01-19 23:23 UTC

**Comment by trenkert** [comment] 2018-04-07 18:05
@dometto thank you, I had forgotten to commit the files to the repo. it would be great if gollum could have a "link to file" function where a link to a file is inserted and the file is automatically committed.
