### ISSUE TITLE
Unable to test on gollum 5.x

### ISSUE THREAD

**Issue by jessebett** [gollum/gollum#1403] opened 2019-08-26 19:06 UTC
Thanks @dometto for your response in the other issue. I was considering `gollum` as a way to serve my vimwiki (with markdown syntax). Since both use markdown syntax I had hoped this would be straightforward, even on version 4.x. 

However, as described in [this post on integrating vimwiki and gollum](https://davidyat.es/2017/09/01/vimwiki-plus-gollum/) there is some issue with allowing `.wiki` files to be read by gollum as `.md`. I don't know if this will still be an issue in `5.x`. In any case I ignored the issue/patch in that blog and just allowed my vimwiki files to be named `.md` to test gollum. This worked to test 4.x, but ran into the mathjax bug from #1390.

I tried to test on 5.x but now every time I attempt to access an existing page, or even create new ones, gollum serves me the create new page screen.

here is my version:
```
gollum --versions
Gollum 5.0.1b
Running on: x86_64-darwin18 with Ruby version 2.6.3
Using:
gollum-grit_adapter 1.0.1
gollum-lib 5.0.a.4
With the following renderers:
kramdown 2.1.0
```

e.g.
Inside my `Home.md` I have a vimwiki created link
```
# Test Home
*[test page](link/to/page)
```
Inside `link/to/page.md` there is a test page in markdown.

When I run `gollum` I see my test homepage. When I click the `test page` link I am not taken to my test markdown page, but instead I am taken to a create new page.

I thought this was an issue with explicit file extensions, and manually edited the link to contain the explicit extension:
```
# Test Home
*[test page](link/to/page.md)
```

However, now when I run gollum and click this link in the browser it opens a download window asking to save file `page.md`.

As such I am unable to test whether the mathjax bug of #1390 is still an issue in `5.x`.

**Comment by bartkamphorst** [comment] 2019-08-27 06:56
@jessebett Thanks for the thorough issue report, this is exactly the kind of info we need in order to troubleshoot the migration process from 4.x to 5.x. To begin, could you drop the gollum-grit_adapter in favor of the new gollum-rugged_adapter?

**Comment by dometto** [comment] 2019-08-28 15:06
> To begin, could you drop the gollum-grit_adapter in favor of the new gollum-rugged_adapter?

To clarify: if you're properly using bundle, you should be able to `bundle exec gollum --adapter rugged`

**Comment by dometto** [comment] 2019-08-28 15:12
I can't reproduce the problem without the rugged adapter either. @jamesdabbs, did you notice that filenames are case sensitive on 5.x? See [here](https://github.com/gollum/gollum/wiki/5.0-release-notes#filename-handling).

**Comment by jessebett** [comment] 2019-08-30 20:31
can you point me to the install instructions for the rugged adapter? If I run `bundel exec gollum --adapter rugged ~/path/to/wiki` I get
```
dyld: lazy symbol binding failed: Symbol not found: _libiconv_open
  Referenced from: /Users/jesse/.rvm/gems/ruby-2.6.3/gems/rugged-0.28.3.1/lib/rugged/rugged.bundle
  Expected in: flat namespace

dyld: Symbol not found: _libiconv_open
  Referenced from: /Users/jesse/.rvm/gems/ruby-2.6.3/gems/rugged-0.28.3.1/lib/rugged/rugged.bundle
  Expected in: flat namespace

[1]    48601 abort
```

**Comment by dometto** [comment] 2019-08-31 14:37
Looks like you have the rugged adapter but something has gone wrong with your installation of rugged itself. See whether `gem install rugged` succeeds, and whether you can then `require 'rugged'` in `irb` or a ruby script.

**Comment by dometto** [comment] 2019-09-09 23:12
@jessebett any progress?

**Comment by jessebett** [comment] 2019-09-11 19:12
Sorry, I won't have a chance to look at this for a bit now that academic term has started. I will report back once I've tested this.

**Comment by dometto** [comment] 2019-09-11 21:24
Ok! Like I said, from the looks of the error message, I would think this is actually a problem with installing `rugged` (would still be glad to help out if I can). I'll close this for now, but if/when you try again, feel free to drop a message or reopen this issue.

**Closed by dometto** 2019-09-11 21:24 UTC
