### ISSUE TITLE
Mistreatment of line breaks in 5.x

### ISSUE THREAD

**Issue by jstolarek** [gollum/gollum#1503] opened 2020-03-26 19:48 UTC
Consider the following contents of an `.md` file:

```
foo
bar
```

On 4.x it renders correctly as a single paragraph of text:

```html
<p>foo bar</p>
```

However, 5.x inserts a line break after "foo":

```html
<p>foo <br />
bar</p>
```

which is against Markdown specification.

On the 4.x branch I am using `github-markdown` gem for rendering (installed with `sudo gem install github-markdown`). I honestly don't know whether that gem is also being used when I run gollum 5.x from a local copy of a repository. I start gollum 5.x by running the following command from gollum repo directory:

```
bundle exec bin/gollum --css --mathjax --h1-title --port 1234 --config /path/to/config.rb /path/to/wiki/repo
```

**Comment by bartkamphorst** [comment] 2020-03-26 19:52
@jstolarek Can you post the output of `bundle exec bin/gollum --versions`?

**Comment by jstolarek** [comment] 2020-03-26 19:56
```
$ bundle exec bin/gollum --versions
Gollum 5.0.1b
Running on: x86_64-linux-gnu with Ruby version 2.5.5
Using:
rugged 0.99.0
gollum-rugged_adapter 0.99.4
gollum-lib 5.0.a.4
Markdown rendering gem: kramdown
Other renderering gems:
none
```

**Comment by bartkamphorst** [comment] 2020-03-26 20:04
Thanks. So you're rendering Markdown with `kramdown`, not `github-markdown`. To use `github-markdown`, add `github-markdown` to your `Gemfile` in the local copy of 5.x and run `bundle install`. If you then run `bundle exec bin/gollum --versions` again, you should see `github-markdown` listed as your Markdown rendering gem.

To the issue at hand: it looks like this is not an issue with gollum, but with Kramdown:
```ruby
$> Kramdown::Document.new("foo\nbar").to_html
 => "<p>foo\nbar</p>\n" 
```

**Comment by bartkamphorst** [comment] 2020-03-26 20:08
Interestingly, this is from the kramdown [documentation](https://kramdown.gettalong.org/syntax.html):

> Paragraphs are the most used block-level elements. One or more consecutive lines of text are interpreted as one paragraph. The first line of a paragraph may be indented up to three spaces, the other lines can have any amount of indentation because paragraphs support line wrapping. In addition to the rules outlined in the section about line wrapping, a paragraph ends when a definition list line is encountered.

**Comment by jstolarek** [comment] 2020-03-26 20:32
> If you then run `bundle exec bin/gollum --versions` again, you should see `github-markdown` listed as your Markdown rendering gem.

Indeed, that works. Will I need to take some extra configuration steps if at some later date I install a released version of Gollum 5? Or will it just pick a system-wide installation of `github-markdown` in the same way version currently 4.x does?

> Interestingly, this is from the kramdown documentation:

The documentation also says:

> Notice that a line break in the source does not mean a line break in the output (due to the lazy syntax)!. If you want to have an explicit line break (i.e. a `<br />` tag) you need to end a line with two or more spaces or two backslashes!

Like I said, the behaviour that I reported goes against any Markdown specification I have seen so far. Also, inserting EOL with two backslashes never worked for me. That should probably get reported upstream.

**Comment by dometto** [comment] 2020-03-27 09:43
> Indeed, that works. Will I need to take some extra configuration steps if at some later date I install a released version of Gollum 5? Or will it just pick a system-wide installation of github-markdown in the same way version currently 4.x does?

The latter! Notice github itself has switched to using the `CommonMarker` gem, which you can also use with .

> Like I said, the behaviour that I reported goes against any Markdown specification I have seen so far. Also, inserting EOL with two backslashes never worked for me. That should probably get reported upstream.

It may be a conscious decision on kramdown's part to deviate from the markdown spec here. However, we're sticking with kramdown as default renderer because it works out of the box on both regular ruby (MRI) and JRuby. You could open an issue at kramdown if you want to know if there's a way to re-configure this!

**Comment by jstolarek** [comment] 2020-03-27 18:23
Thanks. I won't be reporting upstream - I'm not a Ruby programmer so I can't even provide a program that would replicate the problem.

**Comment by bartkamphorst** [comment] 2020-03-28 07:49
>  `=> "<p>foo\nbar</p>\n" `

@dometto Perhaps I spoke too soon. Because if it is really an issue with Kramdown, shouldn't it have produced `"<p>foo<br />bar</p>\n"` ? Compare:

```ruby
Kramdown::Document.new("foo  \n bar").to_html
 => "<p>foo<br />\n bar</p>\n" 
```

Here, the double space after `foo` does produce a `<br />` tag, but the newline in `foo\nbar` does not (correctly so).

**Comment by bartkamphorst** [comment] 2020-03-28 07:59
And `commonmarker` produces the same output as kramdown here:
```ruby
2.6.3 :003 > CommonMarker.render_html("foo\nbar", :DEFAULT)
 => "<p>foo\nbar</p>\n" 
```

**Comment by dometto** [comment] 2020-03-28 09:21
4.x (correctly) displays `foo\nbar`. But using both `commonmarker` and `github-markup` on 5.x, I also (correctly) get `foo\nbar`. So it is an issue with `kramdown`, or with the specific settings gollum uses kramdown with.

**Comment by dometto** [comment] 2020-03-28 09:24
Confirmed, this is an issue with Kramdown's GitHub Flavored Markdown mode. First time with all of gollum's settings, second time with all of the without `:input => 'GFM'`

```ruby
2.6.3 :001 > require 'kramdown'
 => true 
2.6.3 :002 > content = "foo\nbar"
 => "foo\nbar" 
2.6.3 :003 > Kramdown::Document.new(content, :input => "GFM", :auto_ids => false, :math_engine => nil, :smart_quotes => ["'", "'", '"', '"'].map{|char| char.codepoints.first}).to_html
 => "<p>foo<br />\nbar</p>\n" 
2.6.3 :004 > Kramdown::Document.new(content, :auto_ids => false, :math_engine => nil, :smart_quotes => ["'", "'", '"', '"'].map{|char| char.codepoints.first}).to_html
 => "<p>foo\nbar</p>\n" 
```

**Comment by bartkamphorst** [comment] 2020-03-28 09:41
Here's the fix!
```ruby
Kramdown::Document.new("foo\nbar", :input => "GFM", :hard_wrap => false).to_html
 => "<p>foo\nbar</p>\n"
```

**Comment by dometto** [comment] 2020-03-28 09:43
Thanks @bartkamphorst! Annoyingly, github seems to behave differently in the comments editor (here) and in the wiki:

```
dad
ddd
```

Renders here as follows:

dad
ddd

While on the wiki it is renedered as "dad ddd". CommonMarker also has a `HARD_BREAK` option, which appears to be true in the comments but false in the wiki. I guess we should go with 'false' then, as well?

**Comment by bartkamphorst** [comment] 2020-03-28 09:44
Ha, I was just about to report the same observation. 😄

**Comment by bartkamphorst** [comment] 2020-03-28 09:45
Yes, let's follow Github's wiki behavior.

**Comment by dometto** [comment] 2020-03-29 18:35
Fixed in https://github.com/gollum/gollum-lib/pull/369

**Closed by dometto** 2020-03-29 18:35 UTC

**Comment by dometto** [comment] 2023-01-19 21:50
This may be due to a recent issue with `nokogiri`, or rather the combination of the most recent version of `nokogiri` (`v1.14.0`) and gollum. This issue is fixed on gollum master, but since I believe @aka13-404 is using the JAR release of gollum `v5.3.0`, that would still be affected. Sorry about that! Think the best thing to do is to wait for gollum 6.0 to come out, which we hope to do take care of soon.
