### ISSUE TITLE
Link to anchors of absent internal pages

### ISSUE THREAD

**Issue by jplitza** [gollum/gollum#1096] opened 2015-12-03 20:10 UTC
We are experiencing issues with linking to anchors of internal pages. We expected `[[internal-page-name#anchor]]` to generate a link to the anchor "anchor" of the page "internal-page-name". However, what it does is to generate a link to the anchor "anchor" of the page "internal-page-name#anchor", which is totally nuts:

``` html
<a class="internal absent" href="/internal-page-name%23anchor#anchor">internal-page-name#anchor</a>
```

I don't know which would be the intended behaviour (link to the page "internal-page-name#anchor" or to the anchor "anchor" of the page "internal-page-name"), but surely this is a bug either way.

**Comment by dometto** [comment] 2017-04-14 10:16
Still present on `5.x` (and `master`), but interestingly, this only seems to happen for links to internal pages containing whitespace (or `-` which get subbed for whitespace).

This works correctly:
`[[Hobbit#Bilbo Baggins]]`

But this renders the reported mistaken behavior:

`[[Hobbit and Friends#Bilbo Baggins]]`

**Comment by dometto** [comment] 2017-04-14 10:32
Actually, scratch that. The issue is only with links to internal pages that don't exist anyway (whether or not the filename contains whitespace). The issue is [here](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/filter/tags.rb#L288), where `link_name` only gets set to `page name` rather than `page name#anchor` in case the page is actually found. For non-existent pages, `link_name` keeps containing the anchor, which then gets added a second time.

**Comment by dometto** [comment] 2017-04-17 20:44
Addressed in https://github.com/gollum/gollum-lib/issues/263, which will be in the upcoming `5.x` release.

**Closed by dometto** 2017-04-17 20:44 UTC
Labels: bug
