### ISSUE TITLE
Redirected to create-path after creating new page.

### ISSUE THREAD

**Issue by emil-nasso** [gollum/gollum#1208] opened 2017-03-21 07:12 UTC
If I create a new page, I get redirected to the create URL (ex: http://xx:1337/create/Internal%20Blog/Heyasdf ) after inputting the name of the new page.

If I add a body and save on this page I get this error:

![http://192.168.99.100:1337/create/Internal%20Blog/Heyasdf](http://192.168.99.100:1337/create/Internal%20Blog/Heyasdf)

Maybe you should be redirected to the edit page instead?

Or am I missing something? Feels weird such a basic bug is in there, creating pages is a very basic feature. Maybe something was changed recently?

**Comment by bartkamphorst** [comment] 2017-03-21 08:26
That certainly shouldn't happen, and I haven't seen it mentioned before. What does your setup look like?

**Comment by emil-nasso** [comment] 2017-03-21 10:15
I dug in a bit more when trying to create an reproducible example. The error occurs if you are on a subpage and click the new button there.

I attacked an example that should work.

Just unpack it, run `git init` in the wiki directory and commit the files.

Then go to `http://xxxx:1337/Internal-Blog/2017-03-21-What-is-up` and click the "new"-button, fill in a page name, click ok and the click save on the page you get redirected to.

**Comment by bartkamphorst** [comment] 2017-03-26 14:29
Thanks. I have successfully reproduced the issue, but have yet to understand the cause.

**Comment by dometto** [comment] 2017-04-17 20:56
Looks like this is another problem that was caused by whitespace substitution (notice that error occurs only in the subdirectory `Internal-Blog` -- the `-` character is being subbed for spaces on `master`, which means the eventual file lookup is for the filename *without* the `-`). On `5.x` everything works like a charm.

Might be a while before the release, but the root cause of the bug is fixed in there. I'll close this in the mean time to give us a better overview of which issues are still unaddressed.

**Closed by dometto** 2017-04-17 20:56 UTC
Labels: bug
