### ISSUE TITLE
5.x: drag/drop an image to the edit area gives "error uploading file: error" message

### ISSUE THREAD

**Issue by roscom** [gollum/gollum#1312] opened 2018-08-03 06:40 UTC
gollum -v : _Gollum 4.1.2_
gollum started as: _gollum --css --allow-uploads page --config config.rb --page-file-dir wiki__
config.rb: 
```ruby
Precious::App.set(:wiki_options, { 
        :universal_toc => true,
        :per_page_uploads => true,
})
```
Trace output is:
```
== Sinatra (v1.4.8) has taken the stage on 4567 for development with backup from Thin
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on 0.0.0.0:4567, CTRL+C to stop
2018-08-03 16:35:59 - TypeError - no implicit conversion of Symbol into Integer:
        /home/cb/.gem/ruby/2.5.1/gems/gollum-4.1.2/lib/gollum/app.rb:187:in `[]'
        /home/cb/.gem/ruby/2.5.1/gems/gollum-4.1.2/lib/gollum/app.rb:187:in `block in <class:App>'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
        /home/cb/.gem/ruby/2.5.1/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
        /home/cb/.gem/ruby/2.5.1/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call'
        /home/cb/.gem/ruby/2.5.1/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
        /home/cb/.gem/ruby/2.5.1/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
        /home/cb/.gem/ruby/2.5.1/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
        /home/cb/.gem/ruby/2.5.1/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call'
        /home/cb/.gem/ruby/2.5.1/gems/rack-1.6.10/lib/rack/nulllogger.rb:9:in `call'
        /home/cb/.gem/ruby/2.5.1/gems/rack-1.6.10/lib/rack/head.rb:13:in `call'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
        /home/cb/.gem/ruby/2.5.1/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
        /home/cb/.gem/ruby/2.5.1/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
        /home/cb/.gem/ruby/2.5.1/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
        /home/cb/.gem/ruby/2.5.1/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
        /home/cb/.gem/ruby/2.5.1/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process'
        /home/cb/.gem/ruby/2.5.1/gems/eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool'
```

**Comment by dometto** [comment] 2018-09-20 10:40
Cannot reproduce this on `master`, but strangely I am getting similar errors when trying to drag-and-drop upload on `5.x`. Stack trace is different though:
```
localhost - - [20/Sep/2018:12:38:24 CEST] "POST /uploadFile HTTP/1.1" 500 129636
http://127.0.0.1:4567/edit/Home.md -> /uploadFile
2018-09-20 12:38:28 - NoMethodError - undefined method `blobs' for #<Gollum::Git::Blob:0x007f7ef83a05d8>:
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/gollum-lib-5.0.a.4/lib/gollum-lib/committer.rb:101:in `add_to_index'
	/Users/dawa/Code/gollum_project/gollum/lib/gollum/app.rb:202:in `block in <class:App>'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `call'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `block in compile!'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:1011:in `route_eval'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:1040:in `block in process_route'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `catch'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `process_route'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:990:in `block in route!'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `each'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `route!'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:1097:in `block in dispatch!'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:1094:in `dispatch!'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `block in call!'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `call!'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:913:in `call'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/rack-protection-2.0.4/lib/rack/protection/xss_header.rb:18:in `call'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/rack-protection-2.0.4/lib/rack/protection/path_traversal.rb:16:in `call'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/rack-protection-2.0.4/lib/rack/protection/json_csrf.rb:26:in `call'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/rack-protection-2.0.4/lib/rack/protection/frame_options.rb:31:in `call'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/rack-2.0.5/lib/rack/null_logger.rb:9:in `call'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/show_exceptions.rb:22:in `call'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:194:in `call'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:1957:in `call'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `block in call'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:1729:in `synchronize'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `call'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/rack-2.0.5/lib/rack/handler/webrick.rb:86:in `service'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/webrick-1.3.1/lib/webrick/httpserver.rb:138:in `service'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/webrick-1.3.1/lib/webrick/httpserver.rb:94:in `run'
	/Users/dawa/.rvm/gems/ruby-2.4.1@gollum/gems/webrick-1.3.1/lib/webrick/server.rb:191:in `block in start_thread'
```

**Comment by dometto** [comment] 2018-09-20 10:41
@roscom we won't be fixing this on `4.x` but will address the errors I found in `5.x`.

**Comment by bartkamphorst** [comment] 2018-10-01 15:03
Confirmed on current `5.x`.

**Comment by dometto** [comment] 2018-10-01 17:07
@bartkamphorst, I take it you get the same stacktrace as I did?

**Comment by bartkamphorst** [comment] 2018-10-01 18:15
No, something different:
```
TypeError - no implicit conversion of Symbol into Integer:
        org/jruby/RubyString.java:3504:in `[]'
        C:/Users/gollum/gollum/lib/gollum/app.rb:176:in `block in POST /uploadFile'
        org/jruby/RubyMethod.java:113:in `call'
```

**Comment by dometto** [comment] 2018-10-19 23:36
I just tested and it turns out this is a grit issue. That is, I can't reproduce it on `5.x` with the rugged adapter (nor with rjgit).  Shall we keep this open or not, @bartkamphorst?

**Comment by bartkamphorst** [comment] 2018-10-20 06:48
> I can't reproduce it on 5.x with the rugged adapter (nor with rjgit). Shall we keep this open or not?

I can reproduce it with RJGit on Windows 10, so I'd like to keep it open.

**Comment by bartkamphorst** [comment] 2018-10-30 14:44
A tiny bit more info on this: the full error message says that it is an Internal Server Error.

**Comment by bartkamphorst** [comment] 2018-10-30 15:05
@dometto I can reproduce the `NoMethodError - undefined method blobs` on RJGit (I'm running gollum with `--allow-uploads page`). The problem seems to be that in `committer.add_to_index` the tree variable becomes a Blob in some instances:
```
tree is #<RJGit::Blob:0x7e59e828 ...>
```
The subsequent `tree.blobs.each` subsequently fails because a Blob instance does not have a `blobs` method. This part makes sense.

There is a tree initially, obtained by a call to `index.current_tree`, but the "transformation" happens [here](https://github.com/gollum/gollum-lib/blob/gollum-lib-5.x/lib/gollum-lib/committer.rb#L95) with this call: `tree = tree / dir`.

I'm not sure I understand the logic of what's happening there though, could you enlighten me?

**Comment by dometto** [comment] 2018-10-30 15:53
The `tree / 'path'` method simply returns an item (blob or tree) under `tree` named `'path'`. For some reason `tree / dir` is matching the filepath of a blob under `tree`. I take it that in this case, `dir` is the name of the directory correlated with the page in which you're uploading. So `dir` is similar (or equal?) to the name of the blob `Pagename.md` -- hence the conflict?

This may be a new problem in 5.x, because the `.md` is not getting deleted from the pagename, or some such..

**Comment by bartkamphorst** [comment] 2018-10-30 18:11
> So dir is similar (or equal?) to the name of the blob Pagename.md -- hence the conflict?

You are correct: drag/drop uploading a file on `http://localhost:4567/gollum/edit/Home.md` sets `dir` to `Home.md`.

> This may be a new problem in 5.x, because the .md is not getting deleted from the pagename, or some such.

Makes sense. 👍

**Comment by dometto** [comment] 2018-10-30 19:41
Right. I guess we want dir to be set to `Home` instead?

**Comment by dometto** [comment] 2018-10-30 19:47
Also, should we try to catch the exception or something, to prevent the app from breaking when somehow the wrong parameters are passed to the upload action?

**Comment by bartkamphorst** [comment] 2018-10-30 20:45
> Right. I guess we want dir to be set to Home instead?

Correct.

> should we try to catch the exception or something, to prevent the app from breaking when somehow the wrong parameters are passed to the upload action?

The committer could raise an exception if the tree variable isn't really a Tree, but that's not very Ruby-like. Or we could check if `tree.responds_to?(:blobs)` or something like that.

**Comment by dometto** [comment] 2018-10-31 11:29
Maybe it would be enough to just remove [this line](https://github.com/gollum/gollum/blob/5.x/lib/gollum/app.rb#L167).

**Comment by dometto** [comment] 2018-10-31 11:35
Deleted my previous message because it contained some bad advice. The incorrect setting of `dir` is caused by [this line](https://github.com/gollum/gollum/blob/5.x/lib/gollum/app.rb#L167), but I think we should alter [this one](https://github.com/gollum/gollum/blob/5.x/lib/gollum/app.rb#L583) to use the `::File.basename` of `@name`.

**Comment by dometto** [comment] 2018-10-31 12:14
> This may be a new problem in 5.x, because the .md is not getting deleted from the pagename, or some such.

Confirmed. The issue is that you can now go to `Home.md` in the browser, and that will set the `uploadDest` JS variable to `Home.md`, whereas previously you could only visit `Home` in the browser. See my PR for a fix.

**Comment by bartkamphorst** [comment] 2018-11-09 13:39
Note: the original error report used `--page-file-dir wiki_`. When the proposed fix is merged, we should double-check that the fix also works with a page-fil-dir set.

**Comment by dometto** [comment] 2019-05-03 23:33
After merging #1369 uploading itself works (the file is written to the repo) when using `:page_file_dir`, but the uploaded image does not display on the page. Without page file dir all is fine.

**Comment by bartkamphorst** [comment] 2019-08-23 07:07
I can confirm that uploading works without `page_file_dir`, both using the upload form and drag-and-drop uploading, but only if the repository already contains a tree. With an empty wiki repository, we still get an Internal Server Error:
```trace
2019-08-23 09:03:18 - NoMethodError - undefined method `tree' for nil:NilClass:
	bundler/gems/gollum-lib_rjgit_adapter-8d50148c47c7/lib/rjgit_adapter/git_layer_rjgit.rb:132:in `tree'
	gollum-lib/lib/gollum-lib/committer.rb:44:in `index'
	gollum-lib/lib/gollum-lib/committer.rb:83:in `add_to_index'
	gollum-lib/lib/gollum-lib/wiki.rb:769:in `write'
	gollum-lib/lib/gollum-lib/wiki.rb:241:in `write_file'
	gollum/lib/gollum/app.rb:221:in `block in POST /gollum/upload_file'
        [...]
```

**Comment by bartkamphorst** [comment] 2019-08-23 07:16
With `--page-file-dir _wiki` uploading with the upload form works fine. With drag-and-drop uploading something strange happens: the link that is inserted is without the page-file-dir, as expected (e.g., `[[jvw015.pdf|/uploads/jvw015.pdf]]`). However, when the page is rendered, this link is then turned into a live link with a location that does include the page-file-dir: `http://localhost:4567/_wiki/uploads/jvw015.pdf`.

**Comment by bartkamphorst** [comment] 2019-08-23 07:19
> when the page is rendered, this link is then turned into a live link with a location that does include the page-file-dir

@dometto Could this be an issue in gollum-lib's filter chain (e.g., in `tags.rb`)?

**Comment by bartkamphorst** [comment] 2019-08-23 08:46
> Could this be an issue in gollum-lib's filter chain (e.g., in tags.rb)?

To answer my own question: the issue is [here](https://github.com/gollum/gollum-lib/blob/gollum-lib-5.x/lib/gollum-lib/filter/tags.rb#L199). When I change the call from `file.path` to `file.url_path` the links are generated correctly. 👍 Pushed this fix to `gollum-lib-5.x`.

**Comment by dometto** [comment] 2019-08-23 08:57
good find! Can we just rescue the `tree` error, or alternatively, disable file upload unless there is a tree? or do we want the upload to create the tree if it's missing?

**Comment by bartkamphorst** [comment] 2019-08-23 09:02
I see no reason why drag-and-drop upload shouldn't work the first time you are creating a page (Home.md). The repo is there, it is initiated, it just doesn't contain anything yet. If Home.md can be created without issue, why couldn't `/uploads/document.pdf` not be created first when it is dropped onto the editor?

**Comment by dometto** [comment] 2019-08-23 09:40
Good point. looks like the problem could apply to files more generally, since the stack trace shows `Wiki#write_file` as the origin. That may make it easier to construct a test case.

**Comment by bartkamphorst** [comment] 2019-08-23 10:53
> Good point. looks like the problem could apply to files more generally, since the stack trace shows Wiki#write_file as the origin. That may make it easier to construct a test case.

That's what I was thinking too initially, but `write_file` really is just a wrapper to `write` and is called in pretty much the same way as for pages.

**Comment by bartkamphorst** [comment] 2019-08-26 12:18
Update: after fixing uploading with `page_file_dir _wiki` enabled as well as the uploading option `dir`, I'm now finding that uploading is broken with uploading option `page`. The observed behavior is that the files are uploaded to the root of the `page_file_dir` (e.g., in `_wiki`) instead of to `_wiki/uploads/[Pagename]`. The links are generated correctly (e.g., `[[_wiki/uploads/Home/doc.pdf]]`) but the files end up in `_wiki`.

**Comment by bartkamphorst** [comment] 2019-09-02 12:25
There were two separate issues here that needed to be dealt with. First, some code in the `upload_file` route in `app.rb` got deleted accidentally in a merge, which caused the `page` uploading to fail. Second, empty repositories were posing a separate issue to uploading and this had to do with `HEAD` being non-existent. Both issues have in principle been fixed, but I'll keep this issue open until the rugged adapter has also implemented the proposed fix for empty HEAD. In addition, I have added a set of tests for uploading, including a test for conflict detection.

**Comment by bartkamphorst** [comment] 2019-09-06 08:17
> I'll keep this issue open until the rugged adapter has also implemented the proposed fix for empty HEAD

This fix for the rugged_adapter was implemented [here](https://github.com/gollum/rugged_adapter/commit/c24d02b04bd179f04bc28827f7e5a4ca193b81e2). For completeness, the tests for uploading are [here](https://github.com/gollum/gollum/blob/5.x/test/test_app.rb#L375-L420). Since the reported issues with uploading have been resolved, I'm closing this issue, but I'll open a new issue for conflict detection failing.

**Closed by bartkamphorst** 2019-09-06 08:17 UTC
Labels: bug
