### ISSUE TITLE
Gollum crashes with empty repo

### ISSUE THREAD

**Issue by milaniliev** [gollum/gollum#32] opened 2010-09-01 20:14 UTC
When initializing a new repo, Gollum 1.0.1 crashes if there are no commits in the repository.

It would be awesome if Gollum had a init command that created a repo and initialized it with at least one commit.

**Comment by ajstadlin** [comment] 2016-10-01 20:42
Yes, still broken in Gollum 4.0.1

It is only broken until the first page is committed.

**Comment by dometto** [comment] 2017-04-13 22:38
Actually, I cannot reproduce this in either `4.0.1`, `4.1`, or `5.x` (unreleased), with either the `grit` or `rugged` adapters, so this does not appear to be an issue anymore. Closing.

**Closed by dometto** 2017-04-13 22:38 UTC
Labels: feature
