### ISSUE TITLE
how to import a website into gollum?

### ISSUE THREAD

**Issue by olzhas** [gollum/gollum#1725] opened 2021-05-27 18:42 UTC
Hello everyone,

I am looking for an automated method/tool to import the whole website for example this one - https://www.cv.nrao.edu/~abridle/toolmemo/node1.shtml - how can I do that?

thank you in advance for the help.

**Comment by dometto** [comment] 2021-05-28 12:12
I'm going to close this as it's not a bug or feature request. In general though, I'd try to:

1. Use a site archiving tool to obtain an HTML archive
1. Use an HTML to Markdown conversion tool (e.g. `pandoc`).
1. Commit all the files to a `git` repository

If you need more help, I recommend asking around on e.g. StackOverflow.

**Closed by dometto** 2021-05-28 12:12 UTC
