### ISSUE TITLE
Pure anchor links don't work in MediaWiki markup

### ISSUE THREAD

**Issue by DKroot** [gollum/gollum#1236] opened 2017-05-01 19:28 UTC
I have a MediaWiki ported to Gollum to run as our GitHub repo Wiki. I stumble upon one bug/limitation. In MediaWiki markup, [the canonical way to write anchor links is](https://www.mediawiki.org/wiki/Help:Links) `[[#See also|link text]]`. This, however renders in red and doesn't work on GitHub. 

After some experimentation, I found out that `[[My Page#See_also|link text]]` fixes the issue. But it would be a rather large hassle for us to go through all the pages and fix all the anchor links. We'd probably have to write a script to do that.

**Comment by dometto** [comment] 2017-05-01 20:03
You say it doesn't work on GitHub, but does it work in gollum? Note that the two are not the same, and we can't do anything about the former. Please also clarify for the other issues you've opened whether it's a GitHub or gollum issue. Thanks!

**Comment by DKroot** [comment] 2017-05-01 20:08
I got your point. I wasn't sure whether to file it with Github or straight with Gollum. Ultimately I need it on GitHub, but I can install and test Gollum locally if you want me to.

Please advise.

**Comment by dometto** [comment] 2017-05-01 20:13
Well, the GitHub wikis are no longer based on gollum, so if you're goal is to get it working there I'd advise contacting GitHub support (don't know how much they can do for you). Still, I'd be happy to have a look at any discrepancies between gollum and Mediawiki if you can confirm them. If you'd like to do that, could you just mention all the discrepancies in one issue and close the rest? Can't promise that we can fix all of them because of the way gollum parses link tags, but we can try. :)

**Comment by DKroot** [comment] 2017-05-01 20:41
OK, I'll do both: send these to GitHub support and test with Gollum locally. Out of curiosity, did GitHub fork Gollum or what engine do they now actually use?

**Comment by dometto** [comment] 2017-05-01 20:48
I guess you could call it a fork, but I have no idea how much code from this project (which *was* started by github to run their wikis) is still in their implementation. It may be a pretty thorough rewrite.

**Comment by DKroot** [comment] 2017-05-15 18:50
I confirmed that this issue is present in the latest Gollum (4.1.1) as well. I've also reported to GitHub.

**Comment by dometto** [comment] 2017-05-16 08:19
Thanks for the confirmation. I'll check first if this is still an issue in the `5.x` branch.

**Comment by bartkamphorst** [comment] 2018-11-27 16:12
> I'll check first if this is still an issue in the 5.x branch.

@dometto And, is it? 😏

**Comment by dometto** [comment] 2018-11-29 18:32
Confirmed on 5.x

**Comment by dometto** [comment] 2019-05-04 16:11
Fixed in 5.x (https://github.com/gollum/gollum-lib/pull/315)

**Closed by dometto** 2019-05-04 16:11 UTC
Labels: MediaWiki, help wanted
