### ISSUE TITLE
--page-file-dir does not work

### ISSUE THREAD

**Issue by tobru** [gollum/gollum#491] opened 2012-08-28 15:28 UTC
Using the --page-file-dir option does currently not work.
Steps for reproducing it:
* Create a subdirectory under your Git root, f.e. 'wiki'
* Start gollum: "gollum --page-file-dir wiki"
* Navigate to http://localhost:4567, add some text and save the new page
* The editor reloads with an empty field
* Readd some text an click save: "Duplicate page: Cannot write //home.md, found //home.md."

The page is saved to the Git Root, but searched under 'page-file-dir'

**Comment by dometto** [comment] 2015-01-27 20:35
Yes, if anyone would be willing to give this a try, that would be massively helpful.

**Comment by PaulMakepeace** [comment] 2015-09-23 23:05
Is this option considered working now?

My use case is hiving off the pages in `pages` so that `Gemfile` et al aren't served. I figured all I'd need to do is `page_file_dir: 'pages'`. Apparently though this then redirects `/` to `/pages/Home` and then even more strangely displays a `pages` subdir so all my pages are now served under `/pages/pages`!

**Comment by dometto** [comment] 2015-10-04 15:04
@PaulMakepeace, a fix for page-file-dir issues is being discussed in https://github.com/gollum/gollum-lib/pull/174 and https://github.com/gollum/gollum/pull/1077. Perhaps you could see if the issues you're encountering are addressed in those PRs, or let us know what else would have to be done?

**Comment by PaulMakepeace** [comment] 2015-10-05 20:27
I'm possibly confused by the intent of this flag (since those changes aren't helping).

Here are the docs for it:

> Specify the subdirectory for all pages. If set, Gollum will only serve pages from this directory and its subdirectories. Default: repository root.

For `page_file_dir: 'pages'` I'd expect the root URL (`/`) to serve what's under `./pages` in the repo. Instead what I see is sort of the reverse, `/` redirecting to `/pages/` and documents from the root of the repo appearing there.

**Comment by dometto** [comment] 2015-10-05 21:29
Thanks for the clarification. That *is* the intended behaviour, though we're planning to change it to what you initially thought.

**Comment by PaulMakepeace** [comment] 2015-10-05 21:31
I would you can ultimately implement something that allows the pages in their own part of the repo and not have `config.ru`, `Gemfile`, and friends served as documents. A quick win would be fixing the docs. `--base-path` and this seem to be confused.

**Comment by dometto** [comment] 2015-12-03 20:56
Closing in favor of #1052

**Closed by dometto** 2015-12-03 20:56 UTC
Labels: bug

**Comment by mrev11** [comment] 2017-01-19 10:13
Here is how Gollum 4.0.1 works on my Linux box

1. "gollum"  
Navigating to localhost:4567 I can see my existing Home.md page. Ok.

2. "gollum --page-file-dir ."
Navigating to localhost:4567 brings up a "Create New Page", Home, Note: This page will be created within "/". Is it right? I dont think so.
