### ISSUE TITLE
Gollum treats org mode differently in a preview than in the final page

### ISSUE THREAD

**Issue by TobyHFerguson** [gollum/gollum#1004] opened 2015-04-27 18:18 UTC
I am using org mode to document a process. I am trying to put together a list, as per [[http://orgmode.org/manual/Plain-lists.html]]. Org mode uses '1.' as the numbered bullet marker, and it automatically figures out when to restart the numbering. 

When I preview the following:

```
* Using this environment to give a demo
1. Using the [[./demo_resources][resources]] listing pick a machine on which to run your demo (lets say Machine M, and Demo Ksplice)
1. Log into that machine (Machine M)
1. Clone the demo from the repository
  #+BEGIN_SRC sh
  git clone git@ca-ovsx32.us.oracle.com:Denver-lab/KSpliceDemo.git
  #+END_SRC
1. =cd= to the demo directory
  #+BEGIN_SRC sh
  cd KSpliceDemo
  #+END_SRC
```

I get the expected result - a list 4 items long

However when I save it and go look at it as a finished page I see that the first 3 bullets come out correctly, 1, 2, 3, but that the fourth bullet is indented and starts again at '1' - this is incorrect.

**Comment by dometto** [comment] 2015-04-27 18:26
Looks like this is because of the source blocks, which gollum replaces with the rendered code. Might be that one too many newline is being printed by the code filter.

**Comment by SkyCrawl** [comment] 2015-04-28 08:01
@dometto 
I think the culprit is [this line](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/filter/code.rb#L22) which disregards indentation.

In the extract phase of the filter chain, the source block is replaced with a cache block, with no indentation, which means the renderer considers the cache block as something that "breaks out of the bullet scope" and thus the 4th bullet as a separate list.

**Comment by bartkamphorst** [comment] 2018-11-29 15:12
This issue is related to the normalization of line endings: the content going into the actual page view only has `\n` line endings while the preview has `\r\n` line endings. If I remove the `\r` from the preview content then the preview page is rendered in the same way as the actual page (which is the wrong way). I'm not sure yet what to make of this or how to address it, but this at least explains the difference in behavior.

**Comment by dometto** [comment] 2018-11-29 17:16
Nice catch. Weird though, I would think that \n and \r shouldn't make a difference for the markup renderer..

**Comment by bartkamphorst** [comment] 2018-12-04 08:08
> Weird though, I would think that \n and \r shouldn't make a difference for the markup renderer..

And you would be right. 😉 

```
$ grep -o "\r"  ~/Desktop/orgrenderdata_preview.txt | wc -l
  10
$ grep -o "\r"  ~/Desktop/orgrenderdata_actual.txt | wc -l
  0
```

```
2.4.1 :001 > require 'org-ruby'
 => true 
2.4.1 :002 > contents = ::File.open('~/Desktop/orgrenderdata_actual.txt', 'r').read
 => "* Using this environment to give a demo\n1. Using the [[./demo_resources][resources]] listing pick a machine on which to run your demo (lets say Machine M, and Demo Ksplice)\n1. Log into that machine (Machine M)\n1. Clone the demo from the repository\n  #+BEGIN_SRC sh\n  git clone git@ca-ovsx32.us.oracle.com:Denver-lab/KSpliceDemo.git\n  #+END_SRC\n1. =cd= to the demo directory\n  #+BEGIN_SRC sh\n  cd KSpliceDemo\n  #+END_SRC" 
2.4.1 :003 > Orgmode::Parser.new(contents).to_html
 => "<h1>Using this environment to give a demo</h1>\n<ol>\n  <li>Using the <a href=\"./demo_resources\">resources</a> listing pick a machine on which to run your demo (lets say Machine M, and Demo Ksplice)</li>\n  <li>Log into that machine (Machine M)</li>\n  <li>Clone the demo from the repository\n    <pre class=\"src\" lang=\"sh\">\ngit clone git@ca-ovsx32.us.oracle.com:Denver-lab/KSpliceDemo.git\n    </pre>\n  </li>\n  <li><code>cd</code> to the demo directory\n    <pre class=\"src\" lang=\"sh\">\ncd KSpliceDemo\n    </pre>\n  </li>\n</ol>\n" 
```

(The relevant observation being that there is only one pair of `<ol></ol>` in the rendered output of the contents with only `\n`, which is the correct, expected behavior, but different from what the OP reported.)

It would seem then that the normalized contents is treated differently in one of the (other) filters.

**Comment by bartkamphorst** [comment] 2018-12-04 09:05
Turns out the `code` filter does not match the ORG code block correctly with the `\r`'s present, resulting in the entire "untouched" string being sent to the renderer. So we now need to troubleshoot and fix two things:

1. The regular expression for matching ORG code blocks.
2. The way code blocks are reinserted during the `process` operation so that the renderer can produce the correct output.

**Comment by bartkamphorst** [comment] 2018-12-04 15:30
Fixed in `5.x` with https://github.com/gollum/gollum-lib/pull/316.

**Closed by bartkamphorst** 2018-12-04 15:30 UTC
Labels: Org-Mode, bug
