### ISSUE TITLE
[[_TOC_]] can't work in sidebar

### ISSUE THREAD

**Issue by WooHooDai** [gollum/gollum#1231] opened 2017-04-16 14:54 UTC
I saw [the wiki](https://github.com/gollum/gollum/wiki#table-of-contents-toc-tag) said `[[_TOC_]]` can be inserted into subpages. And #343 shows that.
But when I do that, my sidebar is just blank.

UPDATE: Sorry for duplication. After submitting this issue, I find #1161

**Comment by bartkamphorst** [comment] 2017-04-16 21:04
@WooHooDai As you said, this is a duplicate of #1161 , so I'm closing this (you can subscribe to notifications for #1161 for updates).

**Closed by bartkamphorst** 2017-04-16 21:04 UTC
