### ISSUE TITLE
Undefined method when changing github-markup's default renderings

### ISSUE THREAD

**Issue by jon1924** [gollum/gollum#1233] opened 2017-04-19 13:11 UTC
After reinstalling Gollum and Asciidoctor, if I include the suggested config snippet for [Changing github-markup’s default renderings settings (e.g., turning asciidoctor’s safe mode on)](https://github.com/gollum/gollum/wiki/Formats-and-extensions#changing-github-markups-default-renderings-settings-eg-turning-asciidoctors-safe-mode-on) in my ```config.rb``` file, I get the following error:
~~~~
undefined method `regexp' for :markdown:Symbol (NoMethodError)
~~~~

Removing this snippet fixes the issue (except that not using Asciidoctor's safe mode prevents proper use of Asciidoctor's `include::`, _etc._).

- Ubuntu-Gnome 17.04
- ruby 2.3.3
- asciidoctor 1.5.5
- github-markup 1.6.0
- gollum 4.1.1
- gollum-lib 4.2.5

Thanks for any ideas.

**Comment by dometto** [comment] 2017-04-19 13:24
I think there may be an error in the configuration snippet in the wiki:

```ruby
GitHub::Markup.markups.reject! {|markup| ... }
```

`Markup.markups` returns a hash of the form `{:format_name => {:regexp => /blah/, ...}}`. So `.reject! {|markup| } iterates over an `Array` of the form `[:format_name]`. I'm not at liberty to experiment, but please try changing the line as follows:

```ruby
GitHub::Markup.markups.reject! {|name, markup| ... }
```

If it works, could you please close this and update the wiki (its publically editable)? If not, please let us know (perhaps include the output of `GitHub::Markup.markups.inspect`).

**Comment by jon1924** [comment] 2017-04-19 13:56
Thanks.

This appears to fix the problem in the first line of the snippet. However, `github-markup` now has a problem with the second part of the snippet:
~~~~
GitHub::Markup.markup(:asciidoctor, /adoc|asc(iidoc)?/) do |content|
  Asciidoctor::Compliance.unique_id_start_index = 1
  Asciidoctor.convert(content, :safe => :safe, :attributes => %w(showtitle=@ idprefix idseparator=- env=github env-github source-highlighter=html-pipeline))
end
~~~~
The error is:
~~~~
/var/lib/gems/2.3.0/gems/github-markup-1.6.0/lib/github/markup.rb:63:in `markup': wrong number of arguments (given 2, expected 4..5) (ArgumentError)
~~~~

`GitHub::Markup.markups.inspect` gives no output in the console. Where should I be looking?

**Comment by dometto** [comment] 2017-04-19 14:00
> GitHub::Markup.markups.inspect gives no output in the console.

Ah yes, probably because `github-markup` is not yet required at that point. But that's ok since the problem with that part of the snipper has been solved.

I'm guessing the `wrong number of arguments` refers to the `Asciidoctor.convert` call? If so, then it looks like the signature for this method has changed in more recent versions of `asciidoctor`. Have a look at their documentation.

**Comment by dometto** [comment] 2017-04-27 16:49
@jon1924 did you get this to work? If so, please let us know about what the eventual fix was (or better yet, help us keep the wiki up to date).

**Comment by bartkamphorst** [comment] 2017-04-29 11:38
> I'm guessing the wrong number of arguments refers to the Asciidoctor.convert call?

No, it actually refers to the signature of the `markup` method, see [here](https://github.com/github/markup/blame/master/lib/github/markup.rb#L63). Must have been refactored recently. In any case, the snippet in the docs will need to be updated.

**Comment by dometto** [comment] 2017-04-29 15:38
Updated the wiki.

**Closed by dometto** 2017-04-29 15:38 UTC

**Comment by bartkamphorst** [comment] 2017-04-29 16:01
I take it you confirmed that the new and improved snippet works as expected? 😉
